/**
 * DejaVu Sans Condensed Bold, recortada a los caracteres que usa el ticket,
 * en base64 para que jsPDF la pueda embeber en el PDF.
 *
 * ARCHIVO GENERADO — no editar a mano. Para regenerarlo, desde la raíz del
 * repo (necesita `pip install fonttools`):
 *
 *   python -m fontTools.subset \
 *     backups/dejavu-sans/DejaVuSansCondensed-Bold.ttf \
 *     --unicodes="U+0020-007E,U+00A0-00FF,U+2013,U+2014,U+2018,U+2019,\
 *                 U+201C,U+201D,U+2022,U+20A2,U+20B2,U+2026" \
 *     --layout-features="" --no-hinting --desubroutinize \
 *     --drop-tables+=DSIG,GSUB,GPOS,GDEF --name-IDs="1,2,3,4,6" \
 *     --notdef-outline \
 *     --output-file=client/src/assets/fonts/DejaVuSansCondensed-Bold.subset.ttf
 *
 * y después volver a codificar el .ttf en base64 acá.
 *
 * El subset deja los 99 caracteres que el ticket puede imprimir (ASCII + Latin-1
 * con acentos y ñ + guiones y comillas tipográficas + el símbolo de guaraní) y
 * baja la fuente de 649 KB a 15 KB. Se verificó que los anchos de esos 99
 * caracteres son idénticos a los de la fuente completa.
 *
 * La tabla `name` NO se puede quitar: el parser de TTF de jsPDF la necesita y
 * revienta sin ella.
 *
 * Licencia: Bitstream Vera Fonts Copyright (c) 2003 Bitstream, Inc., y los
 * cambios de DejaVu están en dominio público. Permite redistribuir. El texto
 * completo está en backups/dejavu-sans/DejaVu Fonts License.txt.
 */
export const DEJAVU_SANS_CONDENSED_BOLD_BASE64 =
  "AAEAAAALAIAAAwAwT1MvMmsoEbAAADpMAAAAVmNtYXBlMFHxAAA6pAAAAPhnYXNwAAcABwAAPJQAAAAMZ2x5ZtrNdzIAAAC8AAA0" +
  "GmhlYWQNPgG+AAA2pAAAADZoaGVhDfYHVAAAOigAAAAkaG10eNXXUVcAADbcAAADTGxvY2HuwPyAAAA0+AAAAaxtYXhwARUDywAA" +
  "NNgAAAAgbmFtZQ6uIy0AADucAAAA2HBvc3T/gQBaAAA8dAAAACAAAgBb/pYD9gWkAAMABwAAExEhESUhESFcA5n8zgLM/TT+lgcO" +
  "+PJyBikAAgECAAACRwXVAAUACQAAASERAyMDESERIQECAUQu6C4BRP68BdX9w/5eAaL9zP6cAAACAK8DqgMRBdUAAwAHAAABESMR" +
  "IxEjEQMR1bfVBdX91QIr/dUCKwAAAgB9AAAFjAW+ABsAHwAAAQMzEzMDMxUhAyEVIQMjEyMDIxMjNSETIzUhEwEjAzMDNFbtV8dX" +
  "+f7XPgEA/tFWx1btV8hW+wEnP/4BMFYBL+4/7gW+/n8Bgf5/1f7u1/6BAX/+gQF/1wES1QGB/ar+7gAAAwCQ/tMEhgYUACMAKgAx" +
  "AAABIwMuAScRHgEXEScuATU0Nj8BMxUeARcVLgEnERceARUUBgcDEQ4BFRQWExE+ATU0JgLMkgFx0mRn1G0e17XczQGSWrRaWrRa" +
  "HOW4296SQE1H2E5OSP7TAS0FLikBBjs/BAE3Biq0qbPJCefjCCIb/iovBf7hBii7t7jFDgNCAQUERTU7Q/6x/uoBQkJEQwAABQA7" +
  "/+MG/QXwAAsAFwAbACcAMwAAASIGFRQWMzI2NTQmJzIWFRQGIyImNTQ2ASMBMyEyFhUUBiMiJjU0NhciBhUUFjMyNjU0JgWUQEZG" +
  "QEFFRkCowMCop8LC/W7HA0jI+/6owMCop8DAp0BGRkBBRkcCaHtyc3t7c3J7qNi9vdvbvbzZ/NMGDdm9vdravb3ZqHxyc319c3J8" +
  "AAIAbv/jBfoF8AAmADAAAAkBPgE3IQYCBwEhJw4BIyIANTQ2Ny4BNTQ2MzIWFxEuASMiBhUUFgMOARUUFjMyNjcCzwFwMDEFARgO" +
  "ZFkBCP6CWF7Rde3+3ICSJiTlvlKxYFSXSEZMLIg6PJlrPGktA9/+Pkaubrb+5Gv+vm1GRAEV25LhajVqOqPEHR3+6jAuOzYiV/7T" +
  "L3dHc6IpKQAAAQCvA6oBhQXVAAMAAAERIxEBhdUF1f3VAisAAAEAnv7yArcGEgANAAABISYCNTQSNyEGAhUUEgK3/vWKhIWJAQtz" +
  "dHP+8vcBvdvbAcH17f473d3+OgABAJP+8gKsBhIADQAAEzYSNTQCJyEWEhUUAgeUc3NzcwELiYSDiv7y7gHG3d0Bxe31/j/b2/5D" +
  "9wAAAQAkAjkDnwXwABEAAAENAQclESMRBSctATcFETMRJQOf/tcBKUT+1Jn+00QBLf7TRAEtmQEsBMGtro24/qgBWLiNrq2NtgFY" +
  "/qi2AAEAwwAABUYFBAALAAABESEVIREjESE1IREDbwHW/irW/ioB1gUE/fTs/fQCDOwCDAAAAQBi/t0CAQGDAAUAABMhEQMjE7wB" +
  "RN7AWgGD/s/+iwF1AAEAYwG8ApoC3wADAAATIREhZAI1/csC3/7dAAABALwAAAIBAYMAAwAAEyERIbwBRP68AYP+fQAAAQAA/0IC" +
  "ogXVAAMAAAEzASMB2cj+JscF1fltAAIAWP/jBKsF8AALABcAAAEQJiMiBhEQFjMyNgEQACEgABEQACEgAANQX29wX19wbmABWv7g" +
  "/vj+9v7gASABCgEIASAC7AEY5eX+6P7l6OgBGP6N/m0BkwFzAXQBk/5tAAEAzwAABIQF1QAKAAATIREFESUhESERIdgBMv7GATgB" +
  "SgEy/FQBCgPFSAEGSPs1/vYAAQCRAAAEYwXwABgAAAEhESERAT4BNTQmIyIGBxE+ATMyBBUUBgcCEwJP/DAB6kI/f2lRwW515W7x" +
  "AQtxtgEb/uUBGwHhQn5EaYBNTAFIKy3s03rTsQABAHv/4wRwBfAAKAAAAR4BFRQEISImJxEeATMyNjU0JisBNTMyNjU0JiMiBgcR" +
  "PgEzIAQVFAYDW4eO/s7+2mfQZmHAXYqSlpOKkoKAfHJUqlVnyWEBBgEEfAMlJ8GV3uclJQEpNjdqY2Zp+FtdVl4qKQEaICC/wIOn" +
  "AAIAUgAABK4F1QACAA0AAAkBIQMhETMRIxEhESERAqf+hAF8OgGBwMD+uf2sBJj9jwOu/FL+6f7wARABSgAAAQCO/+MEggXVAB0A" +
  "ABMhESEVPgEzMgAVFAAhIiYnER4BMzI2NTQmIyIGB8MDXv23J1Ar9gES/tb+93Lgb27FV36RkX5KqmEF1f7l5wwN/u/08v7uMTIB" +
  "L0ZGiXV2iCstAAACAHL/4wSgBe4ACwAkAAABIgYVFBYzMjY1NCYBES4BIyIGBz4BMzISFRQAIyAAERAAITIWAptbW1tbXFtbAVBV" +
  "l0ibrQ47i1HP/f7l7v76/uEBUAEkXa8C4YODg4ODg4ODAs3+7C0rv7wxMf702fD+3wGJAWkBcgGnIAAAAQB7AAAEcAXVAAYAABMh" +
  "FQEhASF7A/X99P6uAfD9eQXV2fsEBLoAAAMAcP/jBJEF8AALACMALwAAASIGFRQWMzI2NTQmJS4BNTQ2MzIWFRQGBx4BFRQEISAk" +
  "NTQ2ExQWMzI2NTQmIyIGAoJiaGhiYGdn/qN7fP729P19eomL/vf++/76/vSM2llTUVhYUVNZApx2bm51dW5vdX8pqn+9xsW+f6op" +
  "Kr2Q3uPj3pC9AVVZYGBZWV9gAAIAX//jBI0F7gAYACQAADcRHgEzMjY3DgEjIgI1NAAzIAAREAAhIiYBMjY1NCYjIgYVFBa4U5dK" +
  "m60PPYtRzv0BGu0BBwEg/q/+21+tAVlbXFxbW1xcIQEUKyu/vDIyAQva8QEi/nb+mP6O/lkfAu6Dg4KEhIKDgwAAAgDOAAACEwRg" +
  "AAMABwAAEyERIREhESHOAUX+uwFF/rsEYP59/qb+fQAAAgB0/t0CEwRgAAUACQAAEyERAyMTESERIc4BRd/AWgFF/rsBg/7P/osB" +
  "dQQO/n0AAQDDAD0FRgTHAAYAAAkCFQE1AQVF/J0DY/t+BIIDzf60/rb6Ac/sAc8AAgDDAScFRgPbAAMABwAAEyEVIRUhFSHDBIL7" +
  "fgSC+34D2+vc7QABAMMAPQVGBMcABgAAEzUBFQE1AcMEgvt+A2UDzfr+Mez+MfoBSgAAAgB+AAADtgXwAB0AIQAAASE1NDY/AT4B" +
  "NTQmIyIGBxE+ATMyFhUUBg8BDgEVBSERIQJ+/rs8XzozMFdNSalcbbRU2+dHVDo9Jv67AUX+uwH4MVJ/Yjo0XC5GT0NCAToqKMe/" +
  "YptZOT5LLcH+nAACAHn+nAaxBaAACwBNAAABFBYzMjY1NCYjIgYBDgEjIiY1NDYzMhYXNTMRPgE1NCYnJiQjIgYHBgIVFBIXHgEz" +
  "MjY3FwYEIyIkJyYCNTQSNzYkMzIEFx4BFRAAISMC7F5RUV9gUVBeAXEbeFCbwcKaUHgbvHB/NDVV/v+Vab9QhpRgW1rphHLjUGBx" +
  "/veJpv7Yc3N4enFyAS2iygFJb0NG/tr+9SMCG3uOj3p5jY3+WkdP+cjI+lBHg/1LE8mdZK9JeoQ9O2L+ybWV/vtkYmdeUKJhZ4N9" +
  "fQFJvbYBSn18iKuhYuV+/vH+1AACAAkAAAWKBdUABwAKAAABIQMhASEBIQEhAwPZ/eJW/qQB8gGdAfL+o/3kAXC3ARD+8AXV+isC" +
  "JQJSAAADAKkAAAT8BdUACAARACAAAAEyNjU0JisBERMyNjU0JisBEQEeARUUBCkBESEgFhUUBgLDUlVVUr/LaWlpacsCDXB6/vn+" +
  "9P3BAggBGPtbA5NQTk1R/sT9c2JjYWH+eQIZJMKN2NQF1bzPbZkAAAEAW//jBNMF8AAZAAAlDgEjIAAREAAhMhYXES4BIyICFRQS" +
  "MzI2NwTTYM9w/rD+eAGIAVBwz2Bhu2e61NS6Z7thUjc4AaEBZQFmAaE4N/7LSUT++Ojn/vhESQAAAgCpAAAFmgXVAAgAFwAAAREz" +
  "MjY1NCYjASEgBBcWEhUUAgcGBCkBAgR81ODf1f4pAW4BMgEra19cXF9s/tL+0v6SBLL8cerf3ugBI2F0Zf74p6n+92V0YQAAAQCp" +
  "AAAEZQXVAAsAABMhESERIREhESERIakDp/20Ain91wJg/EUF1f7d/ur+3f6q/t0AAAEAqQAABFEF1QAJAAATIREhESERIREhqQOn" +
  "/bQCKf3X/qUF1f7d/ur+3f2HAAABAFv/4wVhBfAAHQAAJQYEIyAAERAAITIWFxEuASMiAhUUEjMyNjcRIxEhBWGC/umU/rD+eAGP" +
  "AVyG9m1x3nDP4NjHNl0k0wIcb0ZGAaEBZQFpAZ44N/7LR0b+/+/t/v4PEAEiAQIAAAEAqQAABV4F1QALAAATIREhESERIREhESGp" +
  "AVsB/wFa/qb+Af6lBdX9xwI5+isCef2HAAABAKkAAAIEBdUAAwAAEyERIakBW/6lBdX6KwAAAf+Y/mYCBAXVAAsAABMhERAAISMR" +
  "MzI2NakBW/7v/uxHNmxvBdX6vP7p/uwBI4aCAAABAKkAAAXNBdUACgAAEyERASEJASEBESGpAVsB8wGT/XgCyv5O/er+pQXV/d8C" +
  "If09/O4CTP20AAEAqQAABGUF1QAFAAATIREhESGpAVsCYPxFBdX7Tv7dAAABAKkAAAaBBdUADAAAEyEJASERIREBIwERIakBuQEy" +
  "ATQBuP64/svc/sv+twXV/OEDH/orBET82wMl+7wAAAEAqQAABV4F1QAJAAATIQERIREhAREhqQGDAekBSP59/hj+twXV/AAEAPor" +
  "BAD8AAAAAgBb/+MFwwXwAAsAFwAAASICFRQSMzISNTQCAyAAERAAISAAERAAAw+er6+en6+vnwFEAW/+kf68/r3+kAFwBNn+/Ozr" +
  "/vwBBOvsAQQBF/5k/pX+lv5kAZwBagFrAZwAAgCpAAAE/AXVAAoAEwAAEyEgBBUUBCEjESEBETMyNjU0JiOpAj8BAQES/u7+/+T+" +
  "pQFbv2VubmUF1f3q6/39+gS+/l9tZGRsAAACAFv+1QXDBfAADwAbAAAFIyAAERAAISAAERQCBwEhASICFRQWMzISNTQCAzQb/rT+" +
  "jwFwAUMBRwFswbYBD/62/v+er6uin6+vGwGYAWwBawGc/mj+kfz+lFz+sAYE/vzs8P8BBOvsAQQAAgCpAAAFZwXVAAgAHAAAATI2" +
  "NTQmKwEZAiERISAWFRQGBx4BFxMhAy4BIwKWbF9fbJL+pQIRAQr3gIJHcTm8/o+jMmZUAz9aZ2ZY/oH+9v3LBdXG1pS+LRJ/gf5Y" +
  "AXNwUgABAIT/4wSpBfAAJwAAAREuASMiBhUUFh8BHgEVFAQhIiQnER4BMzI2NTQmLwEuATU0JDMyFgRQbtNefHdQapPhvP75/vGA" +
  "/v+BgfBwcXlSe4bJuwEE8m/qBab+xDc4TFA8QxghMsy89/E2NQFFTE1UTkZMHiEw0rLf8CUAAQAJAAAE4AXVAAcAABMhESERIREh" +
  "CQTW/kP+pf5CBdX+3ftOBLIAAAEAqf/jBTAF1QARAAATIREUFjMyNjURIREQACEgABGpAVtte3xtAVv+4f7b/tv+4gXV/IG5n5+5" +
  "A3/8gf7D/soBNgE9AAABAAkAAAWKBdUABgAAEyEJASEBIQkBXAFlAWMBXf4O/mMF1fuyBE76KwABADYAAAe4BdUADAAAEyEbASEb" +
  "ASEBIQsBITcBTOjnAU7m6AFK/sP+cPTx/nAF1fvDBD37wwQ9+isEb/uRAAEAIwAABWkF1QALAAAJASEJASEJASEJASEDlgHS/pf+" +
  "xv7J/pUB0v5AAWoBJgEmAWsC+v0GAf7+AgL6Atv+HwHhAAH/7gAABUkF1QAIAAADIQkBIQERIRESAXsBMgEyAXz+AP6lBdX97AIU" +
  "/KD9iwJ1AAEAUgAABOYF1QAJAAATIRUBIREhNQEhaARp/S8C5vttAtH9RAXV6fw3/t3pA8kAAAEAnv7yAs4GFAAHAAATIRUjETMV" +
  "IZ4CL/39/dEGFOH6oOEAAAEAAP9CAqIF1QADAAAFATMBAdn+J8cB2r4Gk/ltAAEAff7yAqwGFAAHAAABITUzESM1IQKs/dH9/QIv" +
  "/vLhBWDhAAEAugOoBU8F1QAGAAAJASMJASMBA3MB29n+j/6Q2gHcBdX90wEt/tMCLQAAAQAA/h0Dmv7bAAMAAAEVITUDmvxm/tu+" +
  "vgABAFQE7gJSBmYAAwAAARMjAQFT/rD+tAZm/ogBeAACAE//4wRLBHsACgAlAAABIgYVFBYzMjY9ASURITUOASMiJjU0NiEzNTQm" +
  "IyIGBxE+ATMgFgJfZWZSSVt8AUX+u0GidJ3D9AEFvnl/aLJNaNFoARHyAfhMSkRNkW0ph/2BpmZdy6LFuBxVTy4uAREcHe8AAAIA" +
  "mv/jBNUGFAALABwAACUyNjU0JiMiBhUUFgM+ATMyEhEQAiMiJicVIREhArNobW1oZ29vb0Oiabrw8LppokP+vgFC56igoKipn5+p" +
  "AtViXf63/v3+/f63XWKiBhQAAAEAT//jA8oEewAZAAABES4BIyIGFRQWMzI2NxEOASMgABEQACEyFgPJQYVHh5aWh0yIOUucTv7v" +
  "/swBNAERT5oEPf7cMjCvnZ2vMjH+2x8fATcBFQEVATcfAAIAUv/jBI0GFAAQABwAAAERIREhNQ4BIyICERASMzIWAzI2NTQmIyIG" +
  "FRQWA0kBRP68Q6Bquu/vummhkmhtbWhmbW0DvAJY+eyiY1wBSQEDAQMBSV38yaigoKiooKCoAAIAT//jBIkEewAUABsAAAEVIR4B" +
  "MzI2NxEOASMgABEQACEyAAU0JiMiBgcEif0PC41+ZtVwcuVy/u7+0QEqAQXuAR3+tWtXXXUPAjNmfn5DRP7sMDEBNQEXARIBOv7C" +
  "k2Z9dW4AAAEAIwAAAzMGFAATAAABFSMiBh0BIREhESERIxEzNTQ2MwMyskQ2ARP+7f69oKC4wQYU6zdETv8A/KADYAEATrevAAIA" +
  "Uv5GBI0EeQAcACgAACUOASMiAjU0EjMyFhc1IREQACEiJicRHgEzMjY1AyIGFRQWMzI2NTQmA0lDoGq48fG4aqBDAUT+zf7cXrFZ" +
  "VaJSnpTVZG9sZ2VwcL5iXAFD+vsBQVxjpvwR/vL+4yAhARc2NZqkAwaklpqfpJWWpAAAAQCaAAAEkQYUABcAAAERITURNCYnLgEj" +
  "IgYVESERIRE+ATMyFgSQ/rwMDhNBKWVz/r4BQkmkY661Aqr9Vm8BmZNuGiMnrZn92QYU/ahiXe4AAAIAmgAAAd0GFAADAAcAABMh" +
  "ESERIREhmwFC/r4BQv6+BGD7oAYU/twAAAL/wv5GAd0GFAALAA8AABMhERQGKwE1MzI2NREhESGbAULCuZ84W0UBQv6+BGD7tOHt" +
  "61yHBgD+3AABAJoAAATtBhQACgAAEyERASEJASEBESGbAUIBcwF2/hQCE/55/nf+vgYU/LEBm/3+/aIB0/4tAAEAmgAAAd0GFAAD" +
  "AAATIREhmwFC/r4GFPnsAAABAJkAAAbvBHsAJQAAAT4BMzIWFREhET4BNTQmIyIGBxEhETQmIyIGFREhESEVPgEzMhYEQT2oZa62" +
  "/rwBAT9HW2QC/rw6Slxl/rwBRDuaXWihA6Zobe7j/VYCSA0cGndrqJ/92gJIumupnf3ZBGCkX2BwAAEAmgAABJEEewAXAAABESE1" +
  "ETQmJy4BIyIGFREhESEVPgEzMhYEkP68DA4TQSllc/6+AUJJpGOutQKq/VZvAZuRbhojJ62Z/dkEYKRiXe4AAgBP/+MEpAR7AAsA" +
  "FwAAASIGFRQWMzI2NTQmAyAAERAAISAAERAAAnprcHBram9vagEFAST+3P77/vz+2QEnA3uroaGrq6GhqwEA/sj+7P7s/sgBOAEU" +
  "ARQBOAACAJr+VgTVBHsAEAAcAAAlESERIRU+ATMyEhEQAiMiJhMiBhUUFjMyNjU0JgHd/r4BQkOiabrw8LppopNnb29naG1tov20" +
  "BgqkYl3+t/79/v3+t10DN6mfn6mooKCoAAACAFL+VgSNBHkACwAcAAABIgYVFBYzMjY1NCYTDgEjIgIREBIzMhYXNSERIQJ0Zm1t" +
  "ZmhtbW1DoGq67++6aqBDAUT+vAN3qKCgqKigoKj9K2NcAUkBAwEDAUdcY6b59gABAJoAAAOIBHsAEQAAAS4BIyIGFREhESEVPgEz" +
  "MhYXA4grUyt8hv6+AUI+oXEQJiQDLxYVsaX9/ARguG5lAwUAAQBf/+MD8gR7ACcAAAERLgEjIgYVFBYfAR4BFRQGIyImJxEeATMy" +
  "NjU0Ji8BLgE1NDYzMhYDrmfBVVxZQ1g4+Kvu7GTVcGDLaF5gQmI5163c41nEBD3+8DAwMzUrLgsJI6Crs7QjIwEQNDQ6OTAvDQge" +
  "oqWyrB4AAQAYAAADRwWeABMAAAERIREhERQWOwERISImNREjETMRAfsBTP60N1Om/uy/oKCgBZ7+wv8A/iVON/8AsdQB2wEAAT4A" +
  "AAEAkP/jBIYEYAAZAAATESEVFAIVFBYXHgEzMjY1ESERITUOASMiJpABRAINDxRAKWVzAUL+vkmjYq63AbQCrHBb/u0uh3cbIyas" +
  "mQIp+6CiYl3uAAEAGwAABJcEYAAGAAATIRsBIQEhHAFC+/oBQ/50/p4EYPz6Awb7oAABAEAAAAZnBGAADAAAEyEbASEbASEBIQsB" +
  "IUEBOamqAQ2qqgE5/vb+oaup/qAEYPz8AwT9BAL8+6ADAvz+AAEAGwAABIkEYAALAAAJASEbASEJASELASEBmv6UAVXO0QFV/pQB" +
  "fv6r4+D+qwI9AiP+tAFM/d/9wQFi/p4AAQAW/kYEkQRgAA8AABMhARMhAQ4BKwE1MzI2PwEWAUMBD+YBQv5YQKqLu2VSSxUJBGD9" +
  "CAL4+za7les6Sx8AAAEAUgAAA9kEYAAJAAATIRUBIREhNQEhaQNw/e0CE/x6AhP+AwRg+v2a/wD6AmYAAAEA5v6yBDoGFAAkAAAF" +
  "FSMiJj0BNCYrATUzMjY9ATQ2OwEVIyIGHQEUBgceAR0BFBYzBDrExLRhgDc3gGG0xMQ+f01RY2RQTX9t4bDBwJZ133SWzcGv4VeO" +
  "pp2OGRuOnKaPVwABAOr+HQG3Bh0AAwAAAREjEQG2zAYd+AAIAAAAAQDm/rIEOgYUACQAABczMjY9ATQ2Ny4BPQE0JisBNTMyFh0B" +
  "FBY7ARUjIgYdARQGKwHmP35NUWRkUU1+P8TEtGGANzeAYbTExG1Xj6acjhsZjp2mjlfhr8HNlnTfdZbAwbAAAAEAwwGyBUYDUgAd" +
  "AAABFQ4BIyInJicmJyYjIgYHNT4BMzIXFhcWFxYzMjYFRV+hV2CBDAgGDYxUUJpZYaBWYIEOBgYOi1VNmANS9FBFOgYDAwY9TVP0" +
  "UEU6BgMDBj1LAAIBAv6LAkcEYAAFAAkAAAEREzMTEQERIREBAi7oLv68AUT+iwI9AaL+Xv3DBHEBZP6cAAACAJz+xwQVBZgABgAj" +
  "AAABDgEVFBYXAREuASsBET4BNxEOASsBESMRJgIRNBI3ETMRHgECeEZGRkYBnUOAOw1QiDNLgzQJkuzv8+iSQIUDWiyTbG2UKgM5" +
  "/twwMv1pATIv/tseIP7kASAoAS4BAvQBIyMBH/7hAx0AAAEAcAAABGoF8AAbAAABES4BIyIGHQEhFSERIREhETMRIzUzNRA2MzIW" +
  "BF8/hkVqZgFQ/rAB5fwGza+v5PhTowW6/uInJn2Dqu/+uv72AQoBRu+qAQ/4GwACAEIAPQRUBMUAIwAvAAABByc3LgE1NDY3JzcX" +
  "PgEzMhYXNxcHHgEVFAYHFwcnDgEjIiY3MjY1NCYjIgYVFBYBh7uJuhkaHBq8irosYTcwYjO6iboaGRobuoq7KWA4NGKWUnNzUlJz" +
  "cQEMz5rPMWs/P2wuzZrPHh0bHM+azzduNj9pL8+Zzh4dG7Z/XFx/f1xdfgAAAQAWAAAE7QXVABgAAAEhESERITUhNSchNSEBIQkB" +
  "IQEhFSEHFSEExv5n/qn+ZwGZLP6TAQf+0gFoAQQBAwFo/tEBCP6TLAGZAaD+YAGgwkJWwAIb/jMBzf3lwFZCAAIA6v6iAbcFmAAD" +
  "AAcAAAERIxETESMRAbbMzMwFmP0KAvb8AP0KAvYAAAIADP89A5MF8AAzAD8AAAEVLgEjIgYVFBcWFx4BFRQGBx4BFRQGIyImJzUe" +
  "ATMyNjU0JyYnLgE1NDY3LgE1NDYzMhYBDgEVFBYXPgE1NCYDHFmOM0REqRgLvY9lakZD2r9No1tnpDM7RqIhEbaQY2ZDO861TKL+" +
  "vj48b6Q6P3wFtuMnJzEvQ08LBVmtfXWfMClxSZGnHR3tKSsyKEZKDghXs4JomjMzb0uQoh39hRxMMkNiQhdPNENqAAIAsQU7AukG" +
  "MQADAAcAABMzFSMlMxUjsdTUAWTT0wYx9vb2AAMA/gAABjUFzQAZADEASQAAARUuASMiBhUUFjMyNjcVDgEjIiY1NDYzMhYnIgYH" +
  "DgEVFBYXHgEzMjY3PgE1NCYnLgEnMhYXFhIVFAIHDgEjIiYnJgI1NBI3PgEEpzRjNGZycmY6Zyo7dji95eW9P3PWbbtPTk5OTk68" +
  "bW66Tk5PT05Pu2yI7WJiYWFiYu2Iie1iYmFhYmLtBGbXJSOAcnN+JCPVFhfqwsPpFbdXV1fPennPV1ZWVVdXz3l6z1dYVppubW3+" +
  "+pqY/vttbW5ubW0BBZiaAQZtbW4AAwCOAXUDhQXwAAMADgApAAATIRUhASIGFRQWMzI2PQE3ESM1DgEjIiY1NDY7ATU0JiMiBgc1" +
  "PgEzMhaeAtz9JAGleF48NFBn8d0xflWClL3Me1BNTpVIU5hEycMCPcgCxDQ+MzpyVxZU/kB/TEiGdI2EFDg7IyO0HByvAAIAjgCJ" +
  "A/kEJwAGAA0AAAEVDQEVATUBFQ0BFQE1Akr++AEI/kQDa/75AQf+RAQn8t3d8gFxugFz8t3d8gFxugABAMMBHwVGA40ABQAAEyER" +
  "IxEhwwSC0/xRA439kgGBAAEAYwG8ApoC3wADAAATIREhZAI1/csC3/7dAAAEAP4AAAY1Bc0AFwAgADQATAAAASIGBw4BFRQWFx4B" +
  "MzI2Nz4BNTQmJy4BAyMVMzI2NTQmJzIWFRQGBx4BHwEjJy4BKwERIxEBMhYXFhIVFAIHDgEjIiYnJgI1NBI3PgEDmm27T05OTk5O" +
  "vG1uuk5OT09OT7ugHx9GSEYmnp1fViU/G2POYCI0GgvAAROI7WJiYWFiYu2Iie1iYmFhYmLtBTNXV1fPennPV1ZWVVdXz3l6z1dY" +
  "Vv7ZzzU0NDKKd3lWcBEWUDrd1U5B/pwDRAE3bm1t/vqamP77bW1ubm1tAQWYmgEGbW1uAAABALEFWALpBhQAAwAAEyEVIbECN/3J" +
  "BhS8AAIAoANkAvgF/gALAB0AAAEiBhUUFjMyNjU0JicyFhceARUUBgcOASMiJjU0NgHNQVpZQkFaW0A7bisrLCwpK3A9f6yuBVxk" +
  "SEhiY0dIZKIzLzB4REN5LTAzv42NwQACAMMAAAVGBQQACwAPAAABESEVIREjESE1IREBIRUhA28B1v4q1v4qAdb+KgSC+34FBP6e" +
  "7P6eAWLsAWL76u4AAQBiApwCwAXwABgAAAEhFSE1AT4BNTQmIyIGBzU+ATMyFhUUBgcBcwFN/aIBGjcvQjU4gEtOkkSOokBbA0So" +
  "mQEKNVAoMj4tL7obG4FvSHlWAAEAUQKNAsQF8AAoAAABHgEVFAYjIiYnNR4BMzI2NTQmKwE1MzI2NTQmIyIGBzU+ATMyFhUUBgIV" +
  "U1uytUmFPTt0NlVeYWZDTFhRRkgvbz87iE6WoFEEYBJuUYGBFxauJCVAO0A9iS8zLS0aG6YREnBpRWAAAQFIBO4DRQZmAAMAAAEh" +
  "ASMCRgD//rSxBmb+iAAAAQCc/lQFEgRgACAAABMRIREUFjMyNjURIREUFjMyNjcVDgEjIiYnDgEjIiYnEZ0BRVpbXVoBRB4jEB4R" +
  "MFQoUGYfK3lQQ14a/lQGDP11dHFxdAKL/RNHOAoM+hcWS1NPTy8w/hIAAQB0/zsD9AXVAA0AAAEhESMRIxEjES4BNTQ2AiAB1Kur" +
  "qrjI6gXV+WYGB/n5A04Z27K+6AAAAQC8AgYCAQOJAAMAABMhESG8AUT+vAOJ/n0AAAEA6/5vAoQAAAATAAAhHgEVFAYjIiYvAR4B" +
  "MzI2NTQmJwIeNDJvcytbLwEtSx00OycoPmovX1sNDZgQDy4oGlI8AAEAbgKcAsAF3wAKAAATMxEHNTczETMVIX+6ys7LuP2/AzkC" +
  "CTSgMf1anQAAAwBpAXUDpwXwAAsADwAbAAABMhYVFAYjIiY1NDYDIRUhASIGFRQWMzI2NTQmAgjA3t3BwN/fswLl/RsBc0tSUktL" +
  "UlIF8N6+vtzcvr7e/E3IA9F+dHR8fHR0fgACAK0AiQQZBCcABgANAAAJARUBNS0CARUBNS0BAl0Bu/5FAQf++f5RAbr+RgEG/voE" +
  "J/6Nuv6P8t3d8v6Nuv6P8t3d//8AWv/jBuQF8BAnAM0EB/1kECcAzAM6AAAQBgB56wD//wBa/+MHGwXwECcAzAM6AAAQJwByBFv9" +
  "ZBAGAHnrAP//AF3/4wbkBfAQJwDNBAf9ZBAnAMwDOgAAEAYAcw0AAAIAfv5uA7YEYAAdACEAAAEhFRQGDwEOARUUFjMyNjcRDgEj" +
  "IiY1NDY/AT4BNSUhESEBtgFFOmI6Mi9WTkirW2y2U9zmRlU5PSYBRf67AUUCZjFRfmQ6M1wvRlBEQv7GKijHvmObWDo9TC3DAWT/" +
  "/wAJAAAFigdrEiYAIgAAEAcA0wSAAXX//wAJAAAFigdrEiYAIgAAEAcA0QSAAXX//wAJAAAFigdrEiYAIgAAEAcA1ASWAXX//wAJ" +
  "AAAFigdzEiYAIgAAEAcA0gSWAXv//wAJAAAFigdrEiYAIgAAEAcA0ASQAXUAAwAJAAAFigdtABIAHgAhAAAJASEDIQMhAS4BNTQ2" +
  "MzIWFRQGJRQWMzI2NTQmIyIGAyEDA6EB6f6jVP3iVv6kAekVFJdqaJcT/p5FMTBGRy8xRUMBcLcFuPpIARD+8AW4IksrdaiodS9M" +
  "ezZNTTY2TU37nwJSAAIAAAAAB0oF1QADABMAAAEDIREBIREhESERIREhESERIQMhAyLmAVP+owUD/bQCKf3XAmH8Rf5DhP6yBNX9" +
  "ngJiAQD+3f7q/t3+qv7dAV7+ov//AFv+bwTTBfASJgAkAAAQBwB4AU4AAP//AKkAAARlB2sSJgAmAAAQBwDTBDwBdf//AKkAAARl" +
  "B2sSJgAmAAAQBwDRBDwBdf//AKkAAARlB2sSJgAmAAAQBwDUBDwBdf//AKkAAARlB2sSJgAmAAAQBwDQBDwBdf//ABMAAAIEB2sS" +
  "JgAqAAAQBwDTAw0Bdf//AKkAAAJtB2sSJgAqAAAQBwDRAw0Bdf//AAIAAAKqB2sSJgAqAAAQBwDUAyMBdf//ADoAAAJyB2sSJgAq" +
  "AAAQBwDQAyMBdQACAB0AAAWrBdUADAAfAAABETMRIxEzMjY1NCYjASEgBBcWEhUUAgcGBCkBESMRMwIV09N71OHg1f4qAW0BMwEq" +
  "bF5dXV5s/tH+0v6TnJwEsv6//vz+turf3ugBI2F0Zf74p6n+92V0YQJtAQQA//8AqQAABV4HbRImAC8AABAHANIEsAF1//8AW//j" +
  "BcMHaxImADAAABAHANMExgF1//8AW//jBcMHaxImADAAABAHANEExgF1//8AW//jBcMHaxImADAAABAHANQExgF1//8AW//jBcMH" +
  "bRImADAAABAHANIE3QF1//8AW//jBcMHaxImADAAABAHANAE3AF1AAEA5gApBSIE2wALAAAJAgcJAScJATcJAQUi/nkBh5f+ef56" +
  "mAGH/nmYAYYBhwQz/k7+UKgBsP5QqAGwAbKo/k4BsgAAAwAo/7YF7gYfAAkAEwArAAABHgEzMhI1NCYvAS4BIyICFRQWFwMuATUQ" +
  "ACEyFhc3FwceARUQACEiJicHJwIgLnZLn68ODkUudUqerw0M+kNCAXABQ4vfXLNltUZE/pH+vIrlXLZmAXM+OwEE60R1MZM6Of78" +
  "7EBxLv7qZPqXAWsBnEtNx3PHY/+a/pb+ZE9Py3EA//8Aqf/jBTAHaxImADYAABAHANMEowF1//8Aqf/jBTAHaxImADYAABAHANEE" +
  "owF1//8Aqf/jBTAHaxImADYAABAHANQEugF1//8Aqf/jBTAHaxImADYAABAHANAEugF1////7gAABUkHaxImADoAABAHANEEUgF1" +
  "AAIAqQAABPwF1QAMABUAAAERIREhETMgBBUUBCEDETMyNjU0JiMCBP6lAVvkAQEBEv7u/v/kv2VubmUBAv7+BdX+/P3r6v0Cuv5d" +
  "bWNlbgAAAQCa/+ME3gYUADAAABM0NjMyFh0BDgEVFBYfAR4BFRQGIyImJzUeATMyNjU0Ji8BLgE1NDY3LgEjIgYVESGb8/br8YeC" +
  "LFQ+aGHO0Dt8QzNnMUFPMlg/T0x9gwFWUltc/r4EWt7c4NpHCk5KJTk0JUCpdb28GRj0GxxIOS9ENycxh1p0njJVWW5t+7QA//8A" +
  "T//jBEsGZhImAEIAABAHAEEApwAA//8AT//jBEsGZhImAEIAABAHAHQApwAA//8AT//jBEsGZhImAEIAABAHAMEApwAA//8AT//j" +
  "BEsGORImAEIAABAHAMMApwAA//8AT//jBEsGMRImAEIAABAHAGgApwAA//8AT//jBEsHGxImAEIAABAHAMIApwAAAAMAT//jBzQE" +
  "ewAGABEAPgAAATQmIyIGBwUiBhUUFjMyNj0BAT4BMzIWFz4BMzIAERUhHgEzMjY3EQ4BIyImJw4BIyImNTQ2ITM1NCYjIgYHBedr" +
  "Vl1zD/4YZWZSSVt8/aFryVeIw0BFuG3vAR39Dg2Lf2bVcXPlcqHuQVvJfa7M9AEFvnl/aLJNAqpmfXVuskxKRE2RbSkCShwdTU9N" +
  "T/7C/vZmfn5DRP7sMDFrZGtkxajFuBxVTy4u//8AT/5vA8oEexImAEQAABAHAHgApgAA//8AT//jBIkGZhImAEYAABAHAEEAwwAA" +
  "//8AT//jBIkGZhImAEYAABAHAHQAwwAA//8AT//jBIkGZhImAEYAABAHAMEAwwAA//8AT//jBIkGMRImAEYAABAHAGgAwwAA////" +
  "2QAAAd0GZhImAMAAABAGAEGFAP//AJoAAALKBmYSJgDAAAAQBgB0hQD////nAAACjwZmEiYAwAAAEAcAwf9uAAD//wAfAAACVwYx" +
  "EiYAwAAAEAcAaP9uAAAAAgBP/+MEpAYUAA4AKAAAAS4BIyIGFRQWMzI2NTQmExYSFRAAISAAETQAMzIWFycFJyUnIRclFwUDPDJh" +
  "L2lydWZqbwuSal/+3P77/vz+2QEP7ilGIav+sCEBFKkBPWQBUh/+5QLnGxuFeZSoq6EtXAGUiP7/lP7s/sgBOAEU5wEJDQ7bd4Fh" +
  "ynRygWAA//8AmgAABJEGORImAE8AABAHAMMA2gAA//8AT//jBKQGZhImAFAAABAHAEEAwgAA//8AT//jBKQGZhImAFAAABAHAHQA" +
  "wgAA//8AT//jBKQGZhImAFAAABAHAMEArAAA//8AT//jBKQGORImAFAAABAHAMMAqwAA//8AT//jBKQGMRImAFAAABAHAGgAqwAA" +
  "AAMAwwBWBUYErgADAAcACwAAASERIREhESEFIRUhAnoBFf7rARX+6/5JBIL7fgGL/ssEWP7LgewAAwBG/6IEpQTBAAkAEwArAAAB" +
  "LgEjIgYVFBYfAR4BMzI2NTQmJwEuATUQACEyFhc3FwceARUQACEiJicHJwMCGkMra3AGB0AcRytqbwYG/YI9PQEnAQRgoUOFYn8/" +
  "Pv7c/vtho0aFZQNEHBuroSlBG4seHquhK0Md/eROyHsBFAE4LCyeZZVQyn7+7P7ILS2bXv//AJD/4wSGBmYSJgBWAAAQBwBBANoA" +
  "AP//AJD/4wSGBmYSJgBWAAAQBwB0ANoAAP//AJD/4wSGBmYSJgBWAAAQBwDBAL8AAP//AJD/4wSGBjESJgBWAAAQBwBoAL8AAP//" +
  "ABb+RgSRBmYSJgBaAAAQBwB0AIwAAAACAJr+VgTVBhQAEAAcAAAlESERIRE+ATMyEhEQAiMiJhMiBhUUFjMyNjU0JgHd/r4BQkOi" +
  "abrw8LppopNnb29naG1tov20B779qGJd/rf+/f79/rddAzepn5+pqKCgqP//ABb+RgSRBjESJgBaAAAQBwBoAIwAAAABAJoAAAHd" +
  "BGAAAwAAEyERIZsBQv6+BGD7oAAAAQB5BO4DIQZmAAYAAAEzEyMnByMBYNrmoLOzoAZm/ojh4QAAAgDMBOECzgcbAAsAFwAAARQW" +
  "MzI2NTQmIyIGBzQ2MzIWFRQGIyImAVdFMTFFRjAyRIuXamqWlmpqlwX+N0xNNjZNTTZ2p6d2dqenAAEAkwUbAwYGOQAeAAABJyYn" +
  "JiMiBh0BIzQ2MzIWHwEeATMyNj0BMxQGIyImAc8yAwYqFyAifVxUIEIlNxQhDSEkfV1TITwFVCUCBB8+OwiIlBseKw8QQDkIiJQY" +
  "AAABAGMBsAM3ArIAAwAAEyERIWMC1P0sArL+/gAAAQBjAbAG0QKyAAMAABMhESFjBm35kwKy/v4AAAEAvQNYAkoF1QAFAAABIRET" +
  "MwMB8P7OzMBaA1gBHQFg/qAAAAEAdANYAgEF1QAFAAATIREDIxPOATLMwFoF1f7j/qABYAACAL0DWAQSBdUABQALAAABIRETMwMB" +
  "IRETMwMDt/7Ozb9a/jn+zszAWgNYARsBYv6e/uUBHQFg/qAAAgCpA1gD/gXVAAUACwAAASERAyMTASERAyMTAQQBMs3AWwHIATLO" +
  "v1sF1f7j/qABYAEd/uH+ogFeAAEBCQGRA5EEYAAXAAABNDY3PgEzMhYXHgEVFAYHDgEjIiYnLgEBCi8uMHVCQXYtLzAxLi52QkJ1" +
  "Li0wAvpKgjIzNTYyNIFJSoMzMzY2MzODAAADAJEAAAaiAYMAAwAHAAsAAAEhESEBIREhASERIQVdAUT+vPs1AUT+vAJmAUT+vAGD" +
  "/n0Bg/59AYP+fQAB/pD/4wKjBfAAAwAAByMBM6bJA0jKHQYNAAIAMgKcAt0F3wACAA0AAAEDMwMzETMVIxUjNSE1AZLX1xDffHzP" +
  "/qAFHP69Agb9+puioqgAAAEANv/kBM4F8AAsAAABNjc2NxEOASMgABEQACEyFhcRLgEjIgIVFBcWFxEhFT4BMzIWFxMuASMiBhUD" +
  "YywpWFtaw2n+w/6OAXIBPWnDWluwYa/IYy05ARI1iGAOIB4BJUYlaXEBAwkQIkn+yzc3AaABZQFmAaE4N/7LSUT++OjnhDogAsym" +
  "Y1sCBf7dExOflQAAAgBb/1sEoQZ4ACQALQAAASM1IREGBwYHFSM1JicmERA3Njc1MxUWFxYXFSYnJicRNjc2NwEGBwYREBcWFwPN" +
  "cQFEbnZbX53ZiaepiNidWlVoXV5OZGQhJks5/phZPGlmPVsCVND9S0YjGwaKjx6s0AFlAWnPpSKQiQQXHDf4PxwmAfu+AQYNNgPe" +
  "I1CO/vn++45VIgAAAv0XBQD/TwX2AAMABwAAATMVIyUzFSP9GNPTAWPU1AX29vb2AAAB/a4E7v9gBfYAAwAAASEBI/5hAP/+/7AF" +
  "9v74AAAB/PoE7v9tBfgAIwAAAScmJyYjIgYdASM0NjU0NjMyFh8BHgEzMjY1MxQGFRQGIyIm/jUyAwYpGR0kfQJgTiJCIzUTIw8h" +
  "I30BYU4iPwUfIwIEGjwyBgUUBWqCGRgnDg88OQYUBWqBFgAAAf0GBO7+uAX2AAMAAAETIwH+BbOx/wAF9v74AQgAAfzfBO7/hwX2" +
  "AAYAAAEhEyMnByP9qQEVyKCzs6AF9v74oaEAAAABAAAA1QNOACsAeAAMAAEAAAAAAAAAAAAAAAAACAAEAAAAFQAVAC4AQgB7AMwB" +
  "GQFoAXYBkwGwAdYB7wIAAg4CHAIqAloCcwKeAtsC+gMrA2kDfQPFBAIEFwQvBEQEVwRrBKIFFwU1BWwFmgXHBeEF+AYsBkYGVAZt" +
  "BokGmga5BtIHAgcnB1wHjQfLB98IAggXCDYIVwhvCIcImQioCLoI0AjdCOwJJglWCYMJswnmCgcKRwpwCoUKogq+CswLBgsuC1wL" +
  "jAu8C9wMGAw7DGUMeQyYDLcM1wzvDSENLw1hDZENkQ2rDegOFA5eDo0Oog7/DxEPfg+8D9wP7A/6EG8QfBCrEMsQ9BEuET0RcBGL" +
  "EZkRuhHQEf4SIBIwEkASUBKHEpMSnxKrErcSwxL+EycTMxM/E0sTVxNjE28TexOHE5MTyhPWE+IT7hP6FAYUEhQ0FH4UihSWFKIU" +
  "rhS6FOIVKRU1FUEVTRVZFWUVcRXOFdoV5hXyFf4WChYVFiAWLBY4Fn8WixaXFqMWrxa7FscW4xcsFzgXRBdQF1wXaBeYF6QXshfE" +
  "F+oYGRgnGDUYRxhYGHUYkhi7GNkY5hkBGUoZlRmoGbcZ7Bn7Gg0AAQAAAAJeuAm5D9tfDzz1AB8IAAAAAADTwiv7AAAAANPCK/v4" +
  "TfyuDjkJZQABAAgAAAAAAAAAAARSAFsCgQAAA0gBAgPAAK8GCAB9BQIAkAc2ADsGRwBuAjQArwNKAJ4DSgCTA8MAJAYIAMMCvABi" +
  "Av0AYwK8ALwCoQAABQIAWAUCAM8FAgCRBQIAewUCAFIFAgCOBQIAcgUCAHsFAgBwBQIAXwLhAM4C4QB0BggAwwYIAMMGCADDBC0A" +
  "fgczAHkFkgAJBXwAqQVIAFsF+gCpBOsAqQTrAKkF6ABbBgYAqQKtAKkCrf+ZBZQAqQSWAKkHKgCpBgYAqQYeAFsFRgCpBh4AWwWL" +
  "AKkFLwCEBOkACQXYAKkFkgAJB/EANgWNACMFNv/uBTgAUgNKAJ4CoQAAA0oAfQYIALoDmQAAA5kAVATbAE8FJwCaBEQATwUnAFIE" +
  "4gBPAyEAIwUnAFIFIACaAncAmgJ3/8MEyQCaAncAmgeAAJkFIACaBPIATwUnAJoFJwBSA40AmgRJAF8DcQAYBSAAkASxABsGpgBA" +
  "BKQAGwSxABYEMABSBSAA5gKhAOoFIADmBggAwwKBAAADSAECBQIAnAUCAHAElABCBQIAFgKhAOoDmQAMA5kAsQczAP4EDwCOBKYA" +
  "jgYIAMMC/QBjBzMA/gOZALEDmQCgBggAwwMnAGIDJwBRA5kBSAVMAJwElAB0ArwAvAOZAOsDJwBuBA8AaQSmAK0HdABaB3QAWgd0" +
  "AF0ELQB+BZIACQWSAAkFkgAJBZIACQWSAAkFkgAJB88AAAVIAFsE6wCpBOsAqQTrAKkE6wCpAq0AEwKtAKkCrQACAq0AOgYIAB0G" +
  "BgCpBh4AWwYeAFsGHgBbBh4AWwYeAFsGCADmBh4AKAXYAKkF2ACpBdgAqQXYAKkFNv/uBU8AqQUtAJoE2wBPBNsATwTbAE8E2wBP" +
  "BNsATwTbAE8HiwBPBEQATwTiAE8E4gBPBOIATwTiAE8Cd//aAncAmgJ3/+gCdwAfBPIATwUgAJoE8gBPBPIATwTyAE8E8gBPBPIA" +
  "TwYIAMME8gBGBSAAkAUgAJAFIACQBSAAkASxABYFJwCaBLEAFgJ3AJoDmQB5A5kAzAOZAJMDmQBjBzMAYwK8AL0CvAB0BLsAvQS7" +
  "AKkEmgEJBzMAkQEz/pEDJwAyBQIANgUCAFsAAP0Y/a/8+v0H/OAAAQAAB23+HQAADoT4TfnhDjkAAQAAAAAAAAAAAAAAAAAAANEA" +
  "AQQfArwABAAABTMFmQAAAR4FMwWZAAAD1wBmAhIAAAILCAYDBgQCAgSAAAADAAAAAgAAAAAAAAAAUGZFZAAgACAgsgYU/hQBmgdt" +
  "AeMAAAABAAAAAAAAAAAAAwAAAAMAAAAcAAAACgAAAHwAAwABAAAAHAAEAGAAAAAUABAAAwAEAH4A/yAUIBkgHSAiICYgoiCy//8A" +
  "AAAgAKAgEyAYIBwgIiAmIKIgsv///+H/wOCx4K7grOCo4KXgLOAdAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAB8AAAAAAAA" +
  "AAkAAAAgAAAAfgAAAAEAAACgAAAA/wAAAGAAACATAAAgFAAAAMQAACAYAAAgGQAAAMYAACAcAAAgHQAAAMgAACAiAAAgIgAAAMoA" +
  "ACAmAAAgJgAAAMsAACCiAAAgogAAAM4AACCyAAAgsgAAAM8AAAAFAEIAAwABBAkAAQAqAAAAAwABBAkAAgAIACoAAwABBAkAAwA0" +
  "ADIAAwABBAkABAA0ADIAAwABBAkABgAwAGYARABlAGoAYQBWAHUAIABTAGEAbgBzACAAQwBvAG4AZABlAG4AcwBlAGQAQgBvAGwA" +
  "ZABEAGUAagBhAFYAdQAgAFMAYQBuAHMAIABDAG8AbgBkAGUAbgBzAGUAZAAgAEIAbwBsAGQARABlAGoAYQBWAHUAUwBhAG4AcwBD" +
  "AG8AbgBkAGUAbgBzAGUAZAAtAEIAbwBsAGQAAwAAAAAAAP9+AFoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIACAAC//8AAw==";
