/**
 * DejaVu Sans Condensed (peso REGULAR), recortada a los caracteres que usa el
 * ticket, en base64 para que jsPDF la pueda embeber en el PDF.
 *
 * Por qué el peso regular y no la negrita: ver `ticketFuente.ts`.
 *
 * ARCHIVO GENERADO — no editar a mano. Para regenerarlo, desde la raíz del
 * repo (necesita `pip install fonttools`):
 *
 *   python -m fontTools.subset  *     backups/dejavu-sans/DejaVuSansCondensed.ttf  *     --unicodes="U+0020-007E,U+00A0-00FF,U+2013,U+2014,U+2018,U+2019, *                 U+201C,U+201D,U+2022,U+20A2,U+20B2,U+2026"  *     --layout-features="" --no-hinting --desubroutinize  *     --drop-tables+=DSIG,GSUB,GPOS,GDEF --name-IDs="1,2,3,4,6"  *     --notdef-outline  *     --output-file=client/src/assets/fonts/DejaVuSansCondensed.subset.ttf
 *
 * y después volver a codificar el .ttf en base64 acá.
 *
 * El subset deja los 99 caracteres que el ticket puede imprimir (ASCII + Latin-1
 * con acentos y ñ + guiones y comillas tipográficas + el símbolo de guaraní) y
 * baja la fuente de 664 KB a 16 KB. Se verificó que los anchos de esos 99
 * caracteres son idénticos a los de la fuente completa.
 *
 * La tabla `name` NO se puede quitar: el parser de TTF de jsPDF la necesita y
 * revienta sin ella.
 *
 * Licencia: Bitstream Vera Fonts Copyright (c) 2003 Bitstream, Inc., y los
 * cambios de DejaVu están en dominio público. Permite redistribuir. El texto
 * completo está en backups/dejavu-sans/DejaVu Fonts License.txt.
 */
export const DEJAVU_SANS_CONDENSED_REGULAR_BASE64 =
  "AAEAAAAMAIAAAwBATUFUSIdy00cAAD6sAAACsk9TLzJp/g9XAAA8lAAAAFZjbWFwZTBR8QAAPOwAAAD4Z2FzcAAHAAcAAD6gAAAA" +
  "DGdseWY4q2rcAAAAzAAANeBoZWFkDGgBzwAAOKAAAAA2aGhlYQ0BB2MAADxwAAAAJGhtdHjPdXBzAAA42AAAA5hsb2NhynC9eAAA" +
  "NswAAAHSbWF4cAEoA8EAADasAAAAIG5hbWUI2B1hAAA95AAAAJpwb3N0/4EAWgAAPoAAAAAgAAIAW/6WA/YFpAADAAcAABMRIREl" +
  "IREhXAOZ/M4CzP00/pYHDvjycgYpAAIBFgAAAc0F1QADAAkAACUzFSMRMxEDIwMBFre3txKSE/7+BdX9cf6bAWUAAgCxA6oCnwXV" +
  "AAMABwAAAREjESERIxEBSpkB7ZgF1f3VAiv91QIrAAIAjgAABXwFvgADAB8AAAEhAyELASETMwMhFSEDIRUhAyMTIQMjEyE1IRMh" +
  "NSETA67++ksBBz1dAQZfkF0BGf7ESgEf/r5dkFz++V2RXv7kAT1M/t4BRVwDhf6yA4f+YQGf/mGa/rKZ/mIBnv5iAZ6ZAU6aAZ8A" +
  "AAMAmf7TA/wGFAAhACgALwAAASMDLgEnNR4BFxEuATU0Njc1MxUeARcVLgEnER4BFRQGBwMRDgEVFBYXET4BNTQmAm9aAV+9X1y8" +
  "ZMe1xLhaU51LS51TzMHNwFppbWXLcnRv/tMBLQItLbRAQQEByCSslqO8DuvoBB8bryouBP5VI7ScqcMPAwABmg1qWFZg1f5PEW5a" +
  "WGgABQBl/+MGcgXwAAsAFwAjACcAMwAAASIGFRQWMzI2NTQmJzIWFRQGIyImNTQ2ASIGFRQWMzI2NTQmJTMBIxMyFhUUBiMiJjU0" +
  "NgU8TllZTk1ZWU2OqKmNkKeo/O5NWVhOT1laAt+Q/LeQHI+pqY+PpqcCkZSEgpWVgoOVf9y7u9vbu7zbAmGVgoSUlISBln/58wYN" +
  "27u92tu8utwAAgB0/+MFZQXwAAkAMAAAAQ4BFRQWMzI2NwkBPgE3MwYCBxMjJw4BIyIANTQ2Ny4BNTQ2MzIWFxUuASMiBhUUFgHA" +
  "Uky/kFWWQf6iAck1PAWoC15T++OBXc522P7seXgrLcilS5VMTo4+XnY1AyNRoViSwj9AAo/9+FnLcoT+/n7+45NZVwET14DhYz99" +
  "PKLFJCS2LzFvWDNnAAEAsQOqAUsF1QADAAABESMRAUqZBdX91QIrAAABAJ7+8gI8BhIADQAAAQYCFRQSFyMmAjU0EjcCPHl1dniQ" +
  "iIaGiAYS5v4+5+f+O+XrAcbg3wHE7AAAAQCT/vICMQYSAA0AABMzFhIVFAIHIzYSNTQClJCHhoaHkHd2dgYS7P483+D+OuvlAcXn" +
  "5wHCAAABADYCSgNjBfAAEQAAAQ0BByURIxEFJy0BNwURMxElA2P+vQFDNf7SZv7RNAFD/r00AS9mAS4E38LDYsv+hwF5y2LDwmPL" +
  "AXn+h8sAAQDDAAAFRgUEAAsAAAERIRUhESMRITUhEQNQAfX+C5f+CgH2BQT906r90wItqgItAAABAI7/EgGWAP4ABQAANzMVAyMT" +
  "2L6UdEr+rP7AAUAAAAEAWgHfAkACgwADAAATIRUhWgHl/hsCg6QAAQDFAAABgwD+AAMAADczFSPFvr7+/gAAAQAA/0ICbQXVAAMA" +
  "AAEzASMB1Jn+LJkF1fltAAIAef/jBBsF8AALABcAAAEiAhEQEjMyEhEQAicyEhEQAiMiAhEQEgJKjI6OjI2NjY3i7u7i4u7uBVD+" +
  "zf7M/s3+zQEzATMBNAEzoP5z/ob+h/5zAY0BeQF6AY0AAQDKAAAD6wXVAAoAADchEQU1JTMRIRUh5QEp/rwBQrYBKfz6qgRzSLhI" +
  "+tWqAAEAhwAAA90F8AAcAAAlIRUhNTYANz4BNTQmIyIGBzU+ATMyFhUUBgcGAgFiAnr8q2cBZi5XRZZ5Vb5sbr9P0fg+Uhfxqqqq" +
  "dwGROm2XSXeWQkPMMTLowlylcB3+6wABAIz/4wQCBfAAKAAAAR4BFRQEIyImJzUeATMyNjU0JisBNTMyNjU0JiMiBgc1PgEzMhYV" +
  "FAYC7IKT/u/8VbNgTLRiq7OmlZyjho+TiUuqZ2e1UM/ygAMlH8SQ3fIlJcMxMpaPhJWmd3BzeyQmtCAg0bJ8qwAAAgBaAAAELgXV" +
  "AAIADQAACQEhAzMRMxUjESMRITUCuf41Acsw5b+/tf2hBSX84wPN/DOo/qABYMMAAAEAjv/jA/QF1QAdAAATIRUhET4BMzIAFRQA" +
  "IyImJzUeATMyNjU0JiMiBgfHAsr93ChPKOEBB/7y9lWvXlGtYJy2tpxJkUsF1ar+kg8P/u7q8f71ICDLMTC2nJy2JCYAAAIAgP/j" +
  "BCEF8AALACQAAAEiBhUUFjMyNjU0JhMVLgEjIgIDPgEzMhIVFAIjIgIREAAhMhYCYHqPj3p7j4/uRIxEtL4NNaBgy+v1zOn2AS4A" +
  "/0SMAzu6oqG7u6GiugJ5uCQm/vL+71dd/u/r5v7qAY0BeQFiAaUeAAEAlwAAA/gF1QAGAAATIRUBIwEhlwNg/hi9Acr9ewXVVvqB" +
  "BSsAAwB9/+MEFwXwAAsAIwAvAAABIgYVFBYzMjY1NCYlLgE1NDYzMhYVFAYHHgEVFAYjIiY1NDYTFBYzMjY1NCYjIgYCSoKUlIKC" +
  "lZX+yHWC5cjJ5IJ0g5Pv3t7vlEGCdnWEhHV2ggLFmoeHmpuGh5pWILKAs9DQs4CyICLGj9no6NmPxgFhdIKCdHSCggACAHT/4wQU" +
  "BfAAGAAkAAA3NR4BMzISEw4BIyICNTQSMzISERAAIyImATI2NTQmIyIGFRQWykWMRLS+DTSgYcrr9cvp9v7T/0WMAR57j497eo+P" +
  "H7gkJgENARJWXAEP6+YBFv5z/ob+n/5bHgKXuqKhu7uhoroAAgDYAAABlgQjAAMABwAANzMVIxEzFSPYvr6+vv7+BCP+AAIAjv8S" +
  "AZYEIwADAAkAABMzFSMRMxUDIxPYvr6+lHRKBCP+/dms/sABQAAAAQDDAF4FRgSmAAYAAAkCFQE1AQVF/F8Doft+BIID8P6R/pO2" +
  "AdGmAdEAAgDDAWAFRgOiAAMABwAAEyEVIRUhFSHDBIL7fgSC+34DoqjwqgABAMMAXgVGBKYABgAAEzUBFQE1AcMEgvt+A58D8Lb+" +
  "L6b+L7YBbQAAAgCEAAADUgXwAAMAJAAAJTMVIxMjNTQ2PwE+ATU0JiMiBgc1PgEzMhYVFAYPAQ4BBw4BFQFgt7exrDNRUTMudmFH" +
  "oVhVrlymyUFRTysjBwUG/v4BkZplglZZNV4xWW5GQ7w5OMKfTIlWVi81GRU8NAAAAgB5/pwGswWiAAsATAAAARQWMzI2NTQmIyIG" +
  "AQ4BIyImNTQ2MzIWFzUzET4BNTQmJyYkIyIGBwYCFRQSFx4BMzI2NxcGBCMiJCcmAjU0Ejc2JDMyBBceARUQAAcCroBvb3+Cbm2A" +
  "Aeo2i12bwcKaXYw1gYOVOTle/vOeb8xWjaBoYl75jXTgXlFx/veJpv7Yc3N4enF0ATGqvgFHb0NH/uL8AhmPo6SOjKWk/khNSfnI" +
  "yPpLTIP9IBbfsWu8UIOLQUBm/rXBn/7qamhtV1FvYWeDfX0BSb22AUp9f4euoGLme/75/tAGAAIADgAABN4F1QACAAoAAAEDIQEz" +
  "ASMDIQMjAnb3Ae/+oc8CAL17/aJ6wAUO/RkDrvorAX/+gQAAAwC0AAAEbgXVAAgAEQAgAAABESEyNjU0JiMBESEyNjU0JiMlITIW" +
  "FRQGBx4BFRQGIyEBawEjk42Nk/7dAQ2Fg4OF/j0B0NDhc3CHlPXi/h4Cyf3dh4uMhQJm/j5vcnFwpsCxiaIUIMuYyNoAAQBn/+ME" +
  "pAXwABkAAAEVLgEjIgIREBIzMjY3FQ4BIyAAERAAITIWBKNc0HXm9fXmddBcX9Z2/s7+ogFeATJ41gVi1V9e/sf+2P7Z/sdeX9NI" +
  "SAGfAWcBaAGfRwACALQAAAUfBdUACAARAAABETMgABEQACElISAAERAAKQEBa9sBFgED/v3+6v5vAXUBhwFt/pH+e/6LBS/7dwEY" +
  "AS4BLAEXpv6X/oD+fv6WAAEAtAAABBcF1QALAAATIRUhESEVIREhFSG1A1H9ZQKA/YACrPyeBdWq/kaq/eOqAAEAtAAAA7oF1QAJ" +
  "AAATIRUhESEVIREjtQME/bICFf3rtgXVqv5Iqv03AAEAZ//jBP4F8AAdAAAlESE1IREOASMgABEQACEyFhcVLgEjIgIREBIzMjYE" +
  "Sf7XAd1p/pD+xf6dAWMBO4PtZGXjffb4+PZhl9UBkab9f1NVAZkBbQFuAZlIRtdfYP7O/tH+0v7OJQAAAQC0AAAEtgXVAAsAABMz" +
  "ESERMxEjESERI7W2ApS2tv1stgXV/ZwCZPorAsf9OQAAAQC0AAABawXVAAMAABMzESO1trYF1forAAAB/6D+ZgFrBdUACwAAEzMR" +
  "EAYrATUzMjY1tba5zEU4eWMF1fqT/vL0qpbCAAEAtAAABOAF1QAKAAATMxEBMwkBIwERI7W2Alvq/WUCyu/9e7YF1f2JAnf9SPzj" +
  "As/9MQABALQAAAP5BdUABQAAEzMRIRUhtbYCjvy8BdX61aoAAAEAtAAABYMF1QAMAAATIQkBIREjEQEjAREjtQEPAVcBWAEPsf6l" +
  "tv6lsAXV/AgD+PorBR/8AAQA+uEAAAEAtAAABK4F1QAJAAATMwERMxEjAREjtfUCVLD1/aywBdX7HwTh+isE4fsfAAACAGf/4wVE" +
  "BfAACwAXAAABIgIREBIzMhIREAInIAAREAAhIAAREAAC1sbp6cbG6OjGARsBUv6u/uX+5f6tAVMFTP64/uX+5v64AUgBGgEbAUik" +
  "/lv+nv6f/lsBpAFiAWIBpQAAAgC0AAAEGQXVAAgAEwAAAREzMjY1NCYjJSEyFhUUBisBESMBa+R/i4t//mYBmuLn5+LktgUv/c+S" +
  "h4aSpuPb3eL9qAACAGf++AVEBfAACwAdAAABIgIREBIzMhIREAIbASMnDgEjIAAREAAhIAAREAIC1sbp6cbG6Og579vHHh8P/uX+" +
  "rQFTARsBGwFSvAVM/rj+5f7m/rgBSAEaARsBSPrP/t3vAgIBpQFhAWIBpf5b/p7+/P6OAAIAtAAABMwF1QATABwAAAEeARcTIwMu" +
  "ASsBESMRITIWFRQGAREzMjY1NCYjAzI7bji5xKxCfWzGtgGa5+J1/cjkhIaGhAK8FpB+/mgBf5Zi/YkF1dbYjboCT/3uh4ODhQAA" +
  "AQB5/+MELAXwACcAAAEVLgEjIgYVFBYfAR4BFRQEIyImJzUeATMyNjU0Ji8BLgE1NDYzMhYD2me4VZWha5ZtzMH++/1g13Nv1Geb" +
  "qnqLbsy1+9xfxAWkxTc2gHZjZR8ZK9m22eAwL9BFRoh+bnwfGC3Aq8bkJgAAAf/6AAAEbAXVAAcAAAMhFSERIxEhBQRw/iO2/iMF" +
  "1ar61QUrAAABAKD/4wSlBdUAEQAAEzMRFBYzMjY1ETMREAAjIgARoLedr6+ct/78/v/+/AXV/HXw09PwA4v8XP7c/tYBKgEkAAAB" +
  "AA4AAATeBdUABgAAIQEzCQEzAQIP/f++AaoBq73+AAXV+xcE6forAAABAD0AAAbjBdUADAAAEzMJATMJATMBIwkBIz24ARoBGswB" +
  "GwEauP6v5f7l/uHkBdX7EgTu+xIE7vorBRD68AAAAQA2AAAEtgXVAAsAABMzCQEzCQEjCQEjAXTDAU4BUMP+UAHNw/6G/oPEAeAF" +
  "1f3VAiv9M/z4Anv9hQMdAAAB//wAAARqBdUACAAAAzMJATMBESMRBMQBdAFyxP4ktgXV/ZoCZvzy/TkCxwAAAQBSAAAEnAXVAAkA" +
  "ABMhFQEhFSE1ASFoBB/8rwNm+7cDUfzEBdWa+2+qmgSRAAEAnv7yAhwGFAAHAAATIRUjETMVIZ4BftjY/oIGFI/5/I8AAAEAAP9C" +
  "Am0F1QADAAATASMBmQHUmf4sBdX5bQaTAAEAs/7yAjEGFAAHAAABESE1MxEjNQIx/oLX1wYU+N6PBgSPAAEAwwOoBUYF1QAGAAAJ" +
  "ASMJASMBA1wB6bX+dP50tQHpBdX90wGL/nUCLQAAAf/u/h0DrP6sAAMAAAEVITUDrPxC/qyPjwABAJkE8AJJBmYAAwAAARMjAQFK" +
  "/or+2wZm/ooBdgACAG7/4wPDBHsACgAlAAABIgYVFBYzMjY9ATcRIzUOASMiJjU0NjsBNTQmIyIGBzU+ATMyFgJ4yZt0ZIqmpqY4" +
  "qXubtuPi6JaIVqRMW6tR29gCM2Z7YnPZtClM/YGqZmHBor3AEn+LLi6qJyf8AAIAp//jBC4GFAALABwAAAE0JiMiBhUUFjMyNgE+" +
  "ATMyEhEQAiMiJicVIxEzA4GWg4SWloSDlv3NNJ9vuOXluG+fNKenAi/L5+fLy+fnAlJkYf68/vj++P68YWSoBhQAAAEAZf/jA4QE" +
  "ewAZAAABFS4BIyIGFRQWMzI2NxUOASMiABEQADMyFgODRo1IorKyokiNRkWVU+T+9AEP602SBDWsKyvjzc3jKyuqJCQBPgEOARIB" +
  "OiMAAgBl/+MD6wYUABAAHAAAAREzESM1DgEjIgIREBIzMhYBFBYzMjY1NCYjIgYDRaamNJ9wt+Xlt3Cf/gCWg4SXl4SDlgO2Al75" +
  "7KhkYQFEAQgBCAFEYf4Vy+fny8vn5wAAAgBl/+MEDAR7ABQAGwAAARUhHgEzMjY3FQ4BIyIAERAAMzISBy4BIyIGBwQM/QYLuaRg" +
  "s1hZu2Dy/ucBC+PL7aYClHqLpwwCXlq+xzQ0riosATgBCgETAUP+3cSXtK6eAAABACoAAAKsBhQAEwAAARUjIgYdASEVIREjESM1" +
  "MzU0NjMCrJ5aRQER/u+mn5+cqgYUmVBoY4/8LwPRj067qwAAAgBl/lYD6wR7AAsAKAAAATQmIyIGFRQWMzI2FxACIyImJzUeATMy" +
  "Nj0BDgEjIgIREBIzMhYXNTMDRZWGhZSUhYaVpuXsV5tJSY5Ko6IzoHC64uK6cKAzpgI9yNzcyMfc3Ov+4v7pHR6zLCq9v1tjYgE6" +
  "AQMBBAE6YmOqAAEApwAAA/QGFAATAAABESMRNCYjIgYVESMRMxE+ATMyFgP0pnBvhpunpzuhaq2zAqT9XAKen56+pP2HBhT9nmVk" +
  "7wAAAgCtAAABVAYUAAMABwAAEzMRIxEzFSOupaWlpQRg+6AGFOkAAv/e/lYBVAYUAAsADwAAEzMRFAYrATUzMjY1ETMVI66lkqM/" +
  "LF5FpaUEYPuM1sCcYZkGKOkAAQCnAAAEJgYUAAoAABMzEQEzCQEjAREjp6cB7tT96QIt2P4ApwYU/GkB4/30/awCI/3dAAEArQAA" +
  "AVQGFAADAAATMxEjrqWlBhT57AAAAQCnAAAGZwR7ACIAAAE+ATMyFhURIxE0JiMiBhURIxE0JiMiBhURIxEzFT4BMzIWA74/rHWe" +
  "q6dmaoCWpmdrf5WnpzmebW6aA4l8dvXi/VwCnqGcvqT9hwKeopu/o/2HBGCuZ2J8AAABAKcAAAP0BHsAEwAAAREjETQmIyIGFREj" +
  "ETMVPgEzMhYD9KZwb4abp6c7oWqtswKk/VwCnp+evqT9hwRgrmVk7wACAGX/4wQDBHsACwAXAAABIgYVFBYzMjY1NCYnMhIREAIj" +
  "IgIREBICNIWbmoaFmpqF2Pf32Nn19QPf58nJ5+jIx+mc/sj+7P7t/scBOQETARQBOAACAKf+VgQuBHsAEAAcAAAlESMRMxU+ATMy" +
  "EhEQAiMiJgE0JiMiBhUUFjMyNgFOp6c0n2+45eW4b58B/5aDhJaWhIOWqP2uBgqqZGH+vP74/vj+vGEB68vn58vL5+cAAgBl/lYD" +
  "6wR7AAsAHAAAARQWMzI2NTQmIyIGAQ4BIyICERASMzIWFzUzESMBEZaDhJeXhIOWAjQ0n3C35eW3cJ80pqYCL8vn58vL5+f9rmRh" +
  "AUQBCAEIAURhZKr59gAAAQCnAAAC9gR7ABEAAAEuASMiBhURIxEzFT4BMzIWFwL2HEInjZanpzSodxEqGQO0EhHLvv2yBGCuZmMF" +
  "BQABAGP/4wNnBHsAJwAAARUuASMiBhUUFh8BHgEVFAYjIiYnNR4BMzI2NTQmLwEuATU0NjMyFgMwRpdRe3xZhTixlN7CUbBhXLJX" +
  "dX5bmjmaicq5XKIEP64oKFRUQEkhDiqZiZy2IyO+NTVZUUtQJQ8klYKerB4AAQAxAAACpwWeABMAAAERIRUhERQWOwEVIyImNREj" +
  "NTMRAVIBVf6rQ2erq7+SeXkFnv7Cj/2giU6an9ICYI8BPgAAAgCc/+MD6QR7ABMAFAAAExEzERQWMzI2NREzESM1DgEjIiYBnaVw" +
  "b4ebpqY8n2qttAGgAboCpv1hn5++pAJ7+6CsZmPwA6gAAQA2AAAEDARgAAYAABMzCQEzASM3rwE7ATuw/obhBGD8VAOs+6AAAAEA" +
  "TQAABZcEYAAMAAATMxsBMxsBMwEjCwEjTabPzsPPzqb++MPZ2sMEYPyWA2r8lgNq+6ADlvxqAAABADUAAAQHBGAACwAACQIjCQEj" +
  "CQEzCQED9P6TAX/D/tv+2sMBiP6ZxAELAQsEYP3f/cEBuP5IAkoCFv5xAY8AAQA2/lYEDARgAA8AAAUOASsBNTMyNj8BATMJATMC" +
  "UUaFcIRhREwuHv5orwE7ATuwaMh6mkiGVARO/JQDbAABAE8AAAN5BGAACQAAEyEVASEVITUBIWYDEv2SAm781wJv/agEYKj825Oo" +
  "AyUAAQDm/rIDrwYUACQAAAUVIyImPQE0JisBNTMyNj0BNDY7ARUjIgYdARQGBx4BHQEUFjMDrjjgmGGANzeBYJjgOD1/TVJjZFFN" +
  "f76QlN3vl3SPc5Xw3ZOPWI34nY4ZG46c+I1YAAEA6v4dAYMGHQADAAABESMRAYOZBh34AAgAAAABAOb+sgOvBhQAJAAAFzMyNj0B" +
  "NDY3LgE9ATQmKwE1MzIWHQEUFjsBFSMiBh0BFAYrAeY/fk1RZGRRTX4/OeCXYX84OH9hl+A5vlaP+JyOGxmOnfiOV4+T3fCVc490" +
  "l+/dlAAAAQDDAdMFRgMxAB0AAAEVDgEjIicmJyYnJiMiBgc1PgEzMhcWFxYXFjMyNgVFXqFYY4MKBQYNjFRQmllfoVdjhQgFBw2L" +
  "VU2YAzGyT0Q7BAIDBT5NU7JPRTwEAgMFPkwAAgEW/osBzQRgAAMACQAAASM1MxEjERMzEwHNt7e3E5ISA2L++isCjwFl/psAAAIA" +
  "mv7HA7oFmAAGACEAACURDgEVFBYBFS4BJwM+ATcVDgEHESMRJgIREBI3ETMTHgECYoSUlAHbQ3o9AT97QTp8RVzZ7u7ZXAFCe4MD" +
  "WBLiuLniA6GsKSoD/KAFKieqHiMH/uQBIBQBMwEBAQIBMhYBH/7hBCEAAAEAdAAAA/IF8AAbAAABFS4BIyIGHQEhFSERIRUhNTMR" +
  "IzUzNRA2MzIWA+BFejeFaQFg/qAB9vyC1LOzwdE3iAW0tikpm9TXj/4vqqoB0Y/uAQXzHwAAAgBUAFIEQwSyACMALwAAATcXBx4B" +
  "FRQGBxcHJw4BIyImJwcnNy4BNTQ2Nyc3Fz4BMzIWEzQmIyIGFRQWMzI2AyK6Z7oiICIkvGe6NWg3NGw3u2W6ISIiI7toujJoOjZp" +
  "U4xmZY6NZmWNA+HRc847dz4/cznPcc8oJiUlz3POPnY6QHQ4znPPJyUk/nxwmppwcpydAAEASQAABEoF1QAYAAABIREjESE1ITUn" +
  "ITUzATMJATMBMxUhBxUhBBj+jbX+igF2TP7W7f7jqwFVAVOs/uLt/tdMAXUBx/45Acd7M5t7Akr9RAK8/bZ7mzMAAAIA6v6iAYMF" +
  "mAADAAcAAAERIxETESMRAYOZmZkBmP0KAvYEAP0KAvYAAAIAUv89A0UF8AALAD4AAAEOARUUFhc+ATU0JhMVLgEjIgYVFBcWFx4B" +
  "FRQGBx4BFRQGIyImJzUeATMyNjU0LwEuATU0NjcuATU0NjMyFgFVOTd94Tg4gbhLgDNXYbkYDL52U1Q4NLicQYtPToU0XGbHFsFz" +
  "U1I1NbSWQYoDqC5aLkyFhy1bLkuIApOkJydQR1pzDwh3mmVajDU0bUCOqB0dpCcnVExmew54mWZbjzEscEWCnx0AAgDBBUYC2QYQ" +
  "AAMABwAAATMVIyUzFSMCIbe3/qG2tgYQysrKAAADAP4AAAY1Bc0AFwAvAEkAAAEyFhcWEhUUAgcOASMiJicmAjU0Ejc+ARciBgcO" +
  "ARUUFhceATMyNjc+ATU0JicuARcVLgEjIgYVFBYzMjY3FQ4BIyImNTQ2MzIWA5qI7WJiYWFiYu2Iie1iYmFhYmLtiXbMVFVWVlVU" +
  "zHZ2zVRUVFVTVM2XPHU7hpeajDptPD17P8Li4sJCegXNbm1t/vqamP77bW1ubm1tAQWYmgEGbW1uZ15eXuWCgeNeXl9fXl3ig4Xj" +
  "XV5e9YEhIK+dn64fIn8dHPTQ0fIcAAMAZwHVAukF8AADAB4AKQAAEyEVIQERIzUOASMiJjU0NjsBNTQmIyIGBzU+ATMyFgciBhUU" +
  "FjMyNj0BfQJr/ZUCaYYnglN0iKuqo2lpOHo+QoM+pKH4kXFYSl11AlB7Arj+QHA/RIdxh4oEW1siIn8cHLDwQ09ATZByHQACAI4A" +
  "jQO7BCMABgANAAABFQkBFQE1ExUJARUBNQO7/vEBD/5aH/7xAQ/+WgQjv/70/vS/AaJSAaK//vT+9L8BolIAAAEAwwEfBUYDXgAF" +
  "AAATIREjESHDBIKX/BUDXv3BAZUAAQBaAd8CQAKDAAMAABMhFSFaAeX+GwKDpAAEAP4AAAY1Bc0AFwAvADgATAAAASIGBw4BFRQW" +
  "Fx4BMzI2Nz4BNTQmJy4BJzIWFxYSFRQCBw4BIyImJyYCNTQSNz4BEyMRMzI2NTQmJzIWFRQGBx4BHwEjJy4BKwERIxEDmnbMVFVW" +
  "VlVUzHZ2zVRUVFVTVM12iO1iYmFhYmLtiIntYmJhYWJi7XBubmNPUFuenV9WFT0pe5p1NUExO4wFZl5eXuWCgeNeXl9fXl3ig4Xj" +
  "XV5eZ25tbf76mpj++21tbm5tbQEFmJoBBm1tbv5i/uw+S0w/Z3d5VnARCE1J39FgM/6cA0QAAQC/BWIC2gX2AAMAABMhFSHAAhr9" +
  "5gX2lAACAK8DdQLrBfAACwAaAAABIgYVFBYzMjY1NCYnMhYXHgEVFAYjIiY1NDYBzUhjY0hIY2RHOWsmKimmeXmipQVvb1BPbW1P" +
  "T3CBMS4tckKEt7SHhroAAAIAwwAABUYFBAALAA8AAAERIRUhESMRITUhEQEhFSEDUAH1/guX/goB9v4KBIL7fgUE/n2q/n0Bg6oB" +
  "g/umqgABAFQCnAJvBfAAGAAAEyEVITU2NwA1NCYjIgYHNT4BMzIWFRQBBvEBfv3mHjkBNl5NLm5BRXgzg5z+1zMDDnJuHzgBMV5C" +
  "USMjexwchGyL/uQwAAABAFgCjQKGBfAAKAAAAR4BFRQGIyImJzUeATMyNjU0JisBNTMyNjU0JiMiBgc1PgEzMhYVFAYB2FJbq58z" +
  "cT8vazxibGNiTVVUV1pVJFxJQnMygZhRBGASbVJ8hhUUeRsaT0ZKTGw/PDo9EhdzERJ2Y0VgAAEBTQTuAv0GZgADAAABMwEjAkqz" +
  "/tuKBmb+iAABAJz+VgRoBGAAIAAAExEzERQWMzI2NREzERQWMzI2NxUOASMiJicOASMiJicRnaV8eoWGph8iCBwaJUIfPkoOLYJZ" +
  "W4Em/lYGCv1IkZSoqAKN/KI8OQsMlBcWTlBPT05O/dcAAQCO/zsDzQXVAA0AAAEhESMRIxEjES4BNTQ2AjoBk3+rgMHU6gXV+WYG" +
  "H/nhA04R3bi+6AAAAQDFAkgBgwNGAAMAABMzFSPFvr4DRv4AAQEF/nUCewAAABMAACEeARUUBiMiJic1HgEzMjY1NCYnAhgyMGxq" +
  "KU4nHkMqNTYmKT5pMFlbDAyDEQ8wLh5XPQAAAQB7ApwCfwXfAAoAABMzEQc1NzMRMxUhjLjJz3y4/g4DCgJjKXQn/StuAAADAFYB" +
  "1QMOBfAAAwAPABsAABMhFSEBMhYVFAYjIiY1NDYXIgYVFBYzMjY1NCZ9Amv9lQE2obm5oaG8vKFfcXJeXnFwAlB7BBvdv7/b3L6/" +
  "3XOhiIWgoIWJoAACAK0AjQPbBCMABgANAAATARUBNQkBJQEVATUJAa4Bpv5aAQ/+8QGGAab+WgEP/vEEI/5eUv5evwEMAQy//l5S" +
  "/l6/AQwBDP//AHv/4wbABfAQJgB5AAAQJwDNBBf9ZBAHAMwC4wAA//8Ae//jBoYF8BAmAHkAABAnAHIEF/1kEAcAzALjAAD//wBY" +
  "/+MGwAXwECYAcwAAECcAzQQX/WQQBwDMAuMAAAACAID+bgNOBGAAIAAkAAABMxUUBg8BDgEVFBYzMjY3FQ4BIyImNTQ2PwE+ATc+" +
  "ATUTIzUzAcKrMVJQNS52YkeiVlWsXabJQVBQKyIHBwWwtbUCz5xlgldYNV4xWW5GQ7w5OMKfTIlWVi81GRU8NgEO/v//AA4AAATe" +
  "B2sSJgAiAAAQBwDmBEMBdf//AA4AAATeB2sSJgAiAAAQBwDkBEMBdf//AA4AAATeB20SJgAiAAAQBwDnBEMBdf//AA4AAATeB14S" +
  "JgAiAAAQBwDlBEMBdf//AA4AAATeB04SJgAiAAAQBwDjBEMBdQADAA4AAATeB20ACwAOACEAAAE0JiMiBhUUFjMyNgsBIQEuATU0" +
  "NjMyFhUUBgcBIwMhAyMC/1A5Ok5POTlQifUB6/6CNziPaGeROTYB3717/aJ6wAZaP1lXQT9YWP7z/RkDTilzSXOgoXJGdin6iwF/" +
  "/oEAAAIABwAABo4F1QAPABMAAAEVIREhFSERIRUhESEDIwEXASERBnz9ZgKA/YACrPyd/iWQuQIzff7XAZ0F1ar+Rqr946oBf/6B" +
  "BdWe/PADEAD//wBn/nUEpAXwEiYAJAAAEAcAeAEPAAD//wC0AAAEFwdrEiYAJgAAEAcA5gQoAXX//wC0AAAEFwdrEiYAJgAAEAcA" +
  "5AQoAXX//wC0AAAEFwdtEiYAJgAAEAcA5wQoAXX//wC0AAAEFwdOEiYAJgAAEAcA4wQoAXX//wA1AAABjgdrEiYAKgAAEAcA5gLe" +
  "AXX//wCRAAAB6QdrEiYAKgAAEAcA5ALeAXX////+AAACJAdtEiYAKgAAEAcA5wLeAXX//wAFAAACHAdOEiYAKgAAEAcA4wLeAXUA" +
  "AgAJAAAFKAXVAAwAGQAAEyEgABEQACkBESM1MxMRIRUhETMgABEQACG+AXYBhgFt/pL+e/6KtbW3AS7+0toBFgED/v3+6gXV/pf+" +
  "gP5+/pYCvJAB4/4dkP3qARgBLgEsARcA//8AtAAABK4HXhImAC8AABAHAOUEfgF1//8AZ//jBUQHaxImADAAABAHAOYEowF1//8A" +
  "Z//jBUQHaxImADAAABAHAOQEowF1//8AZ//jBUQHbRImADAAABAHAOcEowF1//8AZ//jBUQHXhImADAAABAHAOUEowF1//8AZ//j" +
  "BUQHThImADAAABAHAOMEowF1AAEA/AA/BQ0ExQALAAAJAgcJAScJATcJAQUM/mUBm2v+Y/5jagGa/mZqAZ0BnQRM/jX+N3kBy/41" +
  "eQHJAct5/jUBywAAAwBb/7oFTwYXAAkAEwArAAAJAR4BMzISETQmJy4BIyICERQWFwcmAjUQACEyFhc3FwcWEhUQACEiJicHJwQ9" +
  "/Xs4kVXG6CRsN5FWxukjI3hGRwFTARt1x06SXJlGSP6u/uVzx1KSXARY/LJAQwFIARpwuLhAQ/64/uVwvESeZgEIoAFiAaVNS79Z" +
  "xmf+9p7+n/5bS0u/WP//AKD/4wSlB2sSJgA2AAAQBwDmBHABdf//AKD/4wSlB2sSJgA2AAAQBwDkBHABdf//AKD/4wSlB20SJgA2" +
  "AAAQBwDnBHABdf//AKD/4wSlB04SJgA2AAAQBwDjBHABdf////wAAARqB2sSJgA6AAAQBwDkBAEBdQACALQAAAQZBdUADAAVAAAT" +
  "MxEzMhYVFAYrAREjExEzMjY1NCYjtbbk4ufn4uS2tuR/i4qABdX++OHc3OL+rgQn/dGShoaRAAABAKf/4wQ1BhQALwAAEzQ2MzIW" +
  "Fw4BFRQWHwEeARUUBiMiJic1HgEzMjY1NCYvAS4BNTQ2Ny4BIyIGFREjp9fFu8UDiJc0OjSVVsq+OnpCSH47aGw1W1NWTpaIB3Zm" +
  "dXqpBHHI2+jgCHNgL1EqJWqOZKy3GRikHh1fWz9UPjc7h1t/rB1ncIuD+5MA//8Abv/jA8MGZhImAEIAABAGAEFKAP//AG7/4wPD" +
  "BmYSJgBCAAAQBgB0SgD//wBu/+MDwwZmEiYAQgAAEAYAwUoA//8Abv/jA8MGNxImAEIAABAGAMNKAP//AG7/4wPDBhASJgBCAAAQ" +
  "BgBoSgD//wBu/+MDwwcGEiYAQgAAEAYAwkoAAAMAbv/jBrEEewAGADMAPgAAAS4BIyIGBwM+ATMyEh0BIR4BMzI2NxUOASMiJicO" +
  "ASMiJjU0NjsBNTQmIyIGBzU+ATMyFgMiBhUUFjMyNj0BBgoBlHuKpww9Qr93y+79Bgu4pF60Wlq7YJbfRULDgKq94+LolohWpExb" +
  "q1GAwNfJm3RkiqYClJe0rp4BMFpe/t36Wr/INTWuKix5d3h4u6i9wBJ/iy4uqicnYP4YZntic9m0KQD//wBl/nUDhAR7EiYARAAA" +
  "EAcAeACBAAD//wBl/+MEDAZmEiYARgAAEAYAQX0A//8AZf/jBAwGZhImAEYAABAGAHR9AP//AGX/4wQMBmYSJgBGAAAQBgDBfQD/" +
  "/wBl/+MEDAYQEiYARgAAEAYAaH0A////zAAAAXwGZhAnAEH/NAAAEgYAwAAA//8AgQAAAjEGZhAnAHT/NAAAEgYAwAAA////4QAA" +
  "AiAGZhImAMAAABAHAMH/NAAA////9QAAAgwGEBImAMAAABAHAGj/NAAAAAIAZf/jBAMGFAAOACgAAAEuASMiBhUUFjMyNjU0JhMW" +
  "EhUUACMiAhE0EjMyFhcnBSc3JzMXJRcFAvItTyWWp52Dg5wwCHFn/wDP0P74xxAvJo/+4R79o81yASwe/vYDkxEQ2MO83t68erwB" +
  "Jo/+4K3//skBNwD/+gE3BQW0a2NczJFvYWL//wCnAAAD9AY3EiYATwAAEAcAwwCJAAD//wBl/+MEAwZmEiYAUAAAEAYAQWgA//8A" +
  "Zf/jBAMGZhImAFAAABAGAHRoAP//AGX/4wQDBmYSJgBQAAAQBgDBaAD//wBl/+MEAwY3EiYAUAAAEAYAw2gA//8AZf/jBAMGEBIm" +
  "AFAAABAGAGhoAAADAMMAlgVGBG8AAwAHAAsAAAEzFSMRMxUjASEVIQKW3d3d3f4tBIL7fgRv9v4S9QJBqgAAAwBA/6IEJgS8AAkA" +
  "EwArAAAJAR4BMzI2NTQmJy4BIyIGFRQWFwcuATUQEjMyFhc3FwceARUQAiMiJicHJwMu/kolXTqFmhJSJl04iJgREnAxMPXZVI88" +
  "fVaDLzH32FaROX1WAyH9sCoo6MhPdZopKevTSG4ul03FdwEUATgzNKhPs03GeP7t/sc0M6hO//8AnP/jA+kGZhImAFYAABAGAEFv" +
  "AP//AJz/4wPpBmYSJgBWAAAQBgB0bwD//wCc/+MD6QZmEiYAVgAAEAYAwW8A//8AnP/jA+kGEBImAFYAABAGAGhvAP//ADb+VgQM" +
  "BmYSJgBaAAAQBgB0VQAAAgCn/lYELgYUABAAHAAAJREjETMRPgEzMhIREAIjIiYBNCYjIgYVFBYzMjYBTqenNJ9vuOXluG+fAf+W" +
  "g4SWloSDlqj9rge+/aJkYf68/vj++P68YQHry+fny8vn5wD//wA2/lYEDAYQEiYAWgAAEAYAaFUAAAIArQAAAVQEewADAAQAABMz" +
  "ESMTrqWlUgRg+6AEewAAAQCtBO4C7AZmAAYAAAEzEyMnByMBioXdfaKifQZm/oj19QAAAgDWBOECxAcGAAsAFwAAATQmIyIGFRQW" +
  "MzI2NxQGIyImNTQ2MzIWAlZQOTtOTjs5UG2PZ2iPj2hnjwX0P1hXQEFXWEBzoKBzc5+fAAEAowUdAvYGNwAbAAABJy4BIyIGByM+" +
  "ATMyFh8BHgEzMjY3Mw4BIyImAckzFB4LIyACcAJbUiM5ITQUHQwiIQFxAlxSIjoFWjcUE0lSh5McITcUE0lSh5McAAEAWgHpA0AC" +
  "eQADAAATIRUhWgLm/RoCeZAAAQBaAekG2gJ5AAMAABMhFSFaBn/5gQJ5kAABAJwD6QGlBdUABQAAASM1EzMDAVq9k3RKA+mtAT/+" +
  "wQAAAQCgA/4BqAXVAAUAABMzFQMjE+q+lHRKBdWY/sEBPwACAJwD6QMWBdUABQALAAABIzUTMwMFIzUTMwMBWr2TdEoBcr6TdEkD" +
  "6a0BP/7Bra0BP/7BAAACAJwD6QMWBdUABQALAAATMxUDIxMlMxUDIxPmvpN0SQFxvpN0SQXVrP7AAUCsrP7AAUAAAQEUAdEDKwQh" +
  "AAsAAAE0NjMyFhUUBiMiJgEUnHFwmptwcZsC+nyrq3x9rKwAAAMA1AAABl8A/gADAAcACwAAJTMVIyUzFSMlMxUjAzq/vwJlwMD7" +
  "NcDA/v7+/v7+AAH+rv/jAoYF8AADAAABMwEjAfWQ/LmQBfD58wACADgCnAKpBd8AAgANAAAJASEDMxEzFSMVIzUhNQGt/uoBFhOV" +
  "eXmC/owFZv5dAhz95G26unkAAAEAVv/kBDsF8AAsAAAlNjc2NxUOASMgABEQACEyFhcVLgEjIgIREBcWFxEzFT4BMzIWHwEuASMi" +
  "BhUC3VdPX1RXw23+6f6+AUIBF27EVVS+a9PgcFSKiSuKYw4iFQEYNiBzfYoHJy9f00hHAZ4BZwFoAZ9HR9VfXv7H/tj+2Zx1HgNd" +
  "nVxZBAWqEA+2qwACAFP/WwQ5BngAJAAtAAAFIzUmJyYREDc2NzUzFRYXFhcVJicmJxE2NzY3ESM1IREGBwYHJxEGBwYREBcWAq1+" +
  "yXuXl3vJfl5XZVRVYVhgRjlBM2wBBVlsXml+eEdkZEeljx+nzAFtAW7Nph+PiQQfJEbXXzAsBPs/AhESJwGRpv1/UyolBbIEpyBs" +
  "mf7R/tKZbAAAAQCe/fwC/AeSAAsAAAEjNRATEhMzAgMCEQFOsJColZDqUXL9/OoDlwHiAjABA/3z/ob97vztAAABAJ79/AFOB4kA" +
  "AwAAEzMRI56wsAeJ9nMAAAEAnv4UAvwHiQALAAABFRATEhMjAgMCETUBTnKEt5C7gpAHier8pf5X/hT+ZQFFAe4CJgMy6gAAAQCe" +
  "/fwC/AeSAAsAAAE1EAMCAzMSExIRFQJMc1HqkJankP386gMTAhIBeQIO/v390P4e/GnqAAABAkv9/AL8B4kABAAAAREjETAC+68H" +
  "ifZzCY0AAQCe/hQC/AeJAAsAAAEzFRADAgMjEhMSEQJMr5CBvJC3hHMHier8zf3b/hL+uwGbAewBqQNbAAABAJ79/AL8B20ABQAA" +
  "ASMRIRUhAU6wAl3+U/38CXHDAAEAnv38AU4HiQADAAATMxEjnrCwB4n2cwAAAQCe/hQC/AeJAAUAAAERIRUhEQFOAa39oweJ907D" +
  "CXUAAAEAnv38AvwHbQAFAAABESE1IRECTP5SAl39/Aiuw/aPAAABAkv9/AL8B3oAAwAAATMRIwJMr68HevaCAAEAnv4UAvwHegAF" +
  "AAABMxEhNSECTK/9owGuB3r2msMAAQJf/eoE0AdtAA0AAAEjETQ3NjsBFSMiBwYVAwenY22o9/1bPTP96gd135GesGZXmQABAJf9" +
  "/AMHB4YAGAAAARYXFhkBIxEQJyYvATUzMjc2GQEzERAHBgJSNCZbp2RD6zc36UVkp1skAsEgPZP+Q/3oAgwBt19BBAG7RWMBswIM" +
  "/ej+SJg8AAECX/4UBNAHhgANAAABERQXFjsBFSMiJyY1EQMHMz1b/femb2MHhviUmlZmsJ6P4QdkAAABAl/99AMHB4wAAwAAASMR" +
  "MwMHp6f99AmYAAEAl/3qAwcHbQANAAABETQnJisBNTMyFxYVEQJgND1b/finbWT96gd9mVdmsJ6R3/iLAAABAl/9/ATQB4YAGAAA" +
  "ASYnJhkBMxEQFxY7ARUHBgcGGQEjERA3NgMUNiRap2NF6Tc360Njp1omAsEhPJgBuAIY/fT+TWNFuwEEQV/+Sf30AhgBvZM9AAEA" +
  "l/4UAwcHhgANAAABMxEUBwYrATUzMjc2NQJgp2Rvpfj9Wz00B4b4nOGPnrBmVpoAAv0nBQ7/PwXZAAMABwAAATMVIyUzFSP+iLa2" +
  "/qC3twXZy8vLAAAB/bQE7v8MBfYAAwAAATMDI/5lps2KBfb++AAAAf0KBQ7/XQXpAB0AAAEnLgEjIgYdASM0NjMyFh8BHgEzMjY9" +
  "ATMOASMiJv4wNBYcCyAkcV1NITcrMxUeDh0kcAJcTB42BTkhDgsyLQZldhAbHg0MMykGZHcQAAAB/VcE7v6xBfYAAwAAARMjA/4A" +
  "sInPBfb++AEIAAAB/SAE7v9GBfgABgAAATMTIycHI/3fqb59lpV9Bfj+9rKyAAABAAAA6ANUACsAaAAMAAEAAAAAAAAAAAAAAAAA" +
  "CAAEAAAAFQAVACsAPwB7AMcBFQFiAXABjQGpAc8B6AH4AgUCEQIfAk0CZAKTAs4C6wMbA1cDagOwA+sD/AQSBCcEOgROBIcE+wUX" +
  "BU0FewWjBbsF0AYEBhwGKQY/BlkGaQaHBp4G0AbyBywHXQeZB6wHzQfiCAIIIQg4CE8IYQhwCIIImAilCLQI6wkbCUYJdgmnCccK" +
  "BQonCjkKVApuCnsKrwrQCvoLKQtZC3gLswvUC/gMDAwpDEkMaAx/DLEMvwzxDSENIQ04DXQNnw3pDhYOKw6GDpkPBg9ED2YPdg+D" +
  "D/cQBBAvEE8QeRCzEMEQ8xEOERoROxFREX4RohGyEcIR0hILEhcSIxIvEjsSRxKBEqkStRLBEs0S2RLlEvES/RMJExUTRxNTE18T" +
  "axN3E4MTjxOxE/0UCRQVFCEULRQ5FF0UoxSuFLkUxBTPFNoU5RVAFUwVVxViFW0VeBWEFZAVnBWoFesV9xYCFg0WGBYjFi4WSBaP" +
  "FpoWpRawFrsWxhb2FwEXERcjF0kXdheDF5AXoRexF8wX5hf9GBUYIxg/GIYY0BjsGPkZFRkxGT8ZWxlrGXgZiRmaGacZtxnQGfsa" +
  "FRoiGjwaZxqAGpMaoRrPGt4a8AAAAAEAAAACXrhYqSVXXw889QAfCAAAAAAA08Ir+QAAAADTwiv5+Kf8TAzqCdwAIAAIAAAAAAAA" +
  "AAAEUgBbAkkAAALiARYDTwCxBggAjgSUAJkG1wBlBZ0AdAH6ALECzwCeAs8AkwOZADYGCADDAkkAjgKZAFoCSQDFAm0AAASUAHkE" +
  "lADKBJQAhwSUAIwElABaBJQAjgSUAIAElACXBJQAfQSUAHQCbQDYAm0AjgYIAMMGCADDBggAwwPSAIQHMwB5BOwADgTwALQFBwBn" +
  "BYsAtASMALQEJAC0BZQAZwVqALQCHwC0Ah//oQS4ALQEAgC0BjYAtAViALQFqgBnBFcAtAWqAGcFAAC0BJIAeQRl//sFRQCgBOwA" +
  "DgceAD0E7gA2BGX//QTuAFICzwCeAm0AAALPALMGCADDA5n/7gOZAJkEaQBuBJIApwP1AGUEkgBlBG4AZQKIACoEkgBlBJAApwIA" +
  "AK0CAP/fBCsApwIAAK0HAwCnBJAApwRnAGUEkgCnBJIAZQL1AKcDwABjAtIAMQSQAJwEQgA2BeMATQRCADUEQgA2A8cATwSUAOYC" +
  "bQDqBJQA5gYIAMMCSQAAAuIBFgSUAJoElAB0BJQAVASUAEkCbQDqA5kAUgOZAMEHMwD+A2QAZwRnAI4GCADDApkAWgczAP4DmQC/" +
  "A5kArwYIAMMC4gBUAuIAWAOZAU0ElACcBJQAjgJJAMUDmQEFAuIAewNkAFYEZwCtBvoAewb6AHsG+gBYA9IAgATsAA4E7AAOBOwA" +
  "DgTsAA4E7AAOBOwADgcDAAcFBwBnBIwAtASMALQEjAC0BIwAtAIfADUCHwCRAh///wIfAAUFlAAJBWIAtAWqAGcFqgBnBaoAZwWq" +
  "AGcFqgBnBggA/AWqAFsFRQCgBUUAoAVFAKAFRQCgBGX//QRbALQEiQCnBGkAbgRpAG4EaQBuBGkAbgRpAG4EaQBuBxEAbgP1AGUE" +
  "bgBlBG4AZQRuAGUEbgBlAgD/zQIAAIECAP/iAgD/9gRnAGUEkACnBGcAZQRnAGUEZwBlBGcAZQRnAGUGCADDBGcAQASQAJwEkACc" +
  "BJAAnASQAJwEQgA2BJIApwRCADYCAACtA5kArQOZANYDmQCjA5kAWgczAFoCSQCcAkkAoAO6AJwDugCcBD8BFAczANQBM/6vAuIA" +
  "OASUAFYElABTA5kAngOZAJ4DmQCeA5kAngOZAksDmQCeA5kAngOZAJ4DmQCeA5kAngOZAksDmQCeBWYCXwVmAJcFZgJfBWYCXwVm" +
  "AJcFZgJfBWYAlwAA/Sj9tf0L/Vj9IQABAAAHbf4dAAANfvin+uMM6gABAAAAAAAAAAAAAAAAAAAA5AABA6YBkAAEAAAFMwWZAAAB" +
  "HgUzBZkAAAPXAGYCEgAAAgsGBgMIBAICBIAAAAMAAAACAAAAAAAAAABQZkVkAEAAICCyBhT+FAGaB20B4wAAAAEAAAAAAAAAAAAD" +
  "AAAAAwAAABwAAAAKAAAAfAADAAEAAAAcAAQAYAAAABQAEAADAAQAfgD/IBQgGSAdICIgJiCiILL//wAAACAAoCATIBggHCAiICYg" +
  "oiCy////4f/A4LHgruCs4KjgpeAs4B0AAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAHwAAAAAAAAACQAAACAAAAB+AAAAAQAA" +
  "AKAAAAD/AAAAYAAAIBMAACAUAAAAxAAAIBgAACAZAAAAxgAAIBwAACAdAAAAyAAAICIAACAiAAAAygAAICYAACAmAAAAywAAIKIA" +
  "ACCiAAAAzgAAILIAACCyAAAAzwAAAAUAQgADAAEECQABACoAAAADAAEECQACAAgAKgADAAEECQADACoAAAADAAEECQAEACoAAAAD" +
  "AAEECQAGACYAMgBEAGUAagBhAFYAdQAgAFMAYQBuAHMAIABDAG8AbgBkAGUAbgBzAGUAZABCAG8AbwBrAEQAZQBqAGEAVgB1AFMA" +
  "YQBuAHMAQwBvAG4AZABlAG4AcwBlAGQAAAADAAAAAAAA/34AWgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAIAAL//wADAAEAAAAK" +
  "AOAA6ABQADwMAAfdAAAAAAKCAAAEYAAABdUAAAAAAAAEYAAAAAAAAAAAAAAAAAAABGAAAAAAAAABaAAABGAAAABVAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEOAAACdgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWgAAAQ4AAABa" +
  "AAAAWgAAAQ4AAAAAAAAAAAAAAQ4AAABaAAAAWgAAAQ4AAABaAAAAWgAAAFoAAAFyAAAAWgAAAFoAAAI4AAD7jwAAADwAAAAAAAAA" +
  "AAAoAB4AMAAHAAMAOgBiAIoAsgDaARYBNAFwAY4BrAABAAcACQAKADwAPgBcAF0AXgABAAMAHgBAAG8ABAAAAAAAAAADANIAAAAo" +
  "CXUAAADRACgAKAmNAAEA0AAoAAAJlgAAAAQAAAAAAAAAAwDVAAAAKAl1AAAA1AAoACgJjQABANMAKAAACZYAAAAEAAAAAAAAAAMA" +
  "2AAAACgJdQAAANcAKAAoCY0AAQDWACgAAAlxAAAABAAAAAAAAAADANsAAAAoCWYAAADaACgAKAl+AAEA2QAoAAAJcQAAAAQAAAAA" +
  "AAAABQDeAAAAKAlyAAAA3wAoACgJmAABAN0AKAAoCYoAAADfACgAKAmYAAEA3AAoAAAJgwAAAAQAAAAAAAAAAgBdAAAAKAgAAAAA" +
  "XQAoAAAIAAABAAQAAAAAAAAABQDiAAAAKAlyAAAA3wAoACgJmAABAOEAKAAoCYoAAADfACgAKAmYAAEA4AAoAAAJgwAAAAQAAAAA" +
  "AAAAAgAeAAAAJASCAAAAHgAkAAAEggABAAQAAAAAAAAAAgBAAAAAJAO+AAAAQAAkAAADvgABAAQAAAAAAAAAAgBvAAAAJAIaAAAA" +
  "bwAkAAACGgABAAA=";
