/**
 * Encode Sans Condensed Regular (Pablo Impallari), recortada a los caracteres que
 * usa el ticket, en base64 para que jsPDF la pueda embeber en el PDF.
 *
 * Se elige en `ticketFuente.ts` (constante `FUENTE_ACTIVA`), donde estan las
 * mediciones de todas las candidatas.
 *
 * El .ttf de origen ya es estatico, no hace falta instanciarlo.
 *
 * ARCHIVO GENERADO — no editar a mano. Para regenerarlo, desde la raiz del
 * repo (necesita `pip install fonttools`):
 *
 *   python -m fontTools.subset  *     backups/EncodeSansCondensed/EncodeSansCondensed-Regular.ttf  *     --unicodes="U+0020-007E,U+00A0-00FF,U+2013,U+2014,U+2018,U+2019, *                 U+201C,U+201D,U+2022,U+20A2,U+20B2,U+2026"  *     --layout-features="" --no-hinting --desubroutinize  *     --drop-tables+=DSIG,GSUB,GPOS,GDEF --name-IDs="1,2,3,4,6"  *     --notdef-outline  *     --output-file=client/src/assets/fonts/EncodeSansCondensed-Regular.subset.ttf
 *
 * y despues volver a codificar el .ttf en base64 aca.
 *
 * El subset deja los 99 caracteres que el ticket puede imprimir: 16 KB.
 *
 * La tabla `name` NO se puede quitar: el parser de TTF de jsPDF la necesita y
 * revienta sin ella.
 *
 * Licencia: Copyright 2012 The Encode Project Authors, con Reserved Font Name
 * "Encode Sans". SIL Open Font License 1.1.
 */
export const ENCODE_SANS_CONDENSED_REGULAR_BASE64 =
  "AAEAAAALAIAAAwAwT1MvMnE1i0MAADucAAAAYGNtYXCrI4oGAAA7/AAAAepnYXNwAAAAEAAAP0AAAAAIZ2x5Zhz1ZikAAAC8AAA1" +
  "GGhlYWQORw76AAA3vAAAADZoaGVhDgUHPwAAO3gAAAAkaG10eOjAGEYAADf0AAADhGxvY2G0P8GrAAA19AAAAchtYXhwAPcAuQAA" +
  "NdQAAAAgbmFtZRhIK48AAD3oAAABNnBvc3T/uAAyAAA/IAAAACAACgC//kgDSwZQAAMADwAVABkAIwApADUAOQA9AEgAAAERIREF" +
  "IRUzFSMVITUjNTMHIxUhNSMnFSM1BSEVMxUjFTM1MxUjFSEVIRUjFTM1MxUjNSMVIRUhFSEnFSM1BSEVMwcVITUjNzMDS/10Ae7+" +
  "rIaIAVaIiIjOAVaIRkQBEv6qiIjOiET+7gFWzkZEzkQBVv6qAVZEzgES/qqQkAFW0pBCBlD3+AgIikRMRERMxdZGSkpKx0RMRJA4" +
  "h0YuczBhpOh76aVhYdREYEREYAACABEAAASGBcgABwAKAAAhAyEDIwEzAQEhAwPqk/3lkpkBzdsBzfzgAcjkAd/+IQXI+jgCZwLq" +
  "//8AEQAABIYHZAAiAAIAAAADANoEEQAA//8AEQAABIYHZAAiAAIAAAADANsEEQAA//8AEQAABIYHNgAiAAIAAAADANgEEQAA//8A" +
  "EQAABIYHZAAiAAIAAAADANkEEQAA//8AEQAABIYHwgAiAAIAAAADANwEEQAA//8AEQAABIYHOQAiAAIAAAADAN0EEQAAAAIAEQAA" +
  "BjAFyAAPABMAACUhFSEDIQMjASEVIRMhFSEFIQMjA9MCXf0VGf4Xl5sB1gQ//W4bAhn97v24AbclrYmJAd/+IQXIif39iUsC1wAA" +
  "AwCQ//MEKwXYABEAHQAoAAAAFhUUBCEiJxE2MzIWFhUUBgcABxEzMjY2NTQmJiMSNjY1NCYjIREWMwOWlf7e/sWjm7GvuOpveoL+" +
  "hmTeh55DSKCHirtUsb3+/lZwAuC9ls7MFAWvIlOsh323IQJbEf3yPnhbYXY3+xs9fWSUkf3GCQAAAQBW/+0DuQXbABsAAAQkAhEQ" +
  "ACEyFxUmJiMiBgIVFBIWMzI2NxUGBiMB4v7/iwExASeKgUJ/RpXBZGS+kkGATD2STBOTAU4BEwGSAWgmiRUSdP7u6O3+7nEZGokX" +
  "GwAAAQBW/mADuQXbAC4AAAAGAhUUEhYzMjY3FQYGIyMVFhYVFAYjIic1FjMyNTQmIyM1JgIREAAhMhcVJiYjAh3BZGS+kkGATD2S" +
  "TApNWG1jX1JYU3Y/OSft9wExASeKgUJ/RgVTdP7u6O3+7nEZGokXG1QIT0RLUyNRJlUrKpobAWMBcQGSAWgmiRUSAAACAJD/8wRc" +
  "BdgACwAYAAAEJxE2MyAAERACBCM2NhI1NAImIyIHERYzAS2dtooBSAFEmv7R5sfabmnTpldZUFENEAW0If6P/n3++P6znId6ARDg" +
  "3QESfg77PwgAAAL//f/zBFwF2AAPACAAAAAAERACBCMiJxEjNTMRNjMSNhI1NAImIyIHESEVIREWMwMYAUSa/tHmgJ2Tk7aKpNpu" +
  "adOmV1kBEP7wUFEF2P6P/n3++P6znBACv3EChCH6onoBEODdARJ+Dv3wcf3ACAABAJAAAAO6BcgACwAAJSEVIREhFSERIRUhASgC" +
  "kvzWAyD9eAIq/daJiQXIif39if//AJAAAAO6B2QAIgAPAAAAAwDaA/wAAP//AJAAAAO6B2QAIgAPAAAAAwDbA/wAAP//AJAAAAO6" +
  "BzYAIgAPAAAAAwDYA/wAAP//AJAAAAO6B2QAIgAPAAAAAwDZA/wAAAABAJAAAAOoBcgACQAAASERIRUhESMRIQOo/YICIv3emgMY" +
  "BT798or9WgXIAAEAVv/zBAwF2wAaAAABEQYjIiQCERAAITIXFSYjIgYCFRQSFjMyNxEEDJV84/7WmAFHATuTiYaOpNVvb9uuSEIC" +
  "0P09GpYBSwEPAZIBZieJKHT+7evm/vNzCQJMAAABAJAAAARbBcgACwAAMxEzESERMxEjESERkJoCl5qa/WkFyP13Aon6OAKw/VAA" +
  "AQCQAAABKgXIAAMAADMRMxGQmgXI+jj//wCQAAABwgdkACIAFwAAAAMA2gKiAAD////TAAAB5wdkACIAFwAAAAMA2wKiAAD///+y" +
  "AAACCAc2ACIAFwAAAAMA2AKiAAD////3AAABKgdkACIAFwAAAAMA2QKiAAAAAf/u/qkBKgXIAAkAAAM2NjURMxEGAgcSWUmaBV9v" +
  "/u+K+rAEpftJtP7nmwABAJAAAARzBcgADAAAIQEjESMRMxEzATMBAQPI/gupmpqtAc2m/gECKAKw/VAFyP12Aor9Mv0GAAEAkAAA" +
  "A50FyAAFAAAzETMRIRWQmgJzBcj6xIwAAAEAlAAABZIFyAAMAAABMxEjEQEjAREjETMBBNq4kf5WiP5WkbgBygXI+jgE0/v6A/v7" +
  "OAXI+6wAAQCQAAAEcwXIAAkAAAEzESMBESMRMwED4pGf/U2RnwKzBcj6OATG+zoFyPs6//8AkAAABHMHOQAiACAAAAADAN0ERgAA" +
  "AAIAVv/tBHMF2wAHABcAABYRECEgERAhNjYSNTQCJiMiBgIVFBIWM1YCDwIO/fJ1oVhYoHZ2oVhYoXYTAvcC9/0J/QmHdAER5usB" +
  "FXV0/u/m6/7rdQD//wBW/+0EcwdkACIAIgAAAAMA2gQqAAD//wBW/+0EcwdkACIAIgAAAAMA2wQqAAD//wBW/+0Ecwc2ACIAIgAA" +
  "AAMA2AQqAAD//wBW/+0EcwdkACIAIgAAAAMA2QQqAAAAAwBW/+QEcwXkABEAGwAlAAAAERAhIicHJzcmERAhMhc3FwcAFwEmJiMi" +
  "BgIVADYSNRAnARYWMwRz/fLSf1BVYnsCD9N9UVVi/P04AjYuf1J2oVgB5KFYOP3KLoBSBFH+k/0JeIE2nrwBcAL3eYI2nvzUlQOQ" +
  "Pjd0/u/m/Yt0ARHmAQSV/HA9NwD//wBW/+0Ecwc5ACIAIgAAAAMA3QQqAAAAAgCQAAAD+QXYAAsAFgAAEzYzIAQRECEiJxEjADY1" +
  "NCYjIgcRFjOQtpEBEgEQ/ctTR5oCCsa6xV1aQ1wFtyH4/v3+CAf+FAJps73GtQ79LAkAAAIAkAAAA/kFyAANABgAABMzFTYzIAQR" +
  "ECEiJxEjADY1NCYjIgcRFjOQmlRaARIBD/3MVEeaAgrGusVdWkNcBcjjDPf+/f4IB/76AYOzvca1Dv0sCQAAAgBW/x4EcwXbAA0A" +
  "HQAAAAIHFhcHJCQCERAhIBEEEhYzMjYSNTQCJiMiBgIVBHPl373wHP58/lG3Ag8CDvyDWKF2daFYWKB2dqFYAYr+hhJDGIU52gF6" +
  "ATkC9/0J5v7rdXQBEebrARV1dP7v5gACAJAAAARrBdgAEgAdAAAhAQYjIicRIxE2NjMgBBUWBgcBADY1NCYjIgcRFjMDwv5bKi5S" +
  "S5hZolsBCgEHAaagAbn+L8mxwmtdWEECZwMF/ZcFtxAR29qm1Cr9gQLkmaSflxD9owYAAAEAN//tA1sF2wAoAAAEJic1FjMyNjU0" +
  "JiYnJyYmNTQ2NjMyFhcVJiMgERQWFhcXFhYVFAYGIwE5pUadmJ2eMm5fRp6kbNaaRZE1eIv+uTBoWkanqG/UlhMcGog2h4VLZkoh" +
  "GDfCmX61YRQSiCb+/0hiSCAYOcWdg7tiAAABAAcAAAQDBcgABwAAIREhNSEVIREBuP5PA/z+TwU8jIz6xAABAIj/7QRLBcgAEwAA" +
  "BCYmNREzERQWMzI2NREzERQGBiMBxNVnmp2trJ2WZdOnE3PvuwO+/C/IurrIA9H8Qrvvc///AIj/7QRLB2QAIgAvAAAAAwDaBDEA" +
  "AP//AIj/7QRLB2QAIgAvAAAAAwDbBDEAAP//AIj/7QRLBzYAIgAvAAAAAwDYBDEAAP//AIj/7QRLB2QAIgAvAAAAAwDZBDEAAAAB" +
  "AAMAAAR3BcgABgAAATMBIwEzAQPhlv445P44oAGdBcj6OAXI+rEAAQAqAAAHBQXIAAwAAAEzASMBASMBMwEBMwEGc5L+msv+x/7B" +
  "y/6ZnQE4AUO1AT4FyPo4BQ368wXI+tIFLvrOAAEACgAABGAFyAALAAABASMBASMBATMBATMCkAHQrP6C/oCsAdL+QawBbQFtqgL0" +
  "/QwCcv2OAvMC1f2uAlIAAf/dAAAEJgXIAAgAAAEBESMRATMBAQQm/iyZ/iSlAYYBgwXI/Mv9bQKSAzb9XAKkAP///90AAAQmB2QA" +
  "IgA3AAAAAwDaA8sAAAABADIAAAOvBcgACQAANyEVITUBITUhFfgCt/yDAq39XQNpiopYBOaKWAACAET/7gMHBE4AHgApAAAAFhYV" +
  "ESMnIwYGIyImJjU0Njc3NTQmJiMiBgc1NjYzEjY3EQcGBhUUFjMCFKFSfwsKLYlVV4RJrrfJNWhVOYU/OpdCOnUtvm1pXVcETkil" +
  "jP0rd0RFRoVckqERFW5caSsVFoIUF/wbPkcBFRMLZFtfXgD//wBE/+4DBwZQACIAOgAAAAMA0gN/AAD//wBE/+4DBwZQACIAOgAA" +
  "AAMA0wN/AAD//wBE/+4DBwXwACIAOgAAAAMAzwN/AAD//wBE/+4DBwZQACIAOgAAAAMA0QN/AAD//wBE/+4DBwZjACIAOgAAAAMA" +
  "1AN/AAD//wBE/+4DBwX+ACIAOgAAAAMA1QN/AAAAAwBE/+0FUARPACwANAA/AAABIR4CMzI3FQYjIiYnBgYjIiYmNTQ2MzM1NCYm" +
  "IyIGBzU2NjMyFhc2MzISEQAGByEuAiMANyYnIyIGFRQWMwVQ/bcDRINpXYd8d4i3Mz6jZFuKS7jFszZrVDiEQD6QQX2eI1jDq7r+" +
  "LXMDAbUCNlxD/lZVGAOpfXFgVwHqj6ZHKIInWmJmVUSEXZetiFtnKxYVghUWUlir/vb+2AHArtiXq0T8jaxcfG1fXFwAAAIAf//t" +
  "A3kGUAAOABwAAAQmJxEzETM2NjMyFhEQITY2NTQmJiMiBgcRFhYzAUyVOJgJJX9Qnsf+GKmiP2xNPnAfGUkgExgUBjf9hTVE//7j" +
  "/bt+zeukukc+OP0rCAoAAAEAS//tAs4ETgAYAAAEAhE0NjYzMhcVJiMiBgYVFBYWMzI3FQYjAR7Ta8uYYVRTS3ONRkB+Y1Jxb3ET" +
  "AQgBKcr3bxWFFU64oKS9UCaEJwAAAQBL/mACzgROACwAAAAGBhUUFhYzMjcVBiMjFRYWFRQGIyImJzUWMzI1NCMjNSYCETQ2NjMy" +
  "FxUmIwG9jUZAfmNScW9xBENIZF8oTyBFUGdpHqGka8uYYVRTSwPJTrigpL1QJoQnVwpQP0hVEQ9RI1NXnBsBCQEGyvdvFYUVAAAC" +
  "AEv/7QNGBlAAEQAfAAAEJiY1EBIzMhcRMxEjJyMGBiM2NjcRJiYjIgYVFBYWMwFSpWL39jVBmIMLCiV+UWNxIBlJHqOjP2xME2nx" +
  "wgEnAR0HAgr5sG46R4ZAOwLWBQfM7KW5RwACAEv/7ANsBlAAFwAmAAAAEhUQISARECEyFyYnBSclJiczFhc3FwcCNjU0JiYjIgYG" +
  "FRQWFjMC+3H+cv5tAYprTTBN/qEUATdcd65gU+EUvUd+OmtPUGs6OmtRBIn+erz9pQIxAi87iH1CYDp7Z1F3Kl8j+zfJ6KjCT06/" +
  "pajCTgAAAgBL/+0DOAROABUAHQAAASEeAjMyNxUGBiMiJiY1EBIzMhIRAAYHIS4CIwM4/a8DRIZrYIdDdj6bxmPMtrG6/il3AwG9" +
  "AjVdRAHqj6ZHKIIVEm/4zAEfAQ/+9P7bAb+t2JSsRQD//wBL/+0DOAZQACIARwAAAAMA0gOMAAD//wBL/+0DOAZQACIARwAAAAMA" +
  "0wOMAAD//wBL/+0DOAXwACIARwAAAAMAzwOMAAD//wBL/+0DOAZQACIARwAAAAMA0QOMAAAAAQAIAAAClAZkABUAAAAGFRUhFSER" +
  "IxEjNTM1NDYzMhcVJiMBu2QBGf7nl7i4rKlHOD00BeJha9l+/EEDv37Upq0LggsAAAIAS/40A0YETgAcACoAAAAmJzUWMzI2NjU1" +
  "IwYGIyImJjUQEjcyFhcRFAYjEjY3ESYmIyIGFRQWFjMBU444g3tjf0EKJX9QZKBh9/JElzfX24pxHxxIH6GiPmxO/jQVFIMsPYt0" +
  "eTVEaPDBAScBHQEYFPvj9tsCQT05AtUHCc3rpLhHAAEAfwAAA1gGUAAUAAATMxEzNjYzMhYVESMRNCYjIgYHESN/mAk1j1eDmphe" +
  "V0KJKZgGUP10RUWjuf0OAut1YURJ/Mz//wBfAAABNgXzACIAUAAAAAMA0AKQAAAAAQB/AAABFwQ9AAMAADMRMxF/mAQ9+8P//wB/" +
  "AAAByQZQACIAUAAAAAMA0gKQAAD////QAAABxgZQACIAUAAAAAMA0wKQAAD///+yAAAB5AXwACIAUAAAAAMAzwKQAAD////MAAAB" +
  "FwZQACIAUAAAAAMA0QKQAAD////d/jABNgXzACIAVgAAAAMA0AKQAAAAAf/d/jABFwQ9AAoAAAM2NjURMxEUBgYHI1lJmCtbTP51" +
  "ivqxA5P8eIbUwWoAAAEAfwAAA6EGUAAMAAAhASMRIxEzETMBMwEBAvf+rIyYmIoBOab+ogF/Ae3+EwZQ/BsB0v3x/dIAAQB/AAAB" +
  "FwZQAAMAADMRMxF/mAZQ+bAAAQB/AAAFYwROACMAAAAWFREjETQjIgYHFhURIxE0JiMiBgcRIxEzFzM2NjMyFzY2MwTIm5iuO34q" +
  "A5VaUD6BKJiADAo3jlO0PTybUQROo7r9DwLr2ENKHiH9CQLrdGRITPzRBD16RkWZT0oAAQB/AAADWAROABQAABMzFzM2NjMyFhUR" +
  "IxE0JiMiBgcRI3+ADAo3kleHnJheV0OHKpgEPXlDR6G3/QoC7XNjRkn8zP//AH8AAANYBf4AIgBaAAAAAwDVA7EAAAACAEv/7QNu" +
  "BE4ACgAaAAAWERASMzISERACIz4CNTQmJiMiBgYVFBYWM0vPw8DRz8JQajo6a09Qazo6a1ATAjABJQEM/vL+3v7c/vN8Tr6lqMJO" +
  "Tb+lqMJOAP//AEv/7QNuBlAAIgBcAAAAAwDSA6IAAP//AEv/7QNuBlAAIgBcAAAAAwDTA6IAAP//AEv/7QNuBfAAIgBcAAAAAwDP" +
  "A6IAAP//AEv/7QNuBlAAIgBcAAAAAwDRA6IAAAADAEv/5ANuBFkAEwAdACcAAAAREAIjIicHJzcmERASMzIXNxcHJAYGFRQXASYm" +
  "IxI2NjU0JwEWFjMDbs/CmGE7VEtVz8OWXztUS/52bjsdAYsfVjlRbTwf/nMfWToDJP76/tz+81JbNnaLAQIBJQEMUFs1dSVOv6am" +
  "YwJtKiX8kk7Apqll/ZEsJ///AEv/7QNuBf4AIgBcAAAAAwDVA6IAAAACAH/+SAN5BE4AEAAeAAATMxczNjYzMhYREAIjIicRIwA2" +
  "NTQmJiMiBgcRFhYzf4ILCiV+UaPM9/Y7OpgBuqM/a0w+ch8YSR4EPXA6R//+4/7Z/uII/lMCI8zspLpHQDv9KgUHAAACAH/+SAN5" +
  "BlAAEQAfAAATMxEzNjYzMhYWFRACIyInESMANjU0JiYjIgYHERYWM3+YCSd+VGSdX/f2OzqYAbqjP2tLQHEfGEkeBlD9hTZDafHC" +
  "/tn+4gj+UwIjzOykukc+OP0lBQcAAAIAS/5IA0YETgAQAB4AACUjBgYjIiYmNRASMzIWFxEjAjY3ESYmIyIGFRQWFjMCrgolf1Bm" +
  "n2D38kSXN5iQcR8cSB+hoj9sTWc2RGrxwgEnAR0YFPomAiw9OQLWBwnN6qS6RwABAH8AAAJkBEgAEAAAEzMXMzY2MzIXFSYjIgYH" +
  "ESN/fw0KLo9VFyYYLk+RJ5gEPZRPUAWRBFRK/OgAAQA//+0CwgROACYAABYnNRYzMjY1NCYnJyYmNTQ2NjMyFxUmJiMiBhUUFhcX" +
  "FhYVFAYGI8t1hHJxdkhLboBzWKt4bWY2YDd6eEVJboZyWad0EymBKl9YS1EVHSOPdFuMTxiCDQxkT0RPFR4kkHdij0sAAQAI/+0E" +
  "hAZkADwAAAAWFRQGBiMiJzUWMzI2NTQmJycmJjU0NjYzMhc2NTQmIyIGFREjESM1MzU0NjMyFhUUBgcmIyIGFRQWFxcEE3FZp3WE" +
  "cnp4c3dHS26AdFereBsRBZqEmJ6YuLjv173gEQs7Rnx5REpuAjCQd2KPSySCJl5ZS1EVHSKQdFqKTQEvKLGbtcz7lgO9gDL3/tvp" +
  "O3ksDWRPRE8VHgAAAQAA/+0CeAXIABYAACQ3FQYjIiY1ESM1MxMzESEVIREUFhYzAjs9TEGVnri4GX8BGv7mKFFBdQ6FEaGvAoJ+" +
  "AYv+dX79k1NgKgABAHb/7QNGBD0AFAAABCY1ETMRFBYzMjY3ETMRIycjBgYjARKcmF1UQIcomIAMCjiQUROiugL0/RJ0Y0ZIAzf7" +
  "w3ZERQD//wB2/+0DRgZQACIAagAAAAMA0gOkAAD//wB2/+0DRgZQACIAagAAAAMA0wOkAAD//wB2/+0DRgXwACIAagAAAAMAzwOk" +
  "AAD//wB2/+0DRgZQACIAagAAAAMA0QOkAAAAAQAGAAADhwQ9AAYAAAEzASMBMwEC65z+pMn+pKEBIgQ9+8MEPfxXAAEAJwAABa4E" +
  "PQAMAAABMwEjAwMjATMTEzMTBSCO/umx+vyy/umT5Pey9AQ9+8MDnfxjBD38bgOS/HIAAAEAAwAAA1gEPQALAAABASMBASMBATMT" +
  "EzMCBgFSqf78/vykAU/+tan+/qQCJf3bAa3+UwIjAhr+YAGgAAEABv5IA4cEPQAIAAABMwEjEyMBMwEC65z+F5iOMv6koQEfBD36" +
  "CwG4BD38TP//AAb+SAOHBlAAIgByAAAAAwDSA4wAAP//AAb+SAOHBfAAIgByAAAAAwDPA4wAAAABADMAAALeBD0ACQAANyEVITUB" +
  "ITUhFeIB/P1VAfH+GQKXfn5dA2J+XQACADECUwKPBdcAHAAnAAAAFhYVESMnIwYGIyImJjU0Njc3NTQmIyIHNTY2MxI2NzUHBgYV" +
  "FBYzAb+LRXYLCSVzR0hvPpKfoWBqYHEzfTkzXSKVWlZOSAXXPIhz/cJfNzc7bEh4gw0PU2RQJXcRFPzsLzTWDgdMRUpJAAIANwJT" +
  "AuUF1wALABsAABImNTQ2MzIWFRQGIz4CNTQmJiMiBgYVFBYWM+qzs6Sks7OkQFYwL1dAQFcvMFZAAlPc5ufb3eXl3XE8lIGClDs7" +
  "lIKBlDwAAgBg/+0D3AXbAAsAGwAABAIREBIzMhIREAIjNjYSNTQCJiMiBgIVFBIWMwFE5OPb2+Pk2l9/RUV/X16ARUWAXhMBZQGS" +
  "AZIBZf6b/m7+bv6bh3MBEujrARR0c/7u6Ov+7HQAAAEAEQAAAbwFzQAGAAABMxEjEQU1AWBcmv7vBc36MwUJxpYAAAEAHgAAAx0F" +
  "2wAXAAAlFSE1ATY2NTQmIyIHNTY2MzIWFRQGBwEDHf0SAW1ZToyOkHs1nUnJ21Nn/tGJiVgCQ43LXop4NokYHbfDc+mh/iUAAQAq" +
  "/+0DOgXbACcAAAAWFRQGBiMiJzUWFjMyNjU0JiMjNTMyNjU0JiMiBzU2NjMyFhUUBgcCnJ5y1pOlkEifSZ6ssbR9RrO8kJKVfzae" +
  "TdHain8C38OWgrhfM4MaGpCNjpyDnIl/fDaDGB2/tIK+JwAAAQAsAAAD7QXIAA4AAAEVIxEjESE1ATMBIRMzEQPtvY79igHzmf4h" +
  "AckVeQHkfv6aAWZYBAr8HAHw/hAAAQBE/+0DUgXIABkAAAAEFRQGIyInNRYWMzI2NTQmJicnEyEVIQMXAlIBAPTkqY1JoEqio1a+" +
  "nZkuAnb+FiFAA0DVztPdNIMZHJWUZoNHCgkC7YT+EQQAAAIAbv/tA8EF2wAaACgAAAAWFhUUBgYjIgIREAAhMhYXFSYjIgYCBzY2" +
  "MxI2NjU0JiMiBgceAjMCorVqaLVy0/EBHgEUPnUuY36Hs14BNZ1YSnJDmX5OkDMGToBYA1JewI2Px2QBSgF+AacBfxMUhSh6/uzk" +
  "NDn9GkCKap2XODu/3VkAAAEACQAAAv8FyAAGAAATIRUBIwEhCQL2/iqfAc79sQXIWPqQBT8AAwBQ/+0D7AXbABwAKwA6AAAAFhYV" +
  "FAYGIyImJjU0NjcmJjU0NjYzMhYWFRQGBwAWFhcWFzY2NTQmIyIGFQA2NTQmJicmJwYGFRQWMwM9eTZuzIqW1G6NfXdqZr+Cf71m" +
  "d3P+ODiJfQsJcWWThIKPAaefOol+IydteKKgAsRriVx0smFerniBzjZArnpzrF5bqXJ3vj8BIm1XKQMEPJRufYeIdvwEiXtUb1Mo" +
  "Cw8srHGFjgAAAgAu/+0DgQXbABoAKAAAABIREAAhIiYnNRYzMjYSNwYGIyImJjU0NjYzEjY3LgIjIgYGFRQWMwKQ8f7i/uw+dS5j" +
  "foezXgE1nVhxtWpotXJnkDMGToBYR3JDmX4F2/62/oL+Wf6BExSFKHoBFOQ0OV7AjY/HZP0ZODu/3VlAimqdlwAAAQCG/3gChgNk" +
  "AAoAAAUzFSE1MxEHNTczAcy6/gPEx/hOF3FxAt2QerQAAQBN/3gCaANtABcAAAUVITUTNjY1NCYjIgc1NjYzMhYVFAYHAwJo/fL7" +
  "PjdfYmZWJ205kZ49SMQXcUkBfV6CO1dOJG8RE3+HTJ5r/tcAAQBJ/2sCegNtACYAAAAWFRQGIyInNRYWMzI2NTQmIyM1MzI2NTQm" +
  "IyIHNTY2MzIWFRQGBwIObLWhcmkzcDRsc3V3Y0F0e2JkalcmcTiWnV5XAWqDZYaRImwSElpaWWBtYVVQTiVrEROCe1l+GQABAB//" +
  "eAKxA2AADgAAJRUjFSM1ITUBMwEhEzMRArF8cv5cAUV9/ssBFxtXyWfq6kkCtf1pAUX+uwAAAQCGAmgChgZUAAoAAAEzFSE1MxEH" +
  "NTczAcy6/gPEx/hOAtlxcQLdkHq0AAABAEkCWwJ6Bl0AJgAAABYVFAYjIic1FhYzMjY1NCYjIzUzMjY1NCYjIgc1NjYzMhYVFAYH" +
  "Ag5staFyaTNwNGxzdXdjQXR7YmRqVyZxOJadXlcEWoNlhpEibBISWlpZYG1hVVBOJWsRE4J7WX4Z//8Ahv94AoYDZAACAIIAAP//" +
  "AE3/eAJoA20AAgCDAAD//wBJ/2sCegNtAAIAhAAAAAH+x/94AhwGUAADAAAFATMB/scC0YT9L4gG2Pko//8Ahv94BhgGVAAiAIYA" +
  "AAAjAIsCzQAAAAMAgwOwAAD//wCG/3gGYQZUACIAhgAAACMAiwLNAAAAAwCFA7AAAP//AEn/eAZhBl0AIgCHAAAAIwCLAs0AAAAD" +
  "AIUDsAAAAAEAHgNGA08GUAAYAAABFxcHJycHByc3NycnNxcXJzUzFQc3NxcHAe6KX15gY2JgX2CJxpokmbkYdRi5mCWaBKOVg0WD" +
  "sbGDRYOVKDJvM1XKoqLKVTNvMgABAAD/EAH5BlAAAwAABQEzAQFk/pyVAWTwB0D4wAABAF4BwQE7Ap4ACwAAEiY1NDYzMhYVFAYj" +
  "mz09MTI9PjEBwTwyMj09MjI8AAEAXgFAAj0DIAAPAAAAJiY1NDY2MzIWFhUUBgYjAQtuPz9uQkNuPz9uQwFAPm5ERG4+Pm5ERG4+" +
  "AP//AF7/8wE7BEoAIgCZAAAABwCZAAADegABAF7+xAE7ANAADwAAJBYVFAYHIzY2NyYmNTQ2MwEAOzUtWyEjBC46OzDQSEljw1VZ" +
  "kEYCPTAzOwD//wBe//MERADQACIAmQAAACMAmQGFAAAAAwCZAwkAAAACAHL/8wFPBcgABQARAAATAxEzEQMCJjU0NjMyFhUUBiOw" +
  "IaMgYz09MTE+PjEBdQIhAjL9zv3f/n47MTE9PTEwPAACAHL+hAFPBEoACwARAAAAFhUUBiMiJjU0NjMDMxMRIxEBET49MjE9PTEw" +
  "YiCjBEo8MjE+PTIyPP57/eH93gIiAAACAFoAAAPDBcgAGwAfAAABIwMzFSMDIxMjAyMTIzUzEyM1MxMzAzMTMwMzARMjAwPDwRrb" +
  "5Sd9J9MnfSe3wRrb5Sd9J9MnfSe3/qga0xoDfP7QfP4wAdD+MAHQfAEwfAHQ/jAB0P4w/lQBMP7QAAEAXv/zATsA0AALAAAWJjU0" +
  "NjMyFhUUBiObPT0xMj0+MQ08MjI9PTIyPAAAAgAg//MC7AXbABYAIgAAAT4CNTQmIyIHNTY2MzIWFRQGBgcDIxAmNTQ2MzIWFRQG" +
  "IwEPe489kZKUfzaeTtDaRZR5D2E+PTExPj4xAwMrZHpSf3w2gxgdv7RmnHw1/rT+ijwwMT09MS89AAIANP5wAwAESgALACAAAAAW" +
  "FRQGIyImNTQ2MxMOAhUUITI3FQYGIyImNTQ2NxMzAfY+PTEyPT4xS3qPPgEjlH82nk3Q2560D2IESjwwMTw8MS89/PArYnlP9DaC" +
  "GB29rpTMTQFM//8AaQOWAjkGUAAiAJ0AAAADAJ0BLwAAAAEAaQOWAQoGUAADAAATAzMDiyKhIgOWArr9Rv//AF7+xAE7BEoAIgCU" +
  "AAAABwCZAAADegABAAD/EAH5BlAAAwAAFQEzAQFklf6c8AdA+MAAAQBX/4IDbgAAAAMAABc1IRVXAxd+fn4AAQAe/jQCkQZkACYA" +
  "AAAGBxYWFREUFjMzFQYjIiY1ETQmIyM1MzI2NRE0NjMyFxUjIgYVEQFkSU5OSVlbeUJGnaBQSxMTS1CgnUZCeVtZAvlyFhdxW/3Y" +
  "Wld2C56bAilOTX9OTgHfm54Ldlda/iIAAAH/2/40Ak4GZAAlAAABFSMiBhURFAYjIic1MzI2NRE0NjcmNRE0JiMjNTYzMhYVERQW" +
  "MwJOFEtPoZ1HQHhcWUlOl1lceEBHnaFPSwKwf01O/debngt2V1oCKFtxFyu4Ad5aV3YLnpv+IU5OAAEApP5IAmkGUAAHAAATESEV" +
  "IREhFaQBxf7TAS3+SAgIfvj0fgAAAf/b/kgBoAZQAAcAAAM1IREhNSERJQEt/tMBxf5IfgcMfvf4AAABAGr+SAInBlAACQAAFhEQ" +
  "ATMAERABI2oBJJn+4wEdmQYCUgJSAbL+QP28/bz+QAABAB3+SAHZBlAACQAAJBEQATMAERABIwE6/uOZASP+3ZkIAkQCRAHA/lD9" +
  "rP2s/lAAAAEAAAH5BkACbQADAAARNSEVBkAB+XR0AAEAAAH5AyACbQADAAARNSEVAyAB+XR0AAEAfwHyAjwCcwADAAATNSEVfwG9" +
  "AfKBgQD//wB/AfICPAJzAAIAqQAA//8AYQCJAwcD3AAiAK0AAAADAK0BUQAA//8AOQCJAt8D3AAiAK4AAAADAK4BUQAAAAEAYQCJ" +
  "AbYD3AAFAAAlAxMzAxMBH76+l7+/iQGqAan+V/5WAAEAOQCJAY4D3AAFAAA3EwMzEwM5vr6Wv7+JAaoBqf5X/lYA//8AXgREAn0G" +
  "UAAiALEAAAADALEBQgAA//8AXgRRAn0GXQAiALIAAAADALIBQgAAAAEAXgREATsGUAAOAAAAFhUUBiMiNTQ2NzMGBgcBATo6LHc1" +
  "LFsgIwQFHz0wMjyRYsRVW49FAAEAXgRRATsGXQAPAAAAFhUUBgcjNjY3JiY1NDYzAQA7NS1bISMELjo7MAZdSEljw1VZkUUCPTAz" +
  "OwABAEv/EALOBS0AHQAAAAYGFRQWFjMyNxUGBxUjNSYCERASNzUzFRYXFSYjAbyMRkB+Y1JxVVKDrK2uq4NaTVNPA8lOuKCkvVAm" +
  "hB4G4OEWAQkBDgEBAQge6N8CE4UVAAACAD0BFAPgBLQAIwAzAAABFwcnJwYjIicHByc3NyY1NDcnJzcXFzYzMhc3NxcHBxYVFAcG" +
  "NjY1NCYmIyIGBhUUFhYzA3tjXWBGVXh3VkVgXWNbODhbZV5gR1R4d1ZHYF5lXDk40WQ4NGNEQmQ4OGNBAdJgXmRYQUBXZF5gR1Z1" +
  "dFZIYF5kWUBAWWReYEhVdXVWIjhrSkVsPDlrSUlrOQAAAQA3/xADWwa4AC0AACQGBxUjNSMiJic1FjMgETQmJicnJiY1NDY3NTMV" +
  "MzIWFxUmIyARFBYWFxcWFhUDW6qgjgRHo0efkwE+Mm5fRp6kqaOOCEKONXaI/rQwaFpGp6jqzyDr3RwZiDUBDEtmSiEYN8KZnsof" +
  "6t0TEYgk/v9IYkggGDnFnQABAFb/EAQMBrgAIQAAAREGIyMVIzUmAhEQEjc1MxUzMhcVJiMiBgIVFBIWMzI3EQQMlXwkjvv4/vWO" +
  "AZOJho6k1W9v265IQgLQ/T0a4/ApAWEBWQFiAWcl590niSh0/u3r5v7zcwkCTAAAAQBIAAAEFAXbABoAACUVITUzESM1MxE0NjMy" +
  "FhcVJiMiBhURIRUhEQQU/DTDw8P17kOPNXaIsKQBwf4/h4eHAih+AQPT2BMRiCSJl/76fv3YAAH/9AAABD4FyAAWAAABATMVIRUh" +
  "FSERIxEhNSE1ITUzATMBAQQ+/lv3/tcBKf7Xmv7XASn+1/f+WaYBhAGEBcj9Im3ibf7SAS5t4m0C3v1cAqQAAAEAfwFqA38EhgAL" +
  "AAABESE1IREzESEVIREBvP7DAT2FAT7+wgFqAU9+AU/+sX7+sQAAAQBpAX8DWwRxAAsAABMnAQE3AQEXAQEHAcFYASH+31gBIQEg" +
  "Wf7fASFZ/uABf1kBIAEgWf7fASFZ/uD+4FkBIQAAAwB/ATUDfwS7AAsADwAbAAAAJjU0NjMyFhUUBiMBNSEVACY1NDYzMhYVFAYj" +
  "AdE5OS4tOTkt/oADAP5SOTkuLTk5LQPuNy8uOTkuLjj+y35+/nw3Ly84OS4uOAACAH8B9gN/A/oAAwAHAAATNSEVATUhFX8DAP0A" +
  "AwADfH5+/np+fgAAAQB/AWgDfwSIAAYAABMBFQE1AQF/AwD9AAJ8/YQEiP62jP62hAEMAQwAAQB/AWgDfwSIAAYAAAEVAQEVATUD" +
  "f/2EAnz9AASIhP70/vSEAUqMAAIAfwABA38EagALAA8AAAERITUhETMRIRUhEQE1IRUBvP7DAT2FAT7+wv4+AwABTgFPfwFO/rJ/" +
  "/rH+s35+AAABAH8CewN/A2wAGAAAACYnJiYjIgYHNTY2MzIWFxYWMzI2NxUGIwKAWD04QyM9ZC0kaUAxWT42RCM8ZC5LgwJ7IB8c" +
  "GTU3jC4vIB8bGjU3jF0AAQB/AL8EYgM3AAUAACURITUhEQPd/KID478B+n79iAABAHb+SANGBD0AFQAAAREjJyMGBiMiJxEjETMR" +
  "FBYzMjY3EQNGgAwKM4JIbDmYmF1UQIcoBD37w3ZERUD+GwX1/RJ0Y0ZIAzcAAAUAVP/uBjQF2wAJAA0AGQAjAC8AABImNRAhIBEU" +
  "BiMTATMBAjY1NCYjIgYVFBYzABE0NjMyFhUQITY2NTQmIyIGFRQWM/ikATgBN6STZAIlg/3bkF5dWFheXlgCOaSTlKT+yFheXlhY" +
  "Xl5YAj/c8gHO/jLy3P3BBcj6OAKtnsDCn57Awp/9QQHO8tzc8v4ybp/Awp+fv8KgAAACAFb+NAYnBdoARQBQAAAAABEUAgYjIiYn" +
  "IwYGIyImJjU0Njc3NTQmJiMiBgc3NjYzMhYWFREUFjMyNjUQAiQjIgQCERASBDMyNjcVBiMgJAIREAAhEjY3EQcGBhUUFjMErwF4" +
  "U49dUmoWCiuNVlaESa23yTRnUzmFPgE5lkJ8oFEvNEthjf7yzM3+8o+SAR3eWKVYpbD+/v6mtgGBAW4hdiy+bmhdVwXa/kH+HMz+" +
  "+3hLREhHRYVdkp8SFm9ZZisXF4IVGUiiiP4bSUXV+AEwAWmcof6G/sD+uv6EoRwddjfDAbEBYAIDAc/6kT5GARUTDGNbX10AAAIA" +
  "d//sBSMF2wApADQAAAUnBgYjIiYmNTQ2NyYmNTQ2MzIXFSYjIgYVFBYWFwE2NTQnMxYWFRQHFyQ3ASYnBhUUFhYzBMvcQdWLktVw" +
  "dGkvKfLsYGZbZKehJVlRAVoJI4YREB/z/hJa/oFFLopOlGcUwV9gaL+Agsk8RYdOzNkXiBeOjUNudkv+0ThEjIA/iz98ZdULlwFQ" +
  "PjNntmGOTAACAFAAAAO5BdgACwAPAAABBiMgERA2MzIXESMzETMRAks+J/5qxs5rdXn2eAHqBQH4AQT3EPo4Bcj6OAACAF3/7QL/" +
  "BdkALwA/AAAABxYWFRQGBiMiJzUWMzI2NTQmJycmJjU0NjcmNTQ2NjMyFxUmIyIGFRQWFxcWFhUFFhc2NTQmJycmJwYVFBYXAv9Z" +
  "IR5ZqXZ/dYRvc3dHS3h9cjEtRViremxlYWh8eURKd4Nx/u8vJjpNT3cyGz5JTgI5ViRdPGGNSyZ8J15ZS1EVHyKOcz9sKkV2XIxP" +
  "Fn0XZE9ETxUgI493dA0ROVJOVxYgDgw7U0hXFgADAFb/6gYqBd4ADwAfADcAAAQkAjU0EiQzMgQSFRQCBCM2JBI1NAIkIyIEAhUU" +
  "EgQzLgI1NDY2MzIXFSYjIgYVFBYzMjcVBiMCYv6uuroBUt7eAVK6uv6u3sABIJ2d/uDAwP7gnZ0BIMBOtGNkvoVmWmFWlJiShmBr" +
  "W3wWvgFZ4+MBWb6+/qfj4/6nvmqiASnFxQEpoqL+18XF/tei8F63hIK5YBpzGZGTlJQlcicAAAQAdQEMBTkF2gAPAB8ALQA1AAAA" +
  "BBIVFAIEIyIkAjU0EiQzEjY2NTQmJiMiBgYVFBYWMxIHFyMnIyMHIxEzMhYVBzI2NTQjIxUDigEVmpr+67Oz/uuamgEVs5vpf3/q" +
  "mpvqf3/qm+yCnWiVF2kCXMd7fulJRY55Bdqc/ui0tP7pm5sBF7S0ARic+4yB7p2e7oKC7p6e7YEB/yfm19cCUGFcazQ3bdgAAAIA" +
  "dQM3AxoF2QAPAB8AAAAmJjU0NjYzMhYWFRQGBiM+AjU0JiYjIgYGFRQWFjMBZppXV5phYZtXV5thQWc5OWdBQWY5OWZBAzdXmmBg" +
  "mldXmmBgmldrOGlFRmg4OGhGRWk4AAABAJD+SAEcBlAAAwAAExEzEZCM/kgICPf4AAIAkP5IARwGUAADAAcAABMRMxEDETMRkIyM" +
  "jANEAwz89PsEAwz89AABAGIC5AO7BcgABgAAASMBASMBMwO7lv7p/uqWAV+ZAuQCXv2iAuQAAv0iBSv/VAXwAAsAFwAAACY1NDYz" +
  "MhYVFAYjICY1NDYzMhYVFAYj/Vg2Ni0tNzctAT42Ni0tNzctBSs1LS02Ni0tNTUtLTY2LS01AAH9zwUo/qYF8wALAAAAJjU0NjMy" +
  "FhUUBiP+CDk5MzM4ODMFKDYvLzc3Ly82AAAB/TwE5P58BlAAAwAAAQMzE/36vpykBOQBbP6UAAAB/foE5P85BlAAAwAAARMzA/36" +
  "pJu9BOQBbP6UAAAB/UAE5P82BlAABgAAAyMDAyMTM8pziIhztI4E5AEf/uEBbAAC/XcE4P7+BmMADwAbAAAAJiY1NDY2MzIWFhUU" +
  "BgYjNjY1NCYjIgYVFBYz/gNZMzNZODhZMjJZODRAQDQ0QEA0BOAyWDc3WTIyWTc3WDJLQDY3QEA3NkAAAf0lBUL/UQX+ABcAAAAm" +
  "JyYmIyIGBzU2MzIWFxYWMzI2NxUGI/6ZPy4kNRosRiI4XSNBLCYzGSxHIjpcBUIWFhMTJSdyRBcWExMlKHNDAAAB/SUFWP9RBcQA" +
  "AwAAATUhFf0lAiwFWGxsAAH9nv5g/vgAFAATAAAEFhUUBiMiJic1FjMyNTQjIzUzFf6wSGRfKE8gRVBnaR5adFA/SFURD1EjU1e8" +
  "fgAAAv0QBnr/Zgc2AAsAFwAAACY1NDYzMhYVFAYjICY1NDYzMhYVFAYj/UY2Ni4vNjYvAV82Ni4vNjYvBnoyKywzMywrMjIrLDMz" +
  "LCsyAAH9VQZI/n0HZAADAAABAzMT/fmkn4kGSAEc/uQAAAH9+QZI/yAHZAADAAABEzMD/fmJnqMGSAEc/uQAAAH9MQZI/0UHZAAG" +
  "AAADIycHIxMzu3iSk3fDjgZI2toBHAAC/XcGP/7+B8IADwAbAAAAJiY1NDY2MzIWFhUUBgYjNjY1NCYjIgYVFBYz/gNZMzNZODhZ" +
  "MjJZODRAQDQ0QEA0Bj8yWTc3WDIyWDc3WTJLQDc2QUE2N0AAAf0XBoP/Xwc5ABcAAAAmJyYmIyIGBzU2MzIWFxYWMzI2NxUGI/6g" +
  "QjIsNRwvRyI5YCZCMik3HS5IIjdiBoMVFRMRIyZvQhUVExIjJm5CAP//AYQE5ALDBlAAAwDSA4oAAP//ASj+YAKCABQAAwDXA4oA" +
  "AP//AKwFKwLeBfAAAwDPA4oAAP//AMYE5AIGBlAAAwDRA4oAAP//AK8FWALbBcQAAwDWA4oAAAABAAAA4wBUAAoAYgAFAAEAAAAA" +
  "AAAAAAAAAAAABAACAAAAZwBnAIMAjwCbAKcAswC/AMsA8wE1AWUBqwHZAhECKQI1AkECTQJZAm8CngK1AsECzQLZAuUC8QMHAyMD" +
  "MgNOA2UDcQOcA6gDtAPAA8wEEQQdBEYEcQSoBNwFGgUsBU0FWQVlBXEFfQWRBbEF0AXpBfUGCgZLBlcGYwZvBnsGhwaTBvIHIgdK" +
  "B4oHvQf+CDEIPQhJCFUIYQiECMYI6Aj0CQAJDAkYCSQJMAk8CVMJbwl7CbEJ0wnfCgwKGAokCjAKPAqBCo0KwAr0CyYLQwt8C9AL" +
  "9QwYDCQMMAw8DEgMXAx6DJgMrwy7DMcM3A0ZDUQNdg2IDbAN6Q4HDjMOdQ6IDuIPJA85D2APlw+0D8oQARAJEBEQGRAoEDgQSBBY" +
  "EIQQkxCpEMYQ0hDvEP8RIBFBEXgRjhHDEfYSAhIQEhwSKhI2Em4SpBK3EsoS4hL7EwcTExMgEygTNBNAE1ITZBNwE3wTlxO0E7QT" +
  "5BQ0FHcUrBTVFP8VGBU5FWcVexWQFaQVxBXtFf0WIhZvFusXOxdZF7YYDhhiGJQYoRi1GMkY7xkGGRUZJBk2GWIZihmXGbYZ3Bnr" +
  "GfoaCxo3Gl8aaBpxGnoagxqMAAEAAAACAAAnEH9NXw889QADB9AAAAAA1IKpfgAAAADUthod/Pr+Lgj8CGUAAAAHAAIAAAAAAAAE" +
  "BAC/AaUAAASXABEElwARBJcAEQSXABEElwARBJcAEQSXABEGWAARBGoAkAPPAFYDzwBWBLIAkASy//0D4gCQA+IAkAPiAJAD4gCQ" +
  "A+IAkAO4AJAEgABWBOsAkAG5AJABuQCQAbn/0wG5/7IBuf/3Abn/7gREAJADoQCQBiYAlAUDAJAFAwCQBMkAVgTJAFYEyQBWBMkA" +
  "VgTJAFYEyQBWBMkAVgRJAJAEUwCQBMkAVgSKAJADkwA3BAoABwTTAIgE0wCIBNMAiATTAIgE0wCIBHoAAwcwACoEbQAKBAr/3QQK" +
  "/90D4QAyA30ARAN9AEQDfQBEA30ARAN9AEQDfQBEA30ARAWPAEQDxAB/AuQASwLkAEsDxABLA7kASwN4AEsDeABLA3gASwN4AEsD" +
  "eABLAmEACAPEAEsDzgB/AZYAXwGWAH8BlgB/AZb/0AGW/7IBlv/MAZb/3QGW/90DhAB/AZUAfwXZAH8DzgB/A84AfwO5AEsDuQBL" +
  "A7kASwO5AEsDuQBLA7kASwO5AEsDxAB/A8QAfwPEAEsCbgB/AvYAPwS4AAgChAAAA8UAdgPFAHYDxQB2A8UAdgPFAHYDjQAGBdUA" +
  "JwNYAAMDjQAGA40ABgONAAYDCQAzAuwAMQMcADcEPQBgAlUAEQNTAB4DewAqBBIALAOAAEQD7wBuAzcACQQ9AFAD7wAuAs0AhgLN" +
  "AE0CzQBJAs0AHwLNAIYCzQBJAs0AhgLNAE0CzQBJAOP+xwZ9AIYGfQCGBn0ASQNtAB4B+QAAAZkAXgKbAF4BmQBeAZkAXgSiAF4B" +
  "wQByAcEAcgQdAFoBmQBeAyAAIAMgADQCogBpAXMAaQGZAF4B+QAAA8YAVwJsAB4CbP/bAkQApAJE/9sCRABqAkQAHQZAAAADIAAA" +
  "ArsAfwK7AH8DQABhA0AAOQHvAGEB7wA5AtsAXgLbAF4BmQBeAZkAXgGlAAAC4ABLBB0APQOTADcEgABWBEIASAQ0//QD/QB/A8QA" +
  "aQP9AH8D/QB/A/0AfwP9AH8D/QB/A/0AfwTYAH8DxQB2BogAVAZ+AFYFIwB3BEkAUANbAF0GgABWBa0AdQOPAHUBrACQAawAkAQd" +
  "AGIAAP0iAAD9zwAA/TwAAP36AAD9QAAA/XcAAP0lAAD9JQAA/Z4AAP0QAAD9VQAA/fkAAP0xAAD9dwAA/RcDigGEASgArADGAK8A" +
  "AQAACAz+SAAACVD8+v7HCPwAAQAAAAAAAAAAAAAAAAAAAN8ABAPTAZAAAwAABRQEsAAAAJYFFASwAAACvAAyAosAAAAABQYAAAAA" +
  "AAAAAAADAAAAAgAAAAAAAAAASU1QQQDAACAgsggM/kgAAArGAggAAAABAAAAAAQ9BcgAAAAgAAMAAAACAAAAAwAAABQAAwABAAAA" +
  "FAAEAdYAAAAWABAAAwAGAC8AOQB+AP8gFCAZIB0gIiAmILL//wAAACAAMAA6AKAgEyAYIBwgIiAmILL//wAAAEgAAAAAAADgmeCT" +
  "4HDgb+AFAAEAFgAAADIAugF4AAAAAAAAAAAAAAAAAAEAlgCcAJgAtgDEAMYAnQClAKYAjwC6AJQAqQCZAJ8AkwCeAL8AvQC+AJoA" +
  "xQACAAoACwANAA8AFAAVABYAFwAcAB0AHgAfACAAIgApACsALAAtAC4ALwA0ADUANgA3ADkAowCQAKQAzgCgAOEAOgBCAEMARQBH" +
  "AEwATQBOAE8AVQBXAFgAWQBaAFwAYwBlAGYAZwBpAGoAbwBwAHEAcgB1AKEAzACiAMEAswCXALQAuAC1ALkAzQDIAOAAyQB2AKsA" +
  "wgCqAMoA4gDLAMAAiQCKAN4AwwDHAJEA3wCIAHcArACNAIwAjgCbAAYAAwAEAAgABQAHAAkADAATABAAEQASABsAGAAZABoADgAh" +
  "ACYAIwAkACgAJQC7ACcAMwAwADEAMgA4ACoAaAA+ADsAPABAAD0APwBBAEQASwBIAEkASgBUAFEAUgBTAEYAWwBgAF0AXgBiAF8A" +
  "vABhAG4AawBsAG0AcwBkAHQAqACnAAAAAAAFAEIAAwABBAkAAQAqAAAAAwABBAkAAgAOACoAAwABBAkAAwBMADgAAwABBAkABAA6" +
  "AIQAAwABBAkABgA2AL4ARQBuAGMAbwBkAGUAIABTAGEAbgBzACAAQwBvAG4AZABlAG4AcwBlAGQAUgBlAGcAdQBsAGEAcgAyAC4A" +
  "MAAwADAAOwBJAE0AUABBADsARQBuAGMAbwBkAGUAUwBhAG4AcwBDAG8AbgBkAGUAbgBzAGUAZAAtAFIAZQBnAHUAbABhAHIARQBu" +
  "AGMAbwBkAGUAIABTAGEAbgBzACAAQwBvAG4AZABlAG4AcwBlAGQAIABSAGUAZwB1AGwAYQByAEUAbgBjAG8AZABlAFMAYQBuAHMA" +
  "QwBvAG4AZABlAG4AcwBlAGQALQBSAGUAZwB1AGwAYQByAAAAAwAAAAAAAP+1ADIAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAH//wAP";
