/**
 * Inter Regular (Rasmus Andersson), recortada a los caracteres que
 * usa el ticket, en base64 para que jsPDF la pueda embeber en el PDF.
 *
 * Se elige en `ticketFuente.ts` (constante `FUENTE_ACTIVA`), donde estan las
 * mediciones de todas las candidatas.
 *
 * El .ttf de origen es la instancia wght=400 / opsz=14 de la variable
 * Inter[opsz,wght].ttf, fijada con `fontTools.varLib.instancer`.
 *
 * ARCHIVO GENERADO — no editar a mano. Para regenerarlo, desde la raiz del
 * repo (necesita `pip install fonttools`):
 *
 *   python -m fontTools.subset  *     backups/Inter/Inter-Regular.ttf  *     --unicodes="U+0020-007E,U+00A0-00FF,U+2013,U+2014,U+2018,U+2019, *                 U+201C,U+201D,U+2022,U+20A2,U+20B2,U+2026"  *     --layout-features="" --no-hinting --desubroutinize  *     --drop-tables+=DSIG,GSUB,GPOS,GDEF --name-IDs="1,2,3,4,6"  *     --notdef-outline  *     --output-file=client/src/assets/fonts/Inter-Regular.subset.ttf
 *
 * y despues volver a codificar el .ttf en base64 aca.
 *
 * El subset deja los 99 caracteres que el ticket puede imprimir: 17 KB.
 *
 * La tabla `name` NO se puede quitar: el parser de TTF de jsPDF la necesita y
 * revienta sin ella.
 *
 * Licencia: Copyright 2020 The Inter Project Authors. SIL Open Font License 1.1.
 */
export const INTER_REGULAR_BASE64 =
  "AAEAAAAMAIAAAwBAT1MvMnD5FDkAAD+4AAAAYFNUQVRWpEHxAABDnAAAAF5jbWFwyIdrgAAAQBgAAAH0Z2FzcAAAABAAAEOUAAAA" +
  "CGdseWb51qwMAAAAzAAAOTRoZWFkNxe0QgAAO+AAAAA2aGhlYRaEE80AAD+UAAAAJGhtdHi9I2ZkAAA8GAAAA3xsb2NhK8I6ngAA" +
  "OiAAAAHAbWF4cAD6APYAADoAAAAAIG5hbWUgqD5hAABCDAAAAWhwb3N0/qcAjAAAQ3QAAAAgAAoBSP5gA/gHQAADAA0AEQAVACEA" +
  "JwAxADUAOwBHAABBIREhARUhNSM3NSEVMwMRIREHIzUzAREhESMVMzUzFSM1JxUhNSMVJRUzNTM1IRUzFREjNTMnFSE1IzUnFSE1" +
  "IzUzNSEVMxUD+P1QArD+CAFA19f+wNjYAUBAwMD/AAFAwEBAwEABQED/AMCA/sCAQECAAUCAwAFAkJD+wHD+YAjg+ABAQH9BQAGA" +
  "/wABAMCAAcD/AAEAgECAwIBA4KCAQKBAQGABIGBA4ECggEBAYEBAYAAAAgA0AAAFUQXSAA0AEQAAcwEzASMBJiYnMwYGBwETNSEV" +
  "NAId3AIkyP7EHU03JDZPGv7NRgL9BdL6LgN0UvW+wPlM/IwBoKamAP//ADQAAAVRB3YGJgABAAAABwDWAGUBdP//ADQAAAVRB2kG" +
  "JgABAAAABwDSAL0BdP//ADQAAAVRB4oGJgABAAAABwDQASQBdP//ADQAAAVRB4oGJgABAAAABwDPAcsBdP//ADQAAAVRB4oGJgAB" +
  "AAAABwDYARsBdP//ADQAAAVRB/oGJgABAAAABwDbAZEAAAACADQAAAdtBdIADwATAABzASEVIREhFSERIRUhESMBEzUhFTQCzARi" +
  "/TQCnv1iAtf8c139goYCrgXSqP4UqP4SqAVX+qkBoJ6eAAMAtAAABMgF0gATAB0AJwAAcxEhMhYWFRQGBgcVHgIVFAYGIyUhMjY1" +
  "NCYmIyE1ITI2NjU0JiMhtAIQnMtjRG9BRotdZ9yw/p0BXq6TTItg/pgBSFCCTIeR/rIF0muzbWB9ShIOBFiidXC0aaiGYUt+TKA/" +
  "c01hhgAAAQB6/+wFaAXmACUAAEUiJAI1NBIkMzIeAhcjLgMjIgYCFRQSFjMyPgI3Mw4DAw+//tWrqwErv3HJoGsUvhBNb4ZJhth+" +
  "f9iFSYZvTRC+E2ugyRS5AVfs7QFXukJ/tXNNdFAoiP75v77++YcpT3VMcrSAQ///AHr+UwVoBeYGJgAKAAAABwDaAgT/9QACALQA" +
  "AAVMBdIAFQAZAABhITUhMjYSNTQCJiMhNSEyBBIVFAIEAREjEQKF/pgBXLbvdnXnrf6KAYPaATWlpv7C/gq+qIsBBLWzAQGKqLL+" +
  "s+fp/rG0BdL6LgXSAAEAtAAABEkF0gALAABzESEVIREhFSERIRW0A4z9MgKd/WMC1wXSqP4aqP4MqP//ALQAAARJB4oGJgANAAAA" +
  "BwDQAOEBdP//ALQAAARJB4oGJgANAAAABwDPAYgBdP//ALQAAARJB4oGJgANAAAABwDYANgBdP//ALQAAARJB3YGJgANAAAABwDW" +
  "ACIBdAABALQAAAQ5BdIACQAAcxEhFSERIRUhEbQDhf05AoP9fQXSqP4CqP18AAABAHr/7AV4BeYAJwAARSIkAjU0EiQzMh4CFyMu" +
  "AyMiBgIVFBIWMzI2NjUXITUhFRQCBAMVx/7UqKgBKL92zaJrFMQXTGmET4PWfn/aiX7Aazn+RQI8nv7tFLoBV+vtAVe6RoKzbEhy" +
  "UiuH/vnAvv76iGvFhgumo7n+8JUAAQC0AAAFPgXSAAsAAHMRMxEhETMRIxEhEbS+Aw6+vvzyBdL9fAKE+i4Cpv1aAAEAtAAAAXIF" +
  "0gADAABBESMRAXK+BdL6LgXSAP///8oAAAJcB3YGJgAVAAAABwDW/rYBdP//AAsAAAFyB4oGJgAVAAAABwDQ/3UBdP//ALQAAAIZ" +
  "B4oGJgAVAAAABwDPABwBdP///9IAAAJUB4oGJgAVAAAABwDY/2wBdAABAGT/7APdBdIAEQAARSImNTUzFRQWMzI2NREzERQGAiHF" +
  "+L6Mc3KMvvcU6NZQUIiPj4gEKPvY1ugAAwC0AAAFJwXSAAkAEAAUAABBNT4CNwEzAScBETMRAxcRIQE3AQE2M2VqOAG9+f2ECv4U" +
  "vgMDAtT95XYChgGqy0aAejwB4f1WAfzXBdL+Av6/Xf3KAvaU/HYAAQC0AAAEJAXSAAUAAHMRMxEhFbS+ArIF0vrWqAAAAQC0AAAG" +
  "hgXSAC0AAHMRIQEeAxcjPgM3ASERIxE0PgI3Mw4DBwEjAS4DJzMeAxURtAEOAW8NISUiDSoOIiUiDQFqAQ+7AQMDARAVLy0oDv6z" +
  "pf6uDiYtMBkSAgMCAgXS/FQhY3RzMS5xdWYiA6z6LgNTLnaChj9Fj4VuJPytA1Mja4ORSTiChXsx/K0AAAEAtAAABVMF0gAbAABz" +
  "ETMBHgIXIy4CNREzESMBLgInMx4CFRG04AJeGERPJhsJCAK+4v3kJUtgRyMFCAUF0vxHJXSSU1adhC4DkvouA1A7fat+b7yMKPyu" +
  "//8AtAAABVMHaQYmAB4AAAAHANIA/wF0AAIAev/sBaQF5gAPAB8AAEUiJAI1NBIkMzIEEhUUAgQnMjYSNTQCJiMiBgIVFBIWAxC/" +
  "/tWsrAErv78BKqur/ta/hdd/f9eFhth/f9gUuQFX7O0BV7q6/qnt7P6pubCHAQe+wAEHh4j++b++/vqIAP//AHr/7AWkB3YGJgAg" +
  "AAAABwDWALMBdP//AHr/7AWkB2kGJgAgAAAABwDSAQsBdP//AHr/0gWkBgAGJgAgAAAABwDcAMIAAP//AHr/7AWkB4oGJgAgAAAA" +
  "BwDQAXIBdP//AHr/7AWkB4oGJgAgAAAABwDPAhkBdP//AHr/7AWkB4oGJgAgAAAABwDYAWkBdAABALQAAASuBdIAFwAAcxEhMhYW" +
  "FRQGBiMhNSEyNjY1NCYmIyERtAH+ruFtbeCu/pcBYHaQQUGRd/7KBdJ/1oWF2ICnUY1YWItQ+tUAAwB6/3QFpAXmAAcAFwAnAABB" +
  "MxcXEyMnJwciJAI1NBIkMzIEEhUUAgQnMjYSNTQCJiMiBgIVFBIWAtLGpir4xqIqvr/+1aysASu/vwEqq6v+1r+F139/14WG2H9/" +
  "2AHS2jr+tto4mrkBV+ztAVe6uv6p7ez+qbmwhwEHvsABB4eI/vm/vv76iAAAAgC0AAAE6AXSABcAGwAAcxEhMhYWFRQGBiMhNSEy" +
  "NjY1NCYmIyERIQEzAbQB/q7hbW3grv5rAYx2j0JCkHf+ygKa/pjWAW4F0nfQhYXMc6lFf1dZg0n61QKf/WEAAAEAdP/mBK4F5gAy" +
  "AABFIiYmJzMeAjMyNjY1NCYmJycmJjU0NjYzMhYWFyMmJiMiBgYVFBYWFxceAxUUBgYCkaHthgnDCGKZV2WhXlGGULS0yIjokJPi" +
  "gwS6DbaFYJFQYYU2lTyRhFV/8hpou31UbTVCeE9IWjoWMzO+lH69aGizcW13P21GTl81DykQOF2PaHrEcgABAGIAAATIBdIABwAA" +
  "UzUhFSERIxFiBGb+Lb4FKqio+tYFKgABALT/6AVABdIAFQAARSIkJjURMxEUFhYzMjY2NREzERQGBAL7sP75kL5fsHp6r16+kP77" +
  "GIrwmQPX/Dhrp2Bgp2sDyPwpmfCK//8AtP/oBUAHigYmACwAAAAHANABXQF0//8AtP/oBUAHigYmACwAAAAHAM8CBAF0//8AtP/o" +
  "BUAHigYmACwAAAAHANgBVAF0//8AtP/oBUAHdgYmACwAAAAHANYAngF0AAEANAAABVEF0gANAABhATMBFhYXIzY2NwEzAQJY/dzI" +
  "ATsbUTYlNlAaATPK/eIF0vyMTP66v/lMA3T6LgAAAQA0AAAHrgXSACUAAGEBMxMeAhcjPgI3EzMTHgIXIz4CNxMzASMBJiYnMwYG" +
  "BwMByv5qwuwTIiAOFw8gJBPx2O8UIyIPGg8gJBLrxP5o3f8AGS4WKBYqHf8F0vxuSZebUlKbl0kDkvxuSZebUlKbl0kDkvouA7Bc" +
  "2Y6G02r8UAABADkAAAU8BdIAHwAAcwEVATMTHgIXIz4CNxMzATUBIwEuAiczDgIHATkCR/3a3NcwPTMgISAzPzDb1/3bAkHb/vsq" +
  "OjIfKR4zOyz++QNBjQMe/sRGYFxAP1xhRgE8/OqM/LgBej5ZWT47WVs//oYAAQA0AAAFOgXSAA8AAGERATMBFhYXIzY2NwEzAREC" +
  "WP3c3AEnMk0pTClOLwEm2/3cAmIDcP4fUZNwcpVNAeH8kP2eAP//ADQAAAU6B4oGJgA0AAAABwDPAcABdAABAHoAAASOBdIAFwAA" +
  "czUBNjY3FwYGIyE1IRUBBgYHJzY2MyEVggKaLWYzFVy6XP31BAz9cDBrNRVct1wCDoYD30OHQj4GA6iI/DFHjkU+BgOoAAACAFr/" +
  "5gPgBGwAJwA5AABFIiYmNTQ+Ajc+AjU1NCYmIyIGBgcnPgIzMh4CFREjNSMOAicyNjY1NQ4DBw4CFRQWFgHXaq1mTH+aTmR+PTRo" +
  "TlByRxKtK5KwVjiPhVexDBNUhkBkikgLSl9ZGkFxRDxoGlCabmB4RSIKDQ4iKQZGYTQySyc5ZnMwG1Cdg/0fmCdTOJ9OfUSbDRUQ" +
  "CwMIJ0tAOk4o//8AWv/mA+AGFgYmADcAAAAHAM8BNwAA//8AWv/mA+AGFgYmADcAAAAHANgAhwAA//8AWv/mA+AGAgYmADcAAAAG" +
  "ANbRAP//AFr/5gPgBhYGJgA3AAAABwDQAJAAAP//AFr/5gPgBpwGJgA3AAAABwDZAP0AAP//AFr/5gPgBfUGJgA3AAAABgDSKQAA" +
  "AQBa/+YG8wRsAFQAAEUiJiY1ND4CMyEHNiYmIyIGBhUVFBYWMzI2NjcXDgIjIiYmJxM+AjMyHgIVFSEiBgYVFBYzMjY2NRE0JiYj" +
  "IgYGByc+AjMyFhYXAyMOAwHYaq5mVoyoUgRUVA5CjmVlkk5WmmVDbE8Vrxp8uHR6wXwVHyV1n2RZrIxT+0VPh1ODZGSJRzNnTlBy" +
  "RxKtK5KwVkGYgyAjFBFSdIoaUJpuYIBLIT9trmZjn1tlfKxaJk05LVWBSVKSYAI1UnhBO4PWm0spVEBXWU59RAFfRWI0MksnOWZz" +
  "MCNra/1YL1M/JAACAJ7/6AR+BdIAFgAmAABFIiYmJyMVIxEzETM+AjMyFhIVFAIGJzI2NjU0JiYjIgYGFRQWFgKlaoJGExSutA4T" +
  "RIBtjNV5eNWnaY1HRo1qZ4xHSI0YSV0frQXS/dkeW0iM/v2xsv78jqFxv3V0u25ouXx8vmsAAgCe/l4EfgXSABYAJgAARSImJicj" +
  "ESMRMxEzPgIzMhYSFRQCBicyNjY1NCYmIyIGBhUUFhYCpWqCRhMOtLQOE0SAbYzVeXjVp2mNR0aNameMR0iNGEldH/2xB3T92R5b" +
  "SIz+/bGy/vyOoXG/dXS7bmi5fHy+awAAAQBo/+gELgRsACUAAEUiJgI1NBI2MzIeAhcHLgMjIgYGFRQWFjMyPgI3Fw4DAmWY5YCA" +
  "5ZhRkHdWF60MMkdcN3CQRkaQcDheSTIMrBZXeJIYkAEErK8BBZAqT3NJMStINR11vnBuvXQeN0wtMUt1Uyv//wBo/l4ELgRsBiYA" +
  "QQAAAAcA2gFbAAAAAgBo/+gESAXSABYAJgAARSImAjU0EjYzMhYWFzMRMxEjNSMOAicyNjY1NCYmIyIGBhUUFhYCQYvWeHnWi22A" +
  "RRIOtK4UEkeBUGaMSEeMZ2qNRkeOGI4BBLKxAQOMSFseAif6Lq0fXUmha758fLlobrt0db9xAAEAaP/oBEYEbAAnAABFIiYCNTQS" +
  "NjMyHgIVFSE1IQc0JiYjIgYGFRUUFhYzMjY2NxcOAgJ0out/fOOYWa2NVPycAwNURYhlZZBMVptmQmxOFa4afLcYkAECrKwBBpQ7" +
  "g9abS5g4bqthY59bZXytWSZNOTBUgEgA//8AaP/oBEYGAgYmAEQAAAAGANb+AP//AGj/6ARGBhYGJgBEAAAABwDQAL0AAP//AGj/" +
  "6ARGBhYGJgBEAAAABwDPAWQAAP//AGj/6ARGBhYGJgBEAAAABwDYALQAAAACABQAAALWBhgAAwAUAABBFSE1ExE0NjYzMhYXByYm" +
  "IyIGFRECpv1u3FuSUUBUFDIOLSZTTARempr7ogTzYYJCFQmaBQxVUfs1AAIAaP5GBEoEbAAlADUAAEEiJiYnNx4CMzI2NTUjDgIj" +
  "IiYmNTQ2NjMyFhYXMzUzERQGBgMyNjY1NCYmIyIGBhUUFhYCY3y1eCOSGEd5YoatERNFgWyG1nx614tsgUYTEa+C3Y1mjEhHjGdq" +
  "jkdIjv5GP2g9XiBON4CK4CBYQ3/0r63/jEdcHrP7hZC3VgJsXa96d7VnbbZwc7BjAAEAngAABB0F0gAWAABBESMRMxEjNjYzMhYW" +
  "FREjETQmIyIGBgFStLQfM71/catftYd1UIBKAp79YgXS/X2bgl27jv06AreBkkaGAP//AHwAAAF3BgMGJgBNAAAABgDXAgAAAQCe" +
  "AAABUgReAAMAAHMRMxGetARe+6L///+wAAACQgYCBiYATQAAAAcA1v6cAAD////xAAABUgYWBiYATQAAAAcA0P9bAAD//wCeAAAB" +
  "/wYWBiYATQAAAAYAzwIA////uAAAAjoGFgYmAE0AAAAHANj/UgAAAAH/5v5eAVMEXgAMAABTMxEWBgYjIzUzMjY1nbUBSpJtJCFO" +
  "SARe+1JqmFCmWVMA////5v5eAXYGAwYmAFIAAAAGANcBAAADAJ4AAARIBdIABgAKAA4AAEE1MwEzASMBETMRIQE3AQFHIQHe3/37" +
  "FP6StAIP/lSAAhMBkt8B7f3t/bUF0vouAiN//V4AAQCeAAABUgXSAAMAAEERIxEBUrQF0vouBdIAAAEAngAABmQEcgApAABzETMX" +
  "Iz4CMzIWFyM+AjMyFhYVESMRNCYjIgYGFREjETQmIyIGBhURnq8BDhdjhUh6lxYYFGqXWWGgX7SIWkttO7R8X0FzRgRe+lt3PJZ6" +
  "VHpCVKqC/Q4C7XloP25H/SYC/11yPXhZ/UAAAAEAngAABBwEbAAWAABBESMRMxMjNjYzMhYWFREjETQmIyIGBgFStK0BGTO9f3Gq" +
  "X7SHdVCASgKe/WIEXv7xm4Jdu479OgK3gZJGhv//AJ4AAAQcBfUGJgBXAAAABgDSWAAAAgBo/+gEZARsAA8AHwAARSImAjU0EjYz" +
  "MhYSFRQCBicyNjY1NCYmIyIGBhUUFhYCZZjlgIDlmJnmgIDmmXGSRkaScXCQRkaQGJABBKyvAQWQkP77r6z+/JChdL1ub791db5w" +
  "br10AP//AGj/6ARkBgIGJgBZAAAABgDWCAD//wBo/+gEZAX1BiYAWQAAAAYA0mAA//8AU//TBHcEiwYmAFkAAAAGAN0BAP//AGj/" +
  "6ARkBhYGJgBZAAAABwDQAMcAAP//AGj/6ARkBhYGJgBZAAAABwDPAW4AAP//AGj/6ARkBhYGJgBZAAAABwDYAL4AAAACAJ7+XgR+" +
  "BGwAFgAmAABTETMVMz4CMzIWEhUUAgYjIiYmJyMRATI2NjU0JiYjIgYGFRQWFp6uFBNEgG2M1Xl41YxqgkYTDgE4aY1HRo1qZ4xH" +
  "SI3+XgYAsx5bSIz+/bGy/vyOSV0f/bECK3G/dXS7bmi5fHy+awACAGj+XgRIBGwAFgAmAABBIxEjDgIjIiYCNTQSNjMyFhYXMzUz" +
  "ATI2NjU0JiYjIgYGFRQWFgRItA4SR4Fri9Z4edaLbYBFEhSu/hRmjEhHjGdqjUZHjv5eAk8fXUmOAQSysQEDjEhbHrP8K2u+fHy5" +
  "aG67dHW/cQABAJ4AAALVBG4AEwAAcxEzFTM2NjMyFhcVJiYjIgYGFRGergwfn2QUNxAIQCRQf0gEXqxVZwIBtQIIQ3VM/UQAAQBs" +
  "/+gD0wRsACsAAEUiJiYnNxYWMzI2NTQmJycmJjU0NjYzMhYWFwcmJiMiBhUUFhcXFhYVFAYGAhpzs3QUqxiFZHWLUVO6mJRsu3dz" +
  "oWUZoxdrbGSFWmKpmJJvxxhDhGApXFZkRTpNEywkl3Zgk1NFeU8qPGJcRj5LFygkl3NimVgAAQC0AAAEegXmACsAAHMRNDY2MzIW" +
  "FhUUBgcVFhYVFAYGIyM1MzI2NTQmIyM1MzI2NjU0JiMiBhURtG/FgH7HdH9rkbJsxYSlpXSLmoOBW0hpOYh2cJMEU321YV2seHyv" +
  "JQ4OxZp2umqnimtxkqpJdUJnj4Vq+7AAAgAU//ICdQVoAAMAEwAAQRUhNRMzERQWMzI2NxcGBiMiJjUCVv2+qLQ9RxE1FiUcRyOR" +
  "ogRempoBCvu6S0UIBJgKCpmJAAEAnv/yBB0EXgAWAABFIiYmNREzERQWMzI2NjURMxEjETMGBgIZcatftIh1UH9Kta4YNL8OXbyN" +
  "Asb9SYGSRodfAp77ogEPnYD//wCe//IEHQYCBiYAZgAAAAYA1gAAAAEAnv5eBKYEXgAlAABTETMRFBYWMzI2NjURMxEUFjMzFSMi" +
  "JjU1MxQOAiMiLgI1MxGetEl7S0x3RbQwPB0ki4oqPmFrLS1rYD4o/l4GAP1aaIQ9PoNoAqb8nzcrm4B7ZW+PUSEhUY9v/P4A//8A" +
  "nv/yBB0GFgYmAGYAAAAHANAAvwAA//8Anv/yBB0GFgYmAGYAAAAHAM8BZgAA//8Anv/yBB0GFgYmAGYAAAAHANgAtgAAAAEANgAA" +
  "BEkEXgANAABhATMTFhYXIzY2NxMzAQHh/lXF7iY1HUIdNSXuxf5VBF79aWfNYGDNZwKX+6IAAAEARgAABkYEXgAjAABhATMTFhYX" +
  "IzY2NxMzExYWFyM2NjcTMwEjAy4CJzMOAgcDAZn+rb+IHEAfHx4+HYbAhBw9HiAgPx2Iv/6ts5EWKigVKBQpKhaRBF7+GGT9oJn+" +
  "agHo/hhn/Z2b/WkB6PuiAfpNoKhXVqmiS/4GAAABAEEAAAQdBF4AGwAAcwEHATMXFhYXIzY2NzczATUBIycmJiczBgYHB0EBuQH+" +
  "X9KLNk8qXitHN47O/l0BtdGkNU0pXylGNqYCg4oCZdlUkkREklTZ/ZOF/Yr7Uo1BQY1S+wAAAQA2/lYESQReABoAAFM3FxY2Njc3" +
  "ATMTFhYXIzY2NxMzAQ4CIyImjC4TN1pIGyD+VcXuJjQdQh01JfDE/hUiX35PMEb+a5wFDg1MUF0EZP1paMxgYM1nApf6+1lzNw7/" +
  "/wA2/lYESQYCBiYAbwAAAAYA1uMA//8ANv5WBEkGFgYmAG8AAAAHAM8BSQAAAAEAfgAAA+0EXgALAABzNQE1ITUhFQEVIRV+AnP9" +
  "oQNH/Z8CdYYDJgunj/zjC6cAAAIAqAAABHIF0gADABkAAFMzESMTBTIWFhUUBgYjITUhMjY2NTQmJiMhqMDAWwGAoNxzc9yg/oAB" +
  "gGaNSEiNZv6ABdL6LgShAXXCdnfDdKY+dFJSeEEAAwBo/+gEQQYtAAMAHgAuAABBAScBASImJjU0NjYzMhYWFzMuAic3FhYSEhUU" +
  "AgYnMjY2NTQmJiMiBgYVFBYWA8f9pS8CWv6+lt55eMt8VH1WGBAhhN+qSX30yHd73ZNojEhBi3Bpi0VAiwWH/txuAST584rynJ7x" +
  "iDpVK1zSz1Z9PcL++/67wLT/AIigYqZmXrZ5a7BnYqxrAAIAdP8mBK4GrAADADYAAEURMxEnIiYmJzMeAjMyNjY1NCYmJycmJjU0" +
  "NjYzMhYWFyMmJiMiBgYVFBYWFxceAxUUBgYCVXg8oe2GCcMIYplXZaFeUYZQtLTIiOiQk+KDBLoNtoVgkVBhhTaVPJGEVX/y2geG" +
  "+HrAaLt9VG01QnhPSFo6FjMzvpR+vWhos3Ftdz9tRk5fNQ8pEDhdj2h6xHIAAAIAaAAABC4F0gADACkAAGERMxEnIiYCNTQSNjMy" +
  "HgIXBy4DIyIGBhUUFhYzMj4CNxcOAwIfdjCY5YCA5ZhRkHdWF60MMkdcN3CQRkaQcDheSTIMrBZXeJIF0vouppABBKyvAQWQKk9z" +
  "STErSDUddb5wbr10HjdMLTFLdVMrAAUAHgAABEoF0gADAAcACwAPABMAAFMBBwkCMwE3ESMRBRUhNQEVITXvAXeQ/kgB4gF40v5H" +
  "Ab0CAfy5A0f8uQXS/MhCA3r8yAM4/Ia2/PIDDiaIiP7giIgAAAMAbgAABHMF5gAbACcAKwAAdzUyNicDJjY2MzIWFhcHJiYjIgYG" +
  "FxMWDgMHNSEyNjU1MxUUBiMBNSEVbllNAxUEbc6Ocrd3Ea0ThWtffDoCFQI0VWBVGgMILiapfYb8/gMreC9mYQKsg9B5XKdxHGt+" +
  "TYJR/VZDWzgdCninJy0+L4WFAp6WlgACAHr/JgV4BqwAAwArAABFETMRJyIkAjU0EiQzMh4CFyMuAyMiBgIVFBIWMzI2NjUXITUh" +
  "FRQCBALHeCrH/tSoqAEov3bNomsUxBdMaYRPg9Z+f9qJfsBrOf5FAjye/u3aB4b4esa6AVfr7QFXukaCs2xIclIrh/75wL7++ohr" +
  "xYYLpqO5/vCVAAACAHr/7AVmBeYAFAA6AABBByYmIyIGBgcRIxEzFTM+AjMyFjcHLgMjIgYCFRQSFjMyPgI3Fw4DIyIkAjU0EiQz" +
  "Mh4CBQk9DS4lWn5EArKyDBBVdUEsTne9EE1vhkqF135+14VJhm9NEL4VbKDIcL7+1qurASq+cMigbAMxpgcQYZNK/v0C6L02XjoZ" +
  "vwNMdU8ph/75wL/++ocoUHVMA3O1fUG5AVfs7QFXukJ9tAACAHr/7ASSBeYADwAfAABFIiYCNTQSNjMyFhIVFAIGJzI2EjU0AiYj" +
  "IgYCFRQSFgKGpup8feqlpet8e+qnbZhQUJhtbZhQUJgUtAFV8/IBVra2/qry8v6qtKaOAQu9vgENjo/+9L69/vWOAAABAGAAAAKN" +
  "BdIABwAAQREjESMBNSUCjbsK/pgBRAXS+i4FIv71zO8AAQCaAAAETwXmAB8AAHM1AT4CNTQmJiMiBgYVIzQ2NjMyFhYVFAYGBwEV" +
  "IRWaAe9TbjhKflBVfUS2etKFhc11OpKE/roCr4kCGVqIe0VOcj1FfVSEyG9vvHVRmcKM/qUMpwABAH3/7AR3BeYANAAARSImJicz" +
  "HgIzMjY2NTQmJiMjNTMyNjY1NCYmIyIGBgcjPgIzMhYWFRQGBxUeAhUUBgYCe5LihQXABlWLVV6RVFGab3l5V4VKQXhRTIVVA7cE" +
  "hNmDi8lshXJfh0eE5hRksnZHZzdBdk1Re0alP3JNSm49N2ZJdbJkcLZqfrAiDA9ill56wG8AAgB4AAAEtQXSAAkADwAAUzUBMxUj" +
  "ARUhFQERNxEzEXgCjHNN/hkDcv6AAbUBL5sECO78/gyn/tEBXUkELPouAAEAgP/sBEUF0gAmAABFIiYmJzMeAjMyNjY1NCYmIyIG" +
  "BycTIRUhAzM2NjMyHgIVFAYGAlSD0HwFuAZOfUtajVBUkV5FjiyyWAMQ/ZAzCC6MTWatgEeB4BRns3JCaDtUlF5gmFcsIhYC4qf+" +
  "TSYxSoe2bI/ggQACAHr/7AR8BeYAIgAzAABFIiYmAjU0EjY2MzIWFhcjJiYjIgYGFTM+AjMyFhYVFAYGJzI2NjU0JiYjIg4CFRQW" +
  "FgKGXbqZXEuPyn99xn4SuhmMdHKlWAwocIpNgNR/fOKYWpBUUY5aRHVYMVKQFESgARLOxQEx021ksnVhgob9sz5ZL37fkIvjh6da" +
  "l11blVg1XXdBWJddAAEAYgAABCUF0gAHAABzATUhNSEVAcgClv0EA8P9awUfDKex+t8AAwB6/+wEeQXmAB8ALwA/AABFIiYmNTQ2" +
  "Njc1JiY1NDY2MzIWFhUUBgcVHgIVFAYGJzI2NjU0JiYjIgYGFRQWFhMyNjY1NCYmIyIGBhUUFhYCeZfngUyEU22Ads6Fg853gWpR" +
  "hE6D55ZjkE9UklxeklROkmRPekdEe1FSe0RFfBRrvHleoWwPCBy6dnKzZ2ezcna6HAgPbKFeebxrpUF1T1N/SUl/U091QQK/P3JL" +
  "S249PW5LS3I/AAIAev/sBHwF6QAiADMAAEUiJiYnMxYWMzI2NjUjDgIjIiYmNTQ2NhceAhIVFAIGBgMyPgI1NCYmIyIGBhUUFhYC" +
  "W3/GfhK8F4x2cqRZDChwiU6A1n9+45lcuJhcS47KbkR2WDJTj1xaj1RRjBRktHdjhIb+tD1ZMX/fj4vlhwMBRZ7+8M7G/s7TbQK/" +
  "Nl13QlaVXVmXXFuVWAABAGj/7AUHBeAAQAAARSImJjU0NjY3Nz4CNTQmIyIGBhUUFhYXASMBLgI1NDY2MzIWFhUUBgYHBQYGFRQW" +
  "FjMyPgI1MxQGBgcHBgYCRJPWc1CNWd0bQC1fUThWLzNYOAKu2f3LUH9JWqVucKJYM1k6/tZcS0Z+UlmkgkytRFcdJEnbFG25c2KO" +
  "ekKjFDhONEdcLlE2OGZuRPzAAqZhmZZZY5hWV5FZRHRiK91EdUVJbz5JiMB4lL5uHC1PTgAAAgCg//MBrQXSAAMADwAAUwMzAwMi" +
  "JjU0NjMyFhUUBswMzA1YOE9PODhOTgHfA/P8Df4UTzc4T084N08AAgCg/pcBrQR2AAMADwAAUxMzEwMiJjU0NjMyFhUUBsENswxn" +
  "N09PNzhPT/6XA/P8DQTSTzg4Tk44OE8AAgBS//MDsQXmACEALQAAQTU0NjY3NjY1NCYmIyIGBgcjPgIzMhYWFRQGBw4CFRUDIiY1" +
  "NDYzMhYVFAYBfzVkRUJaQW5EO21IBr4Fd8J2gr9qamFATyNYOE9PODhOTgHBC4mVVykoe1dGZTgxaFN+sF1lsnJ5rDsnSWhZC/4y" +
  "Tzc4T084N08AAAIAZv54A8UEawAhAC0AAEEVFAYGBwYGFRQWFjMyNjY3Mw4CIyImJjU0Njc+AjU1EzIWFRQGIyImNTQ2Apg1ZEVC" +
  "WkFvQzttSQW+BXfCdoHAamphQU4jWDhPTzg3T08CnQuIllYqKHtXRWY4MWhTfbFdZrFyeaw7KEhpWAsBzk44OE9PODhOAAABANr+" +
  "6QKLBi0AEAAAUzQSEjczBgICFRQSEhcjJgLaQ3RLr01xPDVvVq9/gwJfowFlAUt7nf6s/rWShf7w/tGy2QHCAAEAYP7pAhEGLQAQ" +
  "AABTNhISNTQCAiczFhISFRQCB2BZbjM8cE6vS3VChX3+6bcBMQEOgJIBSwFUnXv+tf6aot/+PtUAAQDi/ukCcAYtAAcAAFMRIRUj" +
  "ETMV4gGO4uL+6QdEmfnumQAAAQB7/ukCCQYtAAcAAFM1MxEjNSERe+LiAY7+6ZkGEpn4vAAAAwCQ/ukC7gYtABMAJwArAABTNTI2" +
  "NTU0PgIzFSYGFREUDgIBIi4CNTU0JiM1Mh4CFREUFjMBNTMVkHpgKVuVa39fHlKXAeVrlVspYHp5l1IeX3/9orMChl9lduZmlF8u" +
  "lwF1f/7iOV1EJfxjLV+UZ+R3Zl8mRV44/uR/dgKytrYAAAMAe/7pAtkGLQATACcAKwAAQSIuAjURNCYjNTIeAhUVFBYzATUyNjUR" +
  "ND4CMxUGBhUVFA4CAQc1FwLZeZdSHl6Aa5RbKWF6/aKAXh5Sl3l7YClblAHztLQChiVEXTkBHn51ly5flGbmdmX8BJV2fwEcOF5F" +
  "Jl8BZnbkZ5RfLQNIAbYBAAIAev51B0AFngBJAFkAAEEiJCYCNTQSNiQzMgQWEhUUDgIjIiYmJyMGBiMiJiY1NDY2MzIWFzM1MxEU" +
  "FjMyNjY1NCYmJCMiBAYCFRQSFgQzMjY2NxcOAgMyNjY1NCYmIyIGBhUUFhYEFN/+qOt4eukBTtTOATfSahZFiXQ0el0JCBqGcYWz" +
  "W2u7d2CBGwqeQ0BJTh5TqP8Araz+8rxiYsIBHLpQmXgdKy6RpZ5hdzc8d1dSdD4ycP51eusBV9zVAVLtfYXj/uKYa9ezbSBKPkBh" +
  "hOGNhtR7RiZU/W08WmTQo3zpum1pyP7htrj+4cVmHiUKjBMmGQJJTp12eIc3VY1UXKJjAAAEACIAAATtBdIAAwAHAAsADwAAYRMz" +
  "AwE3IQcBEzMDAzchBwLH9pf0/MIZBFwZ/D/0l/TaGQRaFwXS+i4Bm5aW/mUF0vouA5+YmAAABgB4/+wFVgTnABMAIwAnACsALwAz" +
  "AABFIi4CNTQ+AjMyHgIVFA4CJzI2NjU0JiYjIgYGFRQWFgEnNxcDJzcXBSc3FwMnNxcC4nzYo1xco9h8e9mkXV2k2Xt4w3Nzw3h3" +
  "xXV1xQIfdsh6esh2zPuYdsh6esh2zBRgq+SFheSqX1+q5IWF5atfon/Uf4HUfX3UgX/UfwMPfM58+4bOesx8fMx6At7OfM4AAQAu" +
  "/yACtAYYAAMAAEEBIwECtP4gpgHgBhj5CAb4AAABAQb+IAGjB7IAAwAAQREjEQGjnQey9m4JkgAAAgDA/ugBaQXSAAMABwAAUzMR" +
  "IxMRIxHAqampqQGT/VUG6v1ZAqcAAAEALv8gArQGGAADAABFATMBAg7+IKYB4OAG+PkIAAEAkAIpAx4CzwADAABBFSE1Ax79cgLP" +
  "pqYAAQAAAikEAALPAAMAAEEVITUEAPwAAs+mpgABAAACKQgAAs8AAwAAQRUhNQgA+AACz6amAAEBAAESA4ADkgAPAABBIiYmNTQ2" +
  "NjMyFhYVFAYGAkBYklZWklhZkVZWkQESVpJYWZFWVpFZWJJWAAABAKADmwHGBdIAAwAAUxMzA6CcilgDmwI3/ckAAQCgA5sBxgXS" +
  "AAMAAFMTMwOgWM6cA5sCN/3JAAEA0gObAZQF0gADAABTAzMD6BbCFgObAjf9yf//ANIDmwLoBdIEJgCdAAAABwCdAVQAAP//AKAD" +
  "mwM2BdIEJgCbAAAABwCbAXAAAP//AKADmwM2BdIEJgCcAAAABwCcAXAAAP//AID+mQGmANAEBwCc/+D6/gABAKD/8wGuAQEACwAA" +
  "RSImNTQ2MzIWFRQGASc4T084OE9PDU84OE9PODhP//8AoP/zBkoBAQQmAKIAAAAnAKICTgAAAAcAogScAAD//wCg//MBrgQqBiYA" +
  "ogAAAAcAogAAAyn//wCA/pkBygQqBCcAnP/g+v4ABwCiABwDKf//AKACPQGuA0sGBwCiAAACSgABAGQAkALDBEAABQAAZQEBMwEB" +
  "AfX+bwGRzv52AYqQAdgB2P4o/igAAQBQAJACrwRAAAUAAHcBATMBAVABiv52zgGR/m+QAdgB2P4o/igA//8AZACQBFkEQAQmAKcA" +
  "AAAHAKcBlgAA//8AUACQBEUEQAQmAKgAAAAHAKgBlgAAAAEArgAsBF4EYgAJAABTNQEVATcVJwEVrgOw/TIGBgLOAgh+AdzE/qsM" +
  "HAr+q8IAAAEA7QAsBJ0EYgAJAABBATUBBzUXATUBBJ38UALPBwf9MQOwAgj+JMIBVQocDAFVxP4kAAACAOIBGwRqA3MAAwAHAABT" +
  "NSEVATUhFeIDiPx4A4gCzaam/k6mpgAAAgDDAGQEiAQqAAMABwAAZREzEQE1IRUCUan9yQPFZAPG/DoBlJ+fAAIA0gBwBH4EHgAD" +
  "AAcAAGUBNwEFJwEXBAr8yHQDOPzIdAM4dHADOHb8xnR0Azp2AAMA0gBIBHsERwADAA8AGwAAQRUhNQEiJjU0NjMyFhUUBgMiJjU0" +
  "NjMyFhUUBgR7/FcB0zdOTjc3TU03N05ONzdNTQKcqqr9rE43Nk1NNjdOAvZNODZOTjY4TQAAAwDOAEUEfgRhAAMABwALAAB3NSEV" +
  "ATUhFQERMxHOA7D8UAOw/dSpRaioAk2oqP7aAvX9CwAAAQCmAZAEpQMMABsAAFMmNjYzMhYXFhYzMjY1MxYGBiMiJicmJiMiBheo" +
  "AlOHSkp6UTVAJj5HpAJUhkpMfE02PyY6TAEBt3yWQz5HLiZaV3uWQ0FDLyVSXwAAAQDgATsEJALpAAUAAEERITUhEQN7/WUDRAE7" +
  "AQ+f/lIAAAEAAP9aA6YAAAADAABhFSE1A6b8WqamAAIAUgMuA3MFowADAAsAAEEzFSMBATMBIwMzAwHINDT+igEtxwEtsecP5QVQ" +
  "S/4pAnX9iwH1/gsAAQByAowDkAXSABEAAEETBSclJTcFAzMDJRcFBQclEwG5Df70SAEa/uZIAQwNkAwBC0j+5gEaSP71DAKMAT2r" +
  "fpKSgKsBPf7Dq4CSkn6r/sMAAAQAZAFaBPAF5gATACMAJwA9AABBIi4CNTQ+AjMyHgIVFA4CJzI2NjU0JiYjIgYGFRQWFjcnMxch" +
  "ESEyFhYVFAYGIyM1MzI2NTQmIyMRAqp406BbW6DTeHnToFpaoNN5esh3d8h6ecl3d8n1g4KF/jMBECJONzlRJcOfGTc4Fm4BWlug" +
  "03h406BbW6DTeHjToFuNd8h6esh3d8h6esh3rv7+AhglSzo7UypZLzAwI/4/AAADAKj/6QaoBekAHwAzAEcAAEE0NjYzMhYWFyMm" +
  "JiMiBgYVFBYWMzI2NzMOAiMiJiYBIiQmAjU0EjYkMzIEFhIVFAIGBCcyPgI1NC4CIyIOAhUUHgICAHTFd2ivcw6wD4VUSHhISHhI" +
  "VHUPsA1sp2h3xXQBqJ/+6tR3d9QBFp+fARbUd3fU/uqfe9ekXFyk13t716RcXKTXAuh4xHRZmGFKYEd4SUh3R19LYZpZdcT9eHfU" +
  "ARafnwEW1Hd31P7qn5/+6tR3rlyk13t716RcXKTXe3vXpFwAAgCCAz0DIwXeAA8AHwAAQSImJjU0NjYzMhYWFRQGBicyNjY1NCYm" +
  "IyIGBhUUFhYB1F2ZXFyZXVyYW1uYXDNUMjJUMzRVMjJVAz1amVxdmltbml1cmVqWMlQzNFQzM1Q0M1QyAAIAQwKHAykF6gAjADIA" +
  "AEEiJiY1NDY2Nz4CNTU0JiMiBgcnPgIzMh4CFREjNSMGBicyNjY1NQ4CBwYGFRQWAXJViVFnnlRQYy9YVldnFKEgc5FMNXhrRKYJ" +
  "GYJJSmg3DFReHU9qYQKHO3JSX2YtCQkLGx0ERExFLCdMXSoZP3Ja/dNzMlOGNVUwagsSCwQKOT46PQACAE4CiAOOBeoADwAfAABB" +
  "IiYmNTQ2NjMyFhYVFAYGJzI2NjU0JiYjIgYGFRQWFgHufbxnZ7x9fbtoaLt9U2s1NGxTUms1NWsCiG3CgYPDbGzDg4HDbI9Pg09P" +
  "hFBPhFBPg08AAgBuAAAEHgXSAAwAEAAAQSERIyImJjU0NjYzIQMRMxEEFf6aVJ/ccnLcnwG6srsFLPz8etWHhtN7+i4F0vouAAIA" +
  "ev7SBBIF5gA+AFAAAEEiJiYnNxYWMzI2NTQmJiclLgI1NDY2NzcmJjU0NjMyFhcHJiYjIgYVFBYWFwUeAhUUBgYHBx4CFRQGBhMW" +
  "NjY1NCYmJyUmBgYVFBYWFwIzcqJjFqEZaW5dcjJIIv7mQGE1OGZGA0NEzKajsiuYIlxmYGoySSMBGkJfMztnQgMwPR5irg4fWkUf" +
  "PC3+4iBUPh4+MP7SSothKltrUU83SjQTpCZmdjw9cUwEBTlyT46lopcpYWdWSTVLNBWmJ2dyOj9vSAYHJE5YMl6KSwKMEhlSQilG" +
  "PRmkExxTQShHQBwAAAEAYwOCAfMGrgAHAABBESMRIwc1NwHzrQjbzwau/NQCmYGYfAAAAQBwA4IDHQa4ABwAAFM1AT4CNTQmIyIG" +
  "FSM0NjMyFhUUDgIHBxUhFXYBVDBAH15FR1mmt5CXtRQ2ZlKZAbUDgnsBDSY6NR42Pz82comFaCFDTFw8bweLAAEAZwN4AzQGuAAt" +
  "AABBIiYmJzMWFjMyNjU0JiMjNTMyNjU0JiMiBgcjPgIzMhYWFRQGBxUWFhUUBgYBymKgXwKwAmpJTmNrXExMTWRWREZjAqcBW5le" +
  "YZFQZlNrcl2jA3g6aUYoMz4vMT57PTAtOTctRmo8PWhBRFsLBg1iTUVsPQAB/nAAAAMZBdIAAwAAYQEzAf5wBACp/AAF0vouAAAB" +
  "AEsAAAG2AywABwAAQREjESMHNTcBtqEJwaMDLPzUAqSVoH0AAAEAYwAAApADNQAaAABzNQE2NjU0JiMiBhUjNDYzMhYVFAYGBwcV" +
  "IRVqARA1O0svMkCbn3N6liBaV2oBRmwBJzlVLi80NjFtfYRdJVF4YHUKhwABAGT/9wK/AzUALAAARSImJiczFhYzMjY1NCYjIzUz" +
  "MjY1NCYjIgYHIz4CMzIWFhUUBgcVFhYVFAYBj1OETwWjB1EwOlBITVRUN0U5MStYBJoEUoJMVXM8ST5WU6wJL1c7GSA5LjRFfj80" +
  "LDUmIz1cNEBlN0ZeDgoKZ05jhAACAFsAAALKAywACQAPAAB3NQEzFSMDFSEVBzU3ETMRWwFEaUPJAc79A5d9gQIuwP6iC4Z9ozsC" +
  "TvzUAP//AEsAAAZmBdIEJwDCAAACpgAnAMECTQAAAAcAwwPWAAD//wBLAAAGFAXSBCcAwgAAAqYAJwDBAk0AAAAHAMUDSgAA//8A" +
  "ZAAABrcF2wQnAMQAAAKmACcAwQLwAAAABwDFA+0AAAAFAOb/4wb1BeoAEQAfADEAPwBDAABBIiYmNTU0NjYzMhYWFRUUBgYnMjY1" +
  "NTQmIyIGFRUUFgEiJiY1NTQ2NjMyFhYVFRQGBicyNjU1NCYjIgYVFRQWBQEzAQILX4NDRINeYIFCQ4FfTD48TktBPwQUX4NDRINe" +
  "YIJBQ4FfTD48TktBP/wPBACp/AADP1OKUk5SiVNTiVJOUopTg2lDTkJqakJOQ2n8IVOKUk5SiVNTiVJOUopTg2lDTkJqakJOQ2lm" +
  "BdL6Lv//AKgE8AH9BhYEBgDPAAD//wCWBPAB6wYWBAYA0AAA//8BFAUVA6YGAgQGANYAAP//ANQFRQL+BdMEBgDRAAD//wCb/l4B" +
  "+QAwBAYA2gAAAAEAqATwAf0GFgADAABTEzMDqIzJwgTwASb+2gABAJYE8AHrBhYAAwAAQQMzEwFXwcmMBPABJv7aAAABANQFRQL+" +
  "BdMAAwAAQRUhNQL+/dYF046OAAEA4gUhAygF9QAXAABBIi4CIyIGByM2NjMyHgIzMjY3MwYGAoglRz81ExoZAn4DT1AnQjo1GRka" +
  "BXsDUwUhGSEZMh1adhohGiYrXnIA//8AFAAABWcF0gQmAAwbAAAGAN7iAAACARQFFQOmBgIACwAXAABBIiY1NDYzMhYVFAYhIiY1" +
  "NDYzMhYVFAYDMDFGRjExRUX+KjFGRjExRUUFFUYxMUVFMTFGRjExRUUxMUYAAQB6BRUBdQYDAAsAAFMiJjU0NjMyFhUUBvczSkoz" +
  "NEpKBRVGMTJFRTIxRgABAGYFAgLoBhYACAAAQSM1EzMTFSMnARex66vss44FAgkBC/71Ca8AAgAqBKUCOAacAA8AGwAAQSImJjU0" +
  "NjYzMhYWFRQGBicyNjU0JiMiBhUUFgExSHhHR3hISXdHR3dJNUlJNTRJSQSlRHJGRnFERHFGRnJEfko0NElJNDRKAAEAm/5eAfkA" +
  "MAATAABTNTMyNjU0JiMjNzMVFRYWFRQGI5t2NysrN1IeX2Jbb3j+XmkdJSUc5jBWBE1RWFIAAgAqBgUCOAf6AA8AGwAAQSImJjU0" +
  "NjYzMhYWFRQGBicyNjU0JiMiBhUUFgExSXdHR3dJSXdHR3dJNElINTRJSQYFRHJFRnFDQ3FGRXJEfkk0NElJNDRJAAEABv/SBJYG" +
  "AAADAABXJwEXiIIEDoIuWgXUWgABAFL/0wR2BIsAAwAAVycBF71rA7pqLVoEXloAAQAyApwDNwM2AAMAAFM1IRUyAwUCnJqaAAAB" +
  "AAAA3wCEAAwAcAAHAAEAAAAAAAAAAAAAAAAABwABAAAAagCPAJsApwCzAL8AywDXAPwBOQFzAX8BrQHEAdAB3AHoAfQCCQJHAl4C" +
  "bAJ4AoQCkAKcArkC5gL1AzwDaQN1A60DuQPFA9ED3QPpA/UEGwRgBI8E2QTrBRAFHAUoBTQFQAVfBZ8F1wX5BgUGLwaBBo0GmQak" +
  "BrAGvAbHBz0HeAe0B+0H+Qg0CHAIewiHCJMInwjECRIJOAlDCU8JWwlnCXIJfgmWCaEJxAnSCg4KNAo/CnMKfgqJCpQKoAqsCrgK" +
  "9AswC1ALkgvOC/EMFgwhDFcMYwxvDHsMmQzXDQkNOQ1EDVANaA2TDeAOMQ5wDp0O4Q8mD30Psw/HD/gQQhBiEJ0Q6RD8EVgRpRIE" +
  "EiISQBKEEsgS6hMMEx4TMBNxE7MUNhRcFLAUwBTOFOIU8RT+FQsVGBU1FUMVURVfFWsVdxWDFYwVohWyFb4VyxXUFegV/BYIFhQW" +
  "LBZGFloWbhaGFrQWzxb8Fw0XGRc1F14XtxgiGFQYnhjQGPAZaBl7GacZ6Bn3GgoaMxpyGpAaoRqyGsMbJhsuGzYbPhtGG04bXBtr" +
  "G3gbnxufG58bqhvQG+Yb+hwmHEUccRx/HI0cmgABAAAABABCKVHOr18PPPUAAwgAAAAAAOJ2h5AAAAAA5sXhL/oX/WwUqgjdAAAA" +
  "AwACAAAAAAAABUABSAWFADQFhQA0BYUANAWFADQFhQA0BYUANAWFADQH8wA0BTwAtAXYAHoF2AB6BcYAtATPALQEzwC0BM8AtATP" +
  "ALQEzwC0BLkAtAX4AHoF8gC0AiYAtAIm/8oCJgALAiYAtAIm/9IEkQBkBWAAtASGALQHOgC0BgcAtAYHALQGHgB6Bh4AegYeAHoG" +
  "HgB6Bh4AegYeAHoGHgB6BRwAtAYeAHoFJgC0BSIAdAUqAGIF9AC0BfQAtAX0ALQF9AC0BfQAtAWFADQH4gA0BXUAOQVuADQFbgA0" +
  "BQgAegR+AFoEfgBaBH4AWgR+AFoEfgBaBH4AWgR+AFoHVwBaBOYAngTmAJ4EkgBoBJIAaATmAGgEqgBoBKoAaASqAGgEqgBoBKoA" +
  "aAL2ABQE6ABoBLsAngHwAHwB8ACeAfD/sAHw//EB8ACeAfD/uAHw/+YB8P/mBGQAngHwAJ4HAgCeBLoAngS6AJ4EzABoBMwAaATM" +
  "AGgEzABTBMwAaATMAGgEzABoBOYAngTmAGgDAwCeBDkAbATuALQCngAUBLsAngS7AJ4EsACeBLsAngS7AJ4EuwCeBH8ANgaMAEYE" +
  "XgBBBH8ANgR/ADYEfwA2BGsAfgUWAKgEqQBoBSIAdASSAGgEZgAeBOMAbgX4AHoF1gB6BQwAegNBAGAE4QCaBPEAfQUrAHgEvwCA" +
  "BPYAegSHAGIE8wB6BPYAegUnAGgCTQCgAk0AoAQXAFIEFwBmAusA2gLrAGAC6wDiAusAewNpAJADaQB7B7oAegURACIFzAB4AuIA" +
  "LgKpAQYCKQDAAuIALgOuAJAEAAAACAAAAASAAQACFgCgAhYAoAJmANIDugDSA4YAoAOGAKACTgCAAk4AoAbqAKACTgCgAmoAgAJO" +
  "AKADEwBkAxMAUASpAGQEqQBQBUsArgVLAO0FSwDiBUsAwwVLANIFSwDSBUsAzgVLAKYFSwDgA6YAAAPFAFIEAgByBVQAZAdQAKgD" +
  "pQCCA6EAQwPcAE4E0gBuBIwAegJvAGMDiQBwA5EAZwGJ/nACGwBLAvEAYwMNAGQDIQBbBscASwZrAEsHDgBkB9sA5gKVAKgClQCW" +
  "BLoBFAPSANQCJQCbAAAAqAAAAJYAAADUAAAA4gJAAAACQAAABeEAFAAAARQAAAB6AAAAZgAAACoAAACbAAAAKgScAAYEyQBSA2kA" +
  "MgABAAAHwP4SAAAVdPoX92gUqggAAAAAAAAAAAAAAAAAAAAA3wAEBR8BkAAFAAAFMwTNAAAAmgUzBM0AAALNAIwCnwAAAgAFAwAA" +
  "AAIABIAAAAMAAAACAAAAAAAAAABSU01TAMAAICCyB8D+EgAACN0ClAAAAAEAAAAABF4F0gAAACAADAAAAAIAAAADAAAAFAADAAEA" +
  "AAAUAAQB4AAAABoAEAADAAoALwA5AH4ArAD/IBQgGSAdICIgJiCiILL//wAAACAAMAA6AKAAriATIBggHCAiICYgoiCy//8AAABL" +
  "AAAAAAAA4IXgg+CD4Hjgfd/Y38cAAQAaAAAANgC+ANYAAAAAAAAAAAAAAAAAAAAAANMAhgCeAJEAdQDJAIUAnQCKAIsAtgCuAKEA" +
  "lwCiAJMApAClAKsArQCsAIgAkAABAAkACgAMAA0AEgATABQAFQAaABsAHAAdAB4AIAAnACgAKQAqACsALAAxADIAMwA0ADYAjACW" +
  "AI0AtQC0AMsANwA/AEEAQwBEAEkASgBLAEwAUwBUAFUAVgBXAFkAYABhAGIAYwBlAGYAbABtAG4AbwByAI4AlACPALIA1ACHAHYA" +
  "eACSAHcAlQC9AMwAuAC6AKkAswC3AM0AuQCxAL8AwADKAGgAvACmAM4AvgC7AKoAxwDGAMgAiQAEAAUABgADAAIABwAIAAsADgAP" +
  "ABAAEQAXABgAGQAWANUAHwAkACUAJgAiACEArwAjAC0ALgAvADAANQBzAGQAOwA4ADkAPQA6ADwAPgBCAEYARwBIAEUATwBQAFEA" +
  "TgB0AFgAXQBeAF8AWwBaALAAXABpAGoAawBnAHEAQABwAAAACgB+AAMAAQQJAAEACgAAAAMAAQQJAAIADgAKAAMAAQQJAAMAXAAY" +
  "AAMAAQQJAAQAGgB0AAMAAQQJAAYAGgCOAAMAAQQJAQEADACoAAMAAQQJATgAGAC0AAMAAQQJATkACADMAAMAAQQJAUAADADUAAMA" +
  "AQQJAUEACgDgAEkAbgB0AGUAcgBSAGUAZwB1AGwAYQByADQALgAwADAAMQA7AGcAaQB0AC0ANgA2ADYANAA3AGMAMABiAGIAOwBS" +
  "AFMATQBTADsASQBuAHQAZQByAC0AUgBlAGcAdQBsAGEAcgAtAFIAZQBnAHUAbABhAHIASQBuAHQAZQByACAAUgBlAGcAdQBsAGEA" +
  "cgBJAG4AdABlAHIALQBSAGUAZwB1AGwAYQByAFcAZQBpAGcAaAB0AE8AcAB0AGkAYwBhAGwAIABTAGkAegBlADEANABwAHQASQB0" +
  "AGEAbABpAGMAUgBvAG0AYQBuAAMAAAAAAAD+pACMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAB//8ADwABAAEACAADAAAAFAADAAAA" +
  "LAACb3BzegE4AAB3Z2h0AQEAAWl0YWwBQAACAAYAEgAiAAEAAAACATkADgAAAAMAAQACAAIBkAAAArwAAAADAAIAAgFBAAAAAAAB" +
  "AAAAAA==";
